// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contests.sql

package dbgen

import (
	"context"
	"time"
)

const countVisibleContests = `-- name: CountVisibleContests :one
SELECT count(*) FROM contests c LEFT JOIN LATERAL (
 SELECT COALESCE(bool_or(a.role='editor'),false)::boolean AS editor,COALESCE(bool_or(a.role='jury'),false)::boolean AS jury,
 COALESCE(bool_or(a.role='observer'),false)::boolean AS observer,COALESCE(bool_or(a.role='participant'),false)::boolean AS participant
 FROM contest_access a WHERE a.contest_id=c.id AND a.domain_id=c.domain_id
 AND (a.user_id=NULLIF($1::text,'')::uuid OR a.group_id IN (SELECT group_id FROM domain_group_members WHERE domain_id=c.domain_id AND user_id=NULLIF($1::text,'')::uuid))) grants ON true
WHERE c.domain_id=$2::uuid AND CASE WHEN $3::boolean THEN ($4::boolean OR ($5::boolean AND (c.owner_id=NULLIF($1::text,'')::uuid OR grants.editor OR grants.jury OR grants.observer))) ELSE
 (c.visibility IN ('public','password') OR ($4::boolean OR ($5::boolean AND (c.owner_id=NULLIF($1::text,'')::uuid OR grants.editor OR grants.jury OR grants.observer))) OR ($5::boolean AND (grants.participant OR ($6::boolean AND c.admission='members' AND EXISTS(SELECT 1 FROM contest_participants cp WHERE cp.contest_id=c.id AND cp.user_id=NULLIF($1::text,'')::uuid))))) END
 AND ($7::text='' OR strpos(lower(c.title),lower($7::text))>0 OR c.public_id::text=$7::text)
`

type CountVisibleContestsParams struct {
	ViewerID     string
	DomainID     string
	ManagedOnly  bool
	IsManager    bool
	ActiveMember bool
	CanSubmit    bool
	Keyword      string
}

func (q *Queries) CountVisibleContests(ctx context.Context, arg CountVisibleContestsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVisibleContests,
		arg.ViewerID,
		arg.DomainID,
		arg.ManagedOnly,
		arg.IsManager,
		arg.ActiveMember,
		arg.CanSubmit,
		arg.Keyword,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getContest = `-- name: GetContest :one
SELECT c.id,c.public_id,c.title,c.description,c.rule,c.begin_at,c.end_at,c.freeze_at,c.unfreeze_at,
 c.penalty_minutes,c.penalize_compile_error,c.feedback,c.visibility,c.password_hash,c.rankboard_visible,c.show_problem_metadata,c.created_by,c.created_at,
 c.owner_id,c.domain_id,c.admission,COALESCE((SELECT u.username FROM users u WHERE u.id=c.owner_id),'')::text AS owner_name,c.allow_self_registration,c.allow_late_registration,false AS editor,false AS jury,false AS observer,false AS participant,false AS registered FROM contests c WHERE c.id=$1::uuid AND c.domain_id=$2::uuid
`

type GetContestParams struct {
	ContestID string
	DomainID  string
}

type GetContestRow struct {
	ID                    string
	PublicID              string
	Title                 string
	Description           string
	Rule                  string
	BeginAt               time.Time
	EndAt                 time.Time
	FreezeAt              *time.Time
	UnfreezeAt            *time.Time
	PenaltyMinutes        int
	PenalizeCompileError  bool
	Feedback              string
	Visibility            string
	PasswordHash          string
	RankboardVisible      bool
	ShowProblemMetadata   bool
	CreatedBy             *string
	CreatedAt             time.Time
	OwnerID               string
	DomainID              string
	Admission             string
	OwnerName             string
	AllowSelfRegistration bool
	AllowLateRegistration bool
	Editor                bool
	Jury                  bool
	Observer              bool
	Participant           bool
	Registered            bool
}

func (q *Queries) GetContest(ctx context.Context, arg GetContestParams) (GetContestRow, error) {
	row := q.db.QueryRowContext(ctx, getContest, arg.ContestID, arg.DomainID)
	var i GetContestRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Description,
		&i.Rule,
		&i.BeginAt,
		&i.EndAt,
		&i.FreezeAt,
		&i.UnfreezeAt,
		&i.PenaltyMinutes,
		&i.PenalizeCompileError,
		&i.Feedback,
		&i.Visibility,
		&i.PasswordHash,
		&i.RankboardVisible,
		&i.ShowProblemMetadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.OwnerID,
		&i.DomainID,
		&i.Admission,
		&i.OwnerName,
		&i.AllowSelfRegistration,
		&i.AllowLateRegistration,
		&i.Editor,
		&i.Jury,
		&i.Observer,
		&i.Participant,
		&i.Registered,
	)
	return i, err
}

const listVisibleContests = `-- name: ListVisibleContests :many
SELECT c.id,c.public_id,c.title,c.description,c.rule,c.begin_at,c.end_at,c.freeze_at,c.unfreeze_at,
 c.penalty_minutes,c.penalize_compile_error,c.feedback,c.visibility,c.password_hash,c.rankboard_visible,c.show_problem_metadata,c.created_by,c.created_at,
 c.owner_id,c.domain_id,c.admission,COALESCE((SELECT u.username FROM users u WHERE u.id=c.owner_id),'')::text AS owner_name,c.allow_self_registration,c.allow_late_registration,grants.editor,grants.jury,grants.observer,grants.participant,EXISTS(SELECT 1 FROM contest_participants cp WHERE cp.contest_id=c.id AND cp.user_id=NULLIF($1::text,'')::uuid) AS registered
FROM contests c LEFT JOIN LATERAL (
 SELECT COALESCE(bool_or(a.role='editor'),false)::boolean AS editor,COALESCE(bool_or(a.role='jury'),false)::boolean AS jury,
 COALESCE(bool_or(a.role='observer'),false)::boolean AS observer,COALESCE(bool_or(a.role='participant'),false)::boolean AS participant
 FROM contest_access a WHERE a.contest_id=c.id AND a.domain_id=c.domain_id
 AND (a.user_id=NULLIF($1::text,'')::uuid OR a.group_id IN (SELECT group_id FROM domain_group_members WHERE domain_id=c.domain_id AND user_id=NULLIF($1::text,'')::uuid))) grants ON true
WHERE c.domain_id=$2::uuid AND CASE WHEN $3::boolean THEN ($4::boolean OR ($5::boolean AND (c.owner_id=NULLIF($1::text,'')::uuid OR grants.editor OR grants.jury OR grants.observer))) ELSE
 (c.visibility IN ('public','password') OR ($4::boolean OR ($5::boolean AND (c.owner_id=NULLIF($1::text,'')::uuid OR grants.editor OR grants.jury OR grants.observer))) OR ($5::boolean AND (grants.participant OR ($6::boolean AND c.admission='members' AND EXISTS(SELECT 1 FROM contest_participants cp WHERE cp.contest_id=c.id AND cp.user_id=NULLIF($1::text,'')::uuid))))) END
 AND ($7::text='' OR strpos(lower(c.title),lower($7::text))>0 OR c.public_id::text=$7::text)
ORDER BY c.begin_at DESC,c.id DESC LIMIT $9::integer OFFSET $8::integer
`

type ListVisibleContestsParams struct {
	ViewerID     string
	DomainID     string
	ManagedOnly  bool
	IsManager    bool
	ActiveMember bool
	CanSubmit    bool
	Keyword      string
	PageOffset   int
	PageLimit    int
}

type ListVisibleContestsRow struct {
	ID                    string
	PublicID              string
	Title                 string
	Description           string
	Rule                  string
	BeginAt               time.Time
	EndAt                 time.Time
	FreezeAt              *time.Time
	UnfreezeAt            *time.Time
	PenaltyMinutes        int
	PenalizeCompileError  bool
	Feedback              string
	Visibility            string
	PasswordHash          string
	RankboardVisible      bool
	ShowProblemMetadata   bool
	CreatedBy             *string
	CreatedAt             time.Time
	OwnerID               string
	DomainID              string
	Admission             string
	OwnerName             string
	AllowSelfRegistration bool
	AllowLateRegistration bool
	Editor                bool
	Jury                  bool
	Observer              bool
	Participant           bool
	Registered            bool
}

func (q *Queries) ListVisibleContests(ctx context.Context, arg ListVisibleContestsParams) ([]ListVisibleContestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleContests,
		arg.ViewerID,
		arg.DomainID,
		arg.ManagedOnly,
		arg.IsManager,
		arg.ActiveMember,
		arg.CanSubmit,
		arg.Keyword,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleContestsRow{}
	for rows.Next() {
		var i ListVisibleContestsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.Description,
			&i.Rule,
			&i.BeginAt,
			&i.EndAt,
			&i.FreezeAt,
			&i.UnfreezeAt,
			&i.PenaltyMinutes,
			&i.PenalizeCompileError,
			&i.Feedback,
			&i.Visibility,
			&i.PasswordHash,
			&i.RankboardVisible,
			&i.ShowProblemMetadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.OwnerID,
			&i.DomainID,
			&i.Admission,
			&i.OwnerName,
			&i.AllowSelfRegistration,
			&i.AllowLateRegistration,
			&i.Editor,
			&i.Jury,
			&i.Observer,
			&i.Participant,
			&i.Registered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
