// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: numbers.sql

package dbgen

import (
	"context"
)

const resolveContestNumber = `-- name: ResolveContestNumber :one
SELECT id FROM contests WHERE domain_id=$1::uuid AND public_id=$2::bigint
`

type ResolveContestNumberParams struct {
	DomainID string
	PublicID int64
}

func (q *Queries) ResolveContestNumber(ctx context.Context, arg ResolveContestNumberParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveContestNumber, arg.DomainID, arg.PublicID)
	var id string
	err := row.Scan(&id)
	return id, err
}
