// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package dbgen

import (
	"context"
	"time"
)

const createContest = `-- name: CreateContest :one
INSERT INTO contests AS c (title, description, rule, begin_at, end_at, freeze_at, unfreeze_at,
		                      penalty_minutes, penalize_compile_error, feedback,
		                      visibility, password_hash, rankboard_visible, created_by, domain_id,owner_id,admission,allow_self_registration,allow_late_registration)
		 VALUES ($1::text, $2::text, $3::text, $4::timestamptz, $5::timestamptz, $6::timestamptz, $7::timestamptz, $8::integer, $9::boolean, $10::text, $11::text, $12::text, $13::boolean, $14::uuid, $15::uuid,$14::uuid,$16::text,$17::boolean,$18::boolean)
		 RETURNING c.id,c.public_id,c.title,c.description,c.rule,c.begin_at,c.end_at,c.freeze_at,c.unfreeze_at,
 c.penalty_minutes,c.penalize_compile_error,c.feedback,c.visibility,c.password_hash,c.rankboard_visible,c.created_by,c.created_at,
 c.owner_id,c.domain_id,c.admission,COALESCE((SELECT u.username FROM users u WHERE u.id=c.owner_id),'')::text AS owner_name,c.allow_self_registration,c.allow_late_registration,false AS editor,false AS jury,false AS observer,false AS participant,false AS registered
`

type CreateContestParams struct {
	Title                 string
	Description           string
	Rule                  string
	BeginAt               time.Time
	EndAt                 time.Time
	FreezeAt              *time.Time
	UnfreezeAt            *time.Time
	PenaltyMinutes        int
	PenalizeCompileError  bool
	Feedback              string
	Visibility            string
	PasswordHash          string
	RankboardVisible      bool
	CreatorID             string
	DomainID              string
	Admission             string
	AllowSelfRegistration bool
	AllowLateRegistration bool
}

type CreateContestRow struct {
	ID                    string
	PublicID              string
	Title                 string
	Description           string
	Rule                  string
	BeginAt               time.Time
	EndAt                 time.Time
	FreezeAt              *time.Time
	UnfreezeAt            *time.Time
	PenaltyMinutes        int
	PenalizeCompileError  bool
	Feedback              string
	Visibility            string
	PasswordHash          string
	RankboardVisible      bool
	CreatedBy             *string
	CreatedAt             time.Time
	OwnerID               string
	DomainID              string
	Admission             string
	OwnerName             string
	AllowSelfRegistration bool
	AllowLateRegistration bool
	Editor                bool
	Jury                  bool
	Observer              bool
	Participant           bool
	Registered            bool
}

func (q *Queries) CreateContest(ctx context.Context, arg CreateContestParams) (CreateContestRow, error) {
	row := q.db.QueryRowContext(ctx, createContest,
		arg.Title,
		arg.Description,
		arg.Rule,
		arg.BeginAt,
		arg.EndAt,
		arg.FreezeAt,
		arg.UnfreezeAt,
		arg.PenaltyMinutes,
		arg.PenalizeCompileError,
		arg.Feedback,
		arg.Visibility,
		arg.PasswordHash,
		arg.RankboardVisible,
		arg.CreatorID,
		arg.DomainID,
		arg.Admission,
		arg.AllowSelfRegistration,
		arg.AllowLateRegistration,
	)
	var i CreateContestRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Description,
		&i.Rule,
		&i.BeginAt,
		&i.EndAt,
		&i.FreezeAt,
		&i.UnfreezeAt,
		&i.PenaltyMinutes,
		&i.PenalizeCompileError,
		&i.Feedback,
		&i.Visibility,
		&i.PasswordHash,
		&i.RankboardVisible,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.OwnerID,
		&i.DomainID,
		&i.Admission,
		&i.OwnerName,
		&i.AllowSelfRegistration,
		&i.AllowLateRegistration,
		&i.Editor,
		&i.Jury,
		&i.Observer,
		&i.Participant,
		&i.Registered,
	)
	return i, err
}

const updateContest = `-- name: UpdateContest :one
UPDATE contests AS c SET title = $1::text, description = $2::text, rule = $3::text, begin_at = $4::timestamptz,
		        end_at = $5::timestamptz, freeze_at = $6::timestamptz, unfreeze_at = $7::timestamptz,
		        penalty_minutes = $8::integer, penalize_compile_error = $9::boolean, feedback = $10::text,
		        visibility = $11::text,
		        password_hash = CASE
		          WHEN $12::text <> '' THEN $12::text
		          WHEN $11::text = 'password' THEN password_hash
		          ELSE ''
		        END,
		        rankboard_visible = $13::boolean, admission=$14::text, allow_self_registration=$15::boolean, allow_late_registration=$16::boolean
		 WHERE c.id = $17::uuid AND domain_id = $18::uuid
		 RETURNING c.id,c.public_id,c.title,c.description,c.rule,c.begin_at,c.end_at,c.freeze_at,c.unfreeze_at,
 c.penalty_minutes,c.penalize_compile_error,c.feedback,c.visibility,c.password_hash,c.rankboard_visible,c.created_by,c.created_at,
 c.owner_id,c.domain_id,c.admission,COALESCE((SELECT u.username FROM users u WHERE u.id=c.owner_id),'')::text AS owner_name,c.allow_self_registration,c.allow_late_registration,false AS editor,false AS jury,false AS observer,false AS participant,false AS registered
`

type UpdateContestParams struct {
	Title                 string
	Description           string
	Rule                  string
	BeginAt               time.Time
	EndAt                 time.Time
	FreezeAt              *time.Time
	UnfreezeAt            *time.Time
	PenaltyMinutes        int
	PenalizeCompileError  bool
	Feedback              string
	Visibility            string
	PasswordHash          string
	RankboardVisible      bool
	Admission             string
	AllowSelfRegistration bool
	AllowLateRegistration bool
	ContestID             string
	DomainID              string
}

type UpdateContestRow struct {
	ID                    string
	PublicID              string
	Title                 string
	Description           string
	Rule                  string
	BeginAt               time.Time
	EndAt                 time.Time
	FreezeAt              *time.Time
	UnfreezeAt            *time.Time
	PenaltyMinutes        int
	PenalizeCompileError  bool
	Feedback              string
	Visibility            string
	PasswordHash          string
	RankboardVisible      bool
	CreatedBy             *string
	CreatedAt             time.Time
	OwnerID               string
	DomainID              string
	Admission             string
	OwnerName             string
	AllowSelfRegistration bool
	AllowLateRegistration bool
	Editor                bool
	Jury                  bool
	Observer              bool
	Participant           bool
	Registered            bool
}

func (q *Queries) UpdateContest(ctx context.Context, arg UpdateContestParams) (UpdateContestRow, error) {
	row := q.db.QueryRowContext(ctx, updateContest,
		arg.Title,
		arg.Description,
		arg.Rule,
		arg.BeginAt,
		arg.EndAt,
		arg.FreezeAt,
		arg.UnfreezeAt,
		arg.PenaltyMinutes,
		arg.PenalizeCompileError,
		arg.Feedback,
		arg.Visibility,
		arg.PasswordHash,
		arg.RankboardVisible,
		arg.Admission,
		arg.AllowSelfRegistration,
		arg.AllowLateRegistration,
		arg.ContestID,
		arg.DomainID,
	)
	var i UpdateContestRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Description,
		&i.Rule,
		&i.BeginAt,
		&i.EndAt,
		&i.FreezeAt,
		&i.UnfreezeAt,
		&i.PenaltyMinutes,
		&i.PenalizeCompileError,
		&i.Feedback,
		&i.Visibility,
		&i.PasswordHash,
		&i.RankboardVisible,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.OwnerID,
		&i.DomainID,
		&i.Admission,
		&i.OwnerName,
		&i.AllowSelfRegistration,
		&i.AllowLateRegistration,
		&i.Editor,
		&i.Jury,
		&i.Observer,
		&i.Participant,
		&i.Registered,
	)
	return i, err
}
