// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clarifications.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createClarification = `-- name: CreateClarification :one
INSERT INTO clarifications
		   (contest_id, problem_id, parent_id, author_id, recipient_id, from_jury, subject, body, domain_id)
		 VALUES ($1::uuid, $2::uuid, $3::bigint, $4::uuid, $5::uuid, $6::boolean, $7::text, $8::text, $9::uuid)
		 RETURNING id
`

type CreateClarificationParams struct {
	ContestID   string
	ProblemID   *string
	ParentID    sql.NullInt64
	AuthorID    *string
	RecipientID *string
	FromJury    bool
	Subject     string
	Body        string
	DomainID    string
}

func (q *Queries) CreateClarification(ctx context.Context, arg CreateClarificationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createClarification,
		arg.ContestID,
		arg.ProblemID,
		arg.ParentID,
		arg.AuthorID,
		arg.RecipientID,
		arg.FromJury,
		arg.Subject,
		arg.Body,
		arg.DomainID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findClarificationProblem = `-- name: FindClarificationProblem :one
SELECT problem_id FROM contest_problems
			 WHERE contest_id = $1::uuid AND problem_id = $2::uuid
			 FOR KEY SHARE
`

type FindClarificationProblemParams struct {
	ContestID string
	ProblemID string
}

func (q *Queries) FindClarificationProblem(ctx context.Context, arg FindClarificationProblemParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findClarificationProblem, arg.ContestID, arg.ProblemID)
	var problem_id string
	err := row.Scan(&problem_id)
	return problem_id, err
}

const getClarification = `-- name: GetClarification :one
SELECT c.id, c.contest_id, c.problem_id, c.parent_id, c.author_id,
	COALESCE(author.username, '') AS author_name, c.recipient_id, c.from_jury, c.subject, c.body,
	c.answered, c.created_at, COALESCE(p.title, '') AS problem_name
		 FROM clarifications AS c
		 LEFT JOIN users AS author ON author.id = c.author_id
		 LEFT JOIN problems AS p ON p.id = c.problem_id
		 WHERE c.contest_id = $1::uuid AND c.id = $2::bigint
		 AND EXISTS (SELECT 1 FROM contests WHERE contests.id = $1::uuid AND contests.domain_id = $3::uuid)
`

type GetClarificationParams struct {
	ContestID       string
	ClarificationID int64
	DomainID        string
}

type GetClarificationRow struct {
	ID          int64
	ContestID   string
	ProblemID   *string
	ParentID    sql.NullInt64
	AuthorID    *string
	AuthorName  string
	RecipientID *string
	FromJury    bool
	Subject     string
	Body        string
	Answered    bool
	CreatedAt   time.Time
	ProblemName string
}

func (q *Queries) GetClarification(ctx context.Context, arg GetClarificationParams) (GetClarificationRow, error) {
	row := q.db.QueryRowContext(ctx, getClarification, arg.ContestID, arg.ClarificationID, arg.DomainID)
	var i GetClarificationRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ProblemID,
		&i.ParentID,
		&i.AuthorID,
		&i.AuthorName,
		&i.RecipientID,
		&i.FromJury,
		&i.Subject,
		&i.Body,
		&i.Answered,
		&i.CreatedAt,
		&i.ProblemName,
	)
	return i, err
}

const getClarificationParent = `-- name: GetClarificationParent :one
SELECT contest_id, author_id, problem_id FROM clarifications WHERE id = $1::bigint
`

type GetClarificationParentRow struct {
	ContestID string
	AuthorID  *string
	ProblemID *string
}

func (q *Queries) GetClarificationParent(ctx context.Context, parentID int64) (GetClarificationParentRow, error) {
	row := q.db.QueryRowContext(ctx, getClarificationParent, parentID)
	var i GetClarificationParentRow
	err := row.Scan(&i.ContestID, &i.AuthorID, &i.ProblemID)
	return i, err
}

const listVisibleClarifications = `-- name: ListVisibleClarifications :many
SELECT c.id,c.contest_id,c.problem_id,c.parent_id,c.author_id,COALESCE(author.username,'') AS author_name,c.recipient_id,c.from_jury,c.subject,c.body,c.answered,c.created_at,COALESCE(p.title,'') AS problem_name
FROM clarifications c LEFT JOIN users author ON author.id=c.author_id LEFT JOIN problems p ON p.id=c.problem_id
WHERE c.contest_id=$1::uuid AND EXISTS(SELECT 1 FROM contests parent WHERE parent.id=c.contest_id AND parent.domain_id=$2::uuid)
AND ($3::boolean OR (c.from_jury AND c.recipient_id IS NULL)
 OR c.author_id=NULLIF($4::text,'')::uuid OR c.recipient_id=NULLIF($4::text,'')::uuid
 OR c.parent_id IN(SELECT id FROM clarifications WHERE author_id=NULLIF($4::text,'')::uuid))
ORDER BY COALESCE(c.parent_id,c.id) DESC,c.id
`

type ListVisibleClarificationsParams struct {
	ContestID string
	DomainID  string
	IsStaff   bool
	ViewerID  string
}

type ListVisibleClarificationsRow struct {
	ID          int64
	ContestID   string
	ProblemID   *string
	ParentID    sql.NullInt64
	AuthorID    *string
	AuthorName  string
	RecipientID *string
	FromJury    bool
	Subject     string
	Body        string
	Answered    bool
	CreatedAt   time.Time
	ProblemName string
}

func (q *Queries) ListVisibleClarifications(ctx context.Context, arg ListVisibleClarificationsParams) ([]ListVisibleClarificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleClarifications,
		arg.ContestID,
		arg.DomainID,
		arg.IsStaff,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleClarificationsRow{}
	for rows.Next() {
		var i ListVisibleClarificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.ProblemID,
			&i.ParentID,
			&i.AuthorID,
			&i.AuthorName,
			&i.RecipientID,
			&i.FromJury,
			&i.Subject,
			&i.Body,
			&i.Answered,
			&i.CreatedAt,
			&i.ProblemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markClarificationAnswered = `-- name: MarkClarificationAnswered :exec
UPDATE clarifications SET answered=true WHERE contest_id=$1::uuid AND id=$2::bigint
`

type MarkClarificationAnsweredParams struct {
	ContestID string
	ParentID  int64
}

func (q *Queries) MarkClarificationAnswered(ctx context.Context, arg MarkClarificationAnsweredParams) error {
	_, err := q.db.ExecContext(ctx, markClarificationAnswered, arg.ContestID, arg.ParentID)
	return err
}
