// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: composition.sql

package dbgen

import (
	"context"
	"encoding/json"
)

const deleteContestProblems = `-- name: DeleteContestProblems :exec
DELETE FROM contest_problems WHERE contest_id = $1::uuid
`

func (q *Queries) DeleteContestProblems(ctx context.Context, contestID string) error {
	_, err := q.db.ExecContext(ctx, deleteContestProblems, contestID)
	return err
}

const deleteRemovedContestCells = `-- name: DeleteRemovedContestCells :exec
DELETE FROM contest_submission_cells
		 WHERE contest_submission_cells.contest_id = $1::uuid AND problem_id NOT IN (
		   SELECT problem_id FROM contest_problems WHERE contest_problems.contest_id = $1::uuid)
`

func (q *Queries) DeleteRemovedContestCells(ctx context.Context, contestID string) error {
	_, err := q.db.ExecContext(ctx, deleteRemovedContestCells, contestID)
	return err
}

const getContestProblemByID = `-- name: GetContestProblemByID :one
SELECT cp.contest_id,c.public_id AS contest_public_id,cp.problem_id,p.public_id AS problem_public_id,cp.sort_order,cp.label,cp.color,cp.points,
v.title,v.difficulty,p.visibility,v.tags_json,v.statement_md,v.source,v.time_limit_ms,v.memory_limit_kb,v.judge_type,cp.problem_version
FROM contest_problems cp JOIN contests c ON c.id=cp.contest_id JOIN problems p ON p.id=cp.problem_id
JOIN problem_versions v ON v.problem_id=cp.problem_id AND v.version_no=cp.problem_version
WHERE cp.contest_id=$1::uuid AND cp.domain_id=$2::uuid AND cp.problem_id=$3::uuid
`

type GetContestProblemByIDParams struct {
	ContestID string
	DomainID  string
	ProblemID string
}

type GetContestProblemByIDRow struct {
	ContestID       string
	ContestPublicID string
	ProblemID       string
	ProblemPublicID string
	SortOrder       int
	Label           string
	Color           string
	Points          int
	Title           string
	Difficulty      int
	Visibility      string
	TagsJson        json.RawMessage
	StatementMd     string
	Source          string
	TimeLimitMs     int
	MemoryLimitKb   int
	JudgeType       string
	ProblemVersion  int
}

func (q *Queries) GetContestProblemByID(ctx context.Context, arg GetContestProblemByIDParams) (GetContestProblemByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getContestProblemByID, arg.ContestID, arg.DomainID, arg.ProblemID)
	var i GetContestProblemByIDRow
	err := row.Scan(
		&i.ContestID,
		&i.ContestPublicID,
		&i.ProblemID,
		&i.ProblemPublicID,
		&i.SortOrder,
		&i.Label,
		&i.Color,
		&i.Points,
		&i.Title,
		&i.Difficulty,
		&i.Visibility,
		&i.TagsJson,
		&i.StatementMd,
		&i.Source,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.JudgeType,
		&i.ProblemVersion,
	)
	return i, err
}

const getContestProblemByLabel = `-- name: GetContestProblemByLabel :one
SELECT cp.contest_id,c.public_id AS contest_public_id,cp.problem_id,p.public_id AS problem_public_id,cp.sort_order,cp.label,cp.color,cp.points,
v.title,v.difficulty,p.visibility,v.tags_json,v.statement_md,v.source,v.time_limit_ms,v.memory_limit_kb,v.judge_type,cp.problem_version
FROM contest_problems cp JOIN contests c ON c.id=cp.contest_id JOIN problems p ON p.id=cp.problem_id
JOIN problem_versions v ON v.problem_id=cp.problem_id AND v.version_no=cp.problem_version
WHERE cp.contest_id=$1::uuid AND cp.domain_id=$2::uuid AND cp.label=$3::text
`

type GetContestProblemByLabelParams struct {
	ContestID string
	DomainID  string
	Label     string
}

type GetContestProblemByLabelRow struct {
	ContestID       string
	ContestPublicID string
	ProblemID       string
	ProblemPublicID string
	SortOrder       int
	Label           string
	Color           string
	Points          int
	Title           string
	Difficulty      int
	Visibility      string
	TagsJson        json.RawMessage
	StatementMd     string
	Source          string
	TimeLimitMs     int
	MemoryLimitKb   int
	JudgeType       string
	ProblemVersion  int
}

func (q *Queries) GetContestProblemByLabel(ctx context.Context, arg GetContestProblemByLabelParams) (GetContestProblemByLabelRow, error) {
	row := q.db.QueryRowContext(ctx, getContestProblemByLabel, arg.ContestID, arg.DomainID, arg.Label)
	var i GetContestProblemByLabelRow
	err := row.Scan(
		&i.ContestID,
		&i.ContestPublicID,
		&i.ProblemID,
		&i.ProblemPublicID,
		&i.SortOrder,
		&i.Label,
		&i.Color,
		&i.Points,
		&i.Title,
		&i.Difficulty,
		&i.Visibility,
		&i.TagsJson,
		&i.StatementMd,
		&i.Source,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.JudgeType,
		&i.ProblemVersion,
	)
	return i, err
}

const getContestProblemByNumber = `-- name: GetContestProblemByNumber :one
SELECT cp.contest_id,c.public_id AS contest_public_id,cp.problem_id,p.public_id AS problem_public_id,cp.sort_order,cp.label,cp.color,cp.points,
v.title,v.difficulty,p.visibility,v.tags_json,v.statement_md,v.source,v.time_limit_ms,v.memory_limit_kb,v.judge_type,cp.problem_version
FROM contest_problems cp JOIN contests c ON c.id=cp.contest_id JOIN problems p ON p.id=cp.problem_id
JOIN problem_versions v ON v.problem_id=cp.problem_id AND v.version_no=cp.problem_version
WHERE cp.contest_id=$1::uuid AND cp.domain_id=$2::uuid AND p.public_id=$3::bigint
`

type GetContestProblemByNumberParams struct {
	ContestID string
	DomainID  string
	PublicID  int64
}

type GetContestProblemByNumberRow struct {
	ContestID       string
	ContestPublicID string
	ProblemID       string
	ProblemPublicID string
	SortOrder       int
	Label           string
	Color           string
	Points          int
	Title           string
	Difficulty      int
	Visibility      string
	TagsJson        json.RawMessage
	StatementMd     string
	Source          string
	TimeLimitMs     int
	MemoryLimitKb   int
	JudgeType       string
	ProblemVersion  int
}

func (q *Queries) GetContestProblemByNumber(ctx context.Context, arg GetContestProblemByNumberParams) (GetContestProblemByNumberRow, error) {
	row := q.db.QueryRowContext(ctx, getContestProblemByNumber, arg.ContestID, arg.DomainID, arg.PublicID)
	var i GetContestProblemByNumberRow
	err := row.Scan(
		&i.ContestID,
		&i.ContestPublicID,
		&i.ProblemID,
		&i.ProblemPublicID,
		&i.SortOrder,
		&i.Label,
		&i.Color,
		&i.Points,
		&i.Title,
		&i.Difficulty,
		&i.Visibility,
		&i.TagsJson,
		&i.StatementMd,
		&i.Source,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.JudgeType,
		&i.ProblemVersion,
	)
	return i, err
}

const hasContestProblem = `-- name: HasContestProblem :one
SELECT EXISTS (
		   SELECT 1 FROM contest_problems WHERE contest_id = $1::uuid AND problem_id = $2::uuid AND domain_id = $3::uuid
		)
`

type HasContestProblemParams struct {
	ContestID string
	ProblemID string
	DomainID  string
}

func (q *Queries) HasContestProblem(ctx context.Context, arg HasContestProblemParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasContestProblem, arg.ContestID, arg.ProblemID, arg.DomainID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertContestProblem = `-- name: InsertContestProblem :exec
INSERT INTO contest_problems (contest_id, problem_id, sort_order, label, color, points, domain_id,problem_version)
			 VALUES ($1::uuid, $2::uuid, $3::integer, $4::text, $5::text, $6::integer, $7::uuid,$8::integer)
`

type InsertContestProblemParams struct {
	ContestID      string
	ProblemID      string
	SortOrder      int
	Label          string
	Color          string
	Points         int
	DomainID       string
	ProblemVersion int
}

func (q *Queries) InsertContestProblem(ctx context.Context, arg InsertContestProblemParams) error {
	_, err := q.db.ExecContext(ctx, insertContestProblem,
		arg.ContestID,
		arg.ProblemID,
		arg.SortOrder,
		arg.Label,
		arg.Color,
		arg.Points,
		arg.DomainID,
		arg.ProblemVersion,
	)
	return err
}

const isContestParticipant = `-- name: IsContestParticipant :one
SELECT EXISTS (SELECT 1 FROM contest_participants AS participant
		 JOIN contests AS contest ON contest.id = participant.contest_id
		 WHERE contest_id = $1::uuid AND user_id = $2::uuid AND contest.domain_id = $3::uuid)
`

type IsContestParticipantParams struct {
	ContestID string
	UserID    string
	DomainID  string
}

func (q *Queries) IsContestParticipant(ctx context.Context, arg IsContestParticipantParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isContestParticipant, arg.ContestID, arg.UserID, arg.DomainID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listContestProblemVersions = `-- name: ListContestProblemVersions :many
SELECT problem_id,problem_version FROM contest_problems WHERE contest_id=$1::uuid
`

type ListContestProblemVersionsRow struct {
	ProblemID      string
	ProblemVersion int
}

func (q *Queries) ListContestProblemVersions(ctx context.Context, contestID string) ([]ListContestProblemVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContestProblemVersions, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestProblemVersionsRow{}
	for rows.Next() {
		var i ListContestProblemVersionsRow
		if err := rows.Scan(&i.ProblemID, &i.ProblemVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestProblems = `-- name: ListContestProblems :many
SELECT cp.contest_id,c.public_id AS contest_public_id,cp.problem_id,p.public_id AS problem_public_id,cp.sort_order,cp.label,cp.color,cp.points,v.title,v.difficulty,p.visibility,v.tags_json,cp.problem_version
 FROM contest_problems cp JOIN contests c ON c.id=cp.contest_id JOIN problems p ON p.id=cp.problem_id
 JOIN problem_versions v ON v.problem_id=cp.problem_id AND v.version_no=cp.problem_version
 WHERE cp.contest_id=$1::uuid AND cp.domain_id=$2::uuid ORDER BY cp.sort_order
`

type ListContestProblemsParams struct {
	ContestID string
	DomainID  string
}

type ListContestProblemsRow struct {
	ContestID       string
	ContestPublicID string
	ProblemID       string
	ProblemPublicID string
	SortOrder       int
	Label           string
	Color           string
	Points          int
	Title           string
	Difficulty      int
	Visibility      string
	TagsJson        json.RawMessage
	ProblemVersion  int
}

func (q *Queries) ListContestProblems(ctx context.Context, arg ListContestProblemsParams) ([]ListContestProblemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContestProblems, arg.ContestID, arg.DomainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestProblemsRow{}
	for rows.Next() {
		var i ListContestProblemsRow
		if err := rows.Scan(
			&i.ContestID,
			&i.ContestPublicID,
			&i.ProblemID,
			&i.ProblemPublicID,
			&i.SortOrder,
			&i.Label,
			&i.Color,
			&i.Points,
			&i.Title,
			&i.Difficulty,
			&i.Visibility,
			&i.TagsJson,
			&i.ProblemVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerContestParticipant = `-- name: RegisterContestParticipant :exec
INSERT INTO contest_participants (contest_id, user_id)
		 SELECT id, $1::uuid FROM contests WHERE contests.id = $2::uuid AND contests.domain_id = $3::uuid
		 ON CONFLICT (contest_id, user_id) DO NOTHING
`

type RegisterContestParticipantParams struct {
	UserID    string
	ContestID string
	DomainID  string
}

func (q *Queries) RegisterContestParticipant(ctx context.Context, arg RegisterContestParticipantParams) error {
	_, err := q.db.ExecContext(ctx, registerContestParticipant, arg.UserID, arg.ContestID, arg.DomainID)
	return err
}
