// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scoring.sql

package dbgen

import (
	"context"
	"time"
)

const deleteContestCell = `-- name: DeleteContestCell :exec
DELETE FROM contest_submission_cells
			 WHERE contest_submission_cells.contest_id = $1::uuid AND user_id = $2::uuid AND problem_id = $3::uuid
`

type DeleteContestCellParams struct {
	ContestID string
	UserID    string
	ProblemID string
}

func (q *Queries) DeleteContestCell(ctx context.Context, arg DeleteContestCellParams) error {
	_, err := q.db.ExecContext(ctx, deleteContestCell, arg.ContestID, arg.UserID, arg.ProblemID)
	return err
}

const getContestScoringRules = `-- name: GetContestScoringRules :one
SELECT contest.rule, contest.begin_at, contest.end_at, contest.freeze_at,
		        contest.penalty_minutes, contest.penalize_compile_error,
		        COALESCE(problem.points, 100)::integer AS max_points
		 FROM contests AS contest
		 LEFT JOIN contest_problems AS problem
		   ON problem.contest_id = contest.id AND problem.problem_id = $1::uuid
		 WHERE contest.id = $2::uuid
`

type GetContestScoringRulesParams struct {
	ProblemID string
	ContestID string
}

type GetContestScoringRulesRow struct {
	Rule                 string
	BeginAt              time.Time
	EndAt                time.Time
	FreezeAt             *time.Time
	PenaltyMinutes       int
	PenalizeCompileError bool
	MaxPoints            int
}

func (q *Queries) GetContestScoringRules(ctx context.Context, arg GetContestScoringRulesParams) (GetContestScoringRulesRow, error) {
	row := q.db.QueryRowContext(ctx, getContestScoringRules, arg.ProblemID, arg.ContestID)
	var i GetContestScoringRulesRow
	err := row.Scan(
		&i.Rule,
		&i.BeginAt,
		&i.EndAt,
		&i.FreezeAt,
		&i.PenaltyMinutes,
		&i.PenalizeCompileError,
		&i.MaxPoints,
	)
	return i, err
}

const listContestScoringTargets = `-- name: ListContestScoringTargets :many
SELECT DISTINCT user_id, problem_id FROM submissions WHERE contest_id = $1::uuid
`

type ListContestScoringTargetsRow struct {
	UserID    string
	ProblemID string
}

func (q *Queries) ListContestScoringTargets(ctx context.Context, contestID string) ([]ListContestScoringTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContestScoringTargets, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestScoringTargetsRow{}
	for rows.Next() {
		var i ListContestScoringTargetsRow
		if err := rows.Scan(&i.UserID, &i.ProblemID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoredSubmissions = `-- name: ListScoredSubmissions :many
SELECT submitted_at, status, score
		 FROM submissions
		 WHERE contest_id = $1::uuid AND user_id = $2::uuid AND problem_id = $3::uuid
		 ORDER BY submitted_at
`

type ListScoredSubmissionsParams struct {
	ContestID string
	UserID    string
	ProblemID string
}

type ListScoredSubmissionsRow struct {
	SubmittedAt time.Time
	Status      string
	Score       int
}

func (q *Queries) ListScoredSubmissions(ctx context.Context, arg ListScoredSubmissionsParams) ([]ListScoredSubmissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listScoredSubmissions, arg.ContestID, arg.UserID, arg.ProblemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScoredSubmissionsRow{}
	for rows.Next() {
		var i ListScoredSubmissionsRow
		if err := rows.Scan(&i.SubmittedAt, &i.Status, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockContestCell = `-- name: LockContestCell :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockContestCell(ctx context.Context, lockKey string) error {
	_, err := q.db.ExecContext(ctx, lockContestCell, lockKey)
	return err
}

const upsertContestCell = `-- name: UpsertContestCell :exec
INSERT INTO contest_submission_cells
		   (contest_id, user_id, problem_id, attempts, penalty_sec, score, solved_at,
		    public_attempts, public_penalty_sec, public_score, public_solved_at,
		    pending_count, last_submit_at, domain_id)
		 VALUES ($1::uuid, $2::uuid, $3::uuid, $4::integer, $5::integer, $6::integer, $7::timestamptz, $8::integer, $9::integer, $10::integer, $11::timestamptz, $12::integer, $13::timestamptz,
		         (SELECT domain_id FROM contests WHERE contests.id = $1::uuid))
		 ON CONFLICT (contest_id, user_id, problem_id) DO UPDATE SET
		   attempts = EXCLUDED.attempts,
		   penalty_sec = EXCLUDED.penalty_sec,
		   score = EXCLUDED.score,
		   solved_at = EXCLUDED.solved_at,
		   public_attempts = EXCLUDED.public_attempts,
		   public_penalty_sec = EXCLUDED.public_penalty_sec,
		   public_score = EXCLUDED.public_score,
		   public_solved_at = EXCLUDED.public_solved_at,
		   pending_count = EXCLUDED.pending_count,
		   last_submit_at = EXCLUDED.last_submit_at
`

type UpsertContestCellParams struct {
	ContestID        string
	UserID           string
	ProblemID        string
	Attempts         int
	PenaltySec       int
	Score            int
	SolvedAt         *time.Time
	PublicAttempts   int
	PublicPenaltySec int
	PublicScore      int
	PublicSolvedAt   *time.Time
	PendingCount     int
	LastSubmitAt     *time.Time
}

func (q *Queries) UpsertContestCell(ctx context.Context, arg UpsertContestCellParams) error {
	_, err := q.db.ExecContext(ctx, upsertContestCell,
		arg.ContestID,
		arg.UserID,
		arg.ProblemID,
		arg.Attempts,
		arg.PenaltySec,
		arg.Score,
		arg.SolvedAt,
		arg.PublicAttempts,
		arg.PublicPenaltySec,
		arg.PublicScore,
		arg.PublicSolvedAt,
		arg.PendingCount,
		arg.LastSubmitAt,
	)
	return err
}
