// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: numbers.sql

package dbgen

import (
	"context"
)

const resolveAnnouncementNumber = `-- name: ResolveAnnouncementNumber :one
SELECT id FROM announcements
WHERE domain_id = $1::uuid AND public_id = $2::bigint
`

type ResolveAnnouncementNumberParams struct {
	DomainID string
	PublicID int64
}

func (q *Queries) ResolveAnnouncementNumber(ctx context.Context, arg ResolveAnnouncementNumberParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveAnnouncementNumber, arg.DomainID, arg.PublicID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const resolveContestNumber = `-- name: ResolveContestNumber :one
SELECT id FROM contests
WHERE domain_id = $1::uuid AND public_id = $2::bigint
`

type ResolveContestNumberParams struct {
	DomainID string
	PublicID int64
}

func (q *Queries) ResolveContestNumber(ctx context.Context, arg ResolveContestNumberParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveContestNumber, arg.DomainID, arg.PublicID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const resolveEditorialNumber = `-- name: ResolveEditorialNumber :one
SELECT id FROM editorials
WHERE domain_id = $1::uuid AND public_id = $2::bigint
`

type ResolveEditorialNumberParams struct {
	DomainID string
	PublicID int64
}

func (q *Queries) ResolveEditorialNumber(ctx context.Context, arg ResolveEditorialNumberParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveEditorialNumber, arg.DomainID, arg.PublicID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const resolveProblemNumber = `-- name: ResolveProblemNumber :one
SELECT id FROM problems
WHERE domain_id = $1::uuid AND public_id = $2::bigint
`

type ResolveProblemNumberParams struct {
	DomainID string
	PublicID int64
}

func (q *Queries) ResolveProblemNumber(ctx context.Context, arg ResolveProblemNumberParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveProblemNumber, arg.DomainID, arg.PublicID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const resolveProblemSetNumber = `-- name: ResolveProblemSetNumber :one
SELECT id FROM problem_sets
WHERE domain_id = $1::uuid AND public_id = $2::bigint
`

type ResolveProblemSetNumberParams struct {
	DomainID string
	PublicID int64
}

func (q *Queries) ResolveProblemSetNumber(ctx context.Context, arg ResolveProblemSetNumberParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveProblemSetNumber, arg.DomainID, arg.PublicID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const resolveSubmissionNumber = `-- name: ResolveSubmissionNumber :one
SELECT id FROM submissions
WHERE domain_id = $1::uuid AND public_id = $2::bigint
`

type ResolveSubmissionNumberParams struct {
	DomainID string
	PublicID int64
}

func (q *Queries) ResolveSubmissionNumber(ctx context.Context, arg ResolveSubmissionNumberParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveSubmissionNumber, arg.DomainID, arg.PublicID)
	var id string
	err := row.Scan(&id)
	return id, err
}
