// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: numbers.sql

package dbgen

import (
	"context"
)

const resolveProblemSetNumber = `-- name: ResolveProblemSetNumber :one
SELECT id FROM problem_sets WHERE domain_id=$1::uuid AND public_id=$2::bigint
`

type ResolveProblemSetNumberParams struct {
	DomainID string
	PublicID int64
}

func (q *Queries) ResolveProblemSetNumber(ctx context.Context, arg ResolveProblemSetNumberParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveProblemSetNumber, arg.DomainID, arg.PublicID)
	var id string
	err := row.Scan(&id)
	return id, err
}
