// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const countVisibleSets = `-- name: CountVisibleSets :one
SELECT count(*) FROM problem_sets s
LEFT JOIN LATERAL (SELECT COALESCE(max(CASE WHEN a.role='editor' THEN 2 ELSE 1 END),0)::integer AS grant_rank
 FROM problem_set_access a WHERE a.set_id=s.id AND a.domain_id=s.domain_id
 AND (a.user_id=NULLIF($1::text,'')::uuid OR a.group_id IN (SELECT group_id FROM domain_group_members WHERE domain_id=s.domain_id AND user_id=NULLIF($1::text,'')::uuid))) grants ON true
WHERE s.domain_id=$2::uuid AND (s.visibility='public' OR $3::boolean OR ($4::boolean AND (s.owner_id=NULLIF($1::text,'')::uuid OR grants.grant_rank>0)))
AND ($5::text='' OR s.author_id=NULLIF($5::text,'')::uuid)
AND ($6::text='' OR s.title ILIKE '%'||$6::text||'%' OR s.description ILIKE '%'||$6::text||'%')
`

type CountVisibleSetsParams struct {
	ViewerID     string
	DomainID     string
	IsManager    bool
	ActiveMember bool
	AuthorID     string
	Keyword      string
}

func (q *Queries) CountVisibleSets(ctx context.Context, arg CountVisibleSetsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVisibleSets,
		arg.ViewerID,
		arg.DomainID,
		arg.IsManager,
		arg.ActiveMember,
		arg.AuthorID,
		arg.Keyword,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSetGrantRank = `-- name: GetSetGrantRank :one
SELECT grants.grant_rank FROM problem_sets s
LEFT JOIN LATERAL (SELECT COALESCE(max(CASE WHEN a.role='editor' THEN 2 ELSE 1 END),0)::integer AS grant_rank
 FROM problem_set_access a WHERE a.set_id=s.id AND a.domain_id=s.domain_id
 AND (a.user_id=NULLIF($1::text,'')::uuid OR a.group_id IN (SELECT group_id FROM domain_group_members WHERE domain_id=s.domain_id AND user_id=NULLIF($1::text,'')::uuid))) grants ON true
WHERE s.id=$2::uuid AND s.domain_id=$3::uuid
`

type GetSetGrantRankParams struct {
	ViewerID string
	SetID    string
	DomainID string
}

func (q *Queries) GetSetGrantRank(ctx context.Context, arg GetSetGrantRankParams) (int, error) {
	row := q.db.QueryRowContext(ctx, getSetGrantRank, arg.ViewerID, arg.SetID, arg.DomainID)
	var grant_rank int
	err := row.Scan(&grant_rank)
	return grant_rank, err
}

const getVisibleSet = `-- name: GetVisibleSet :one
SELECT s.id,s.public_id,s.title,s.description,s.author_id,COALESCE(author.username,'') AS author_name,
 s.visibility,s.created_at,s.updated_at,s.domain_id,s.owner_id,owner.username AS owner_name,
 grants.grant_rank,COALESCE(item_stats.all_items_visible,true)::boolean AS all_items_visible,
 COALESCE(item_stats.problem_count,0)::integer AS problem_count,COALESCE(item_stats.solved_count,0)::integer AS solved_count
FROM problem_sets s LEFT JOIN users author ON author.id=s.author_id JOIN users owner ON owner.id=s.owner_id
LEFT JOIN LATERAL (SELECT COALESCE(max(CASE WHEN a.role='editor' THEN 2 ELSE 1 END),0)::integer AS grant_rank
 FROM problem_set_access a WHERE a.set_id=s.id AND a.domain_id=s.domain_id
 AND (a.user_id=NULLIF($1::text,'')::uuid OR a.group_id IN (SELECT group_id FROM domain_group_members WHERE domain_id=s.domain_id AND user_id=NULLIF($1::text,'')::uuid))) grants ON true
LEFT JOIN LATERAL (
 SELECT count(*) FILTER(WHERE visible)::integer AS problem_count,
 count(*) FILTER(WHERE visible AND solved)::integer AS solved_count,
 COALESCE(bool_and(visible),true)::boolean AS all_items_visible
 FROM (SELECT ((p.visibility='public' AND p.published_version IS NOT NULL) OR $2::boolean OR
 ($3::boolean AND (p.owner_id=NULLIF($1::text,'')::uuid OR EXISTS(
 SELECT 1 FROM problem_access pa WHERE pa.problem_id=p.id AND pa.domain_id=p.domain_id
 AND (pa.user_id=NULLIF($1::text,'')::uuid OR pa.group_id IN (SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($1::text,'')::uuid)))))) AS visible,EXISTS(SELECT 1 FROM submissions sub WHERE sub.problem_id=p.id AND sub.user_id=NULLIF($1::text,'')::uuid AND sub.contest_id IS NULL AND sub.status='Accepted') AS solved
 FROM problem_set_problems item JOIN problems p ON p.id=item.problem_id
 WHERE item.set_id=s.id AND item.domain_id=s.domain_id) item_access) item_stats ON true
WHERE s.domain_id=$4::uuid AND s.id=$5::uuid AND (s.visibility='public' OR $2::boolean OR ($3::boolean AND (s.owner_id=NULLIF($1::text,'')::uuid OR grants.grant_rank>0)))
`

type GetVisibleSetParams struct {
	ViewerID     string
	IsManager    bool
	ActiveMember bool
	DomainID     string
	SetID        string
}

type GetVisibleSetRow struct {
	ID              string
	PublicID        string
	Title           string
	Description     string
	AuthorID        *string
	AuthorName      string
	Visibility      string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DomainID        string
	OwnerID         string
	OwnerName       string
	GrantRank       int
	AllItemsVisible bool
	ProblemCount    int
	SolvedCount     int
}

func (q *Queries) GetVisibleSet(ctx context.Context, arg GetVisibleSetParams) (GetVisibleSetRow, error) {
	row := q.db.QueryRowContext(ctx, getVisibleSet,
		arg.ViewerID,
		arg.IsManager,
		arg.ActiveMember,
		arg.DomainID,
		arg.SetID,
	)
	var i GetVisibleSetRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.AuthorName,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainID,
		&i.OwnerID,
		&i.OwnerName,
		&i.GrantRank,
		&i.AllItemsVisible,
		&i.ProblemCount,
		&i.SolvedCount,
	)
	return i, err
}

const listVisibleItems = `-- name: ListVisibleItems :many
SELECT item.problem_id,p.public_id,p.owner_id,item.sort_order,item.note,p.title,p.difficulty,p.visibility,p.submission_count,p.accepted_count,
 COALESCE((SELECT jsonb_agg(t.name ORDER BY t.name) FROM problem_tags pt JOIN tags t ON t.id=pt.tag_id WHERE pt.problem_id=p.id),'[]'::jsonb)::jsonb AS tags,
 CASE WHEN $1::text='' THEN 'none' WHEN EXISTS(SELECT 1 FROM submissions sub WHERE sub.problem_id=p.id AND sub.user_id=NULLIF($1::text,'')::uuid AND sub.contest_id IS NULL AND sub.status='Accepted') THEN 'solved'
 WHEN EXISTS(SELECT 1 FROM submissions sub WHERE sub.problem_id=p.id AND sub.user_id=NULLIF($1::text,'')::uuid AND sub.contest_id IS NULL) THEN 'attempted' ELSE 'none' END::text AS user_status
FROM problem_set_problems item JOIN problems p ON p.id=item.problem_id
WHERE item.domain_id=$2::uuid AND item.set_id=$3::uuid AND ((p.visibility='public' AND p.published_version IS NOT NULL) OR $4::boolean OR
 ($5::boolean AND (p.owner_id=NULLIF($1::text,'')::uuid OR EXISTS(
 SELECT 1 FROM problem_access pa WHERE pa.problem_id=p.id AND pa.domain_id=p.domain_id
 AND (pa.user_id=NULLIF($1::text,'')::uuid OR pa.group_id IN (SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($1::text,'')::uuid))))))
ORDER BY item.sort_order
`

type ListVisibleItemsParams struct {
	ViewerID     string
	DomainID     string
	SetID        string
	IsManager    bool
	ActiveMember bool
}

type ListVisibleItemsRow struct {
	ProblemID       string
	PublicID        string
	OwnerID         string
	SortOrder       int
	Note            string
	Title           string
	Difficulty      int
	Visibility      string
	SubmissionCount int
	AcceptedCount   int
	Tags            json.RawMessage
	UserStatus      string
}

func (q *Queries) ListVisibleItems(ctx context.Context, arg ListVisibleItemsParams) ([]ListVisibleItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleItems,
		arg.ViewerID,
		arg.DomainID,
		arg.SetID,
		arg.IsManager,
		arg.ActiveMember,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleItemsRow{}
	for rows.Next() {
		var i ListVisibleItemsRow
		if err := rows.Scan(
			&i.ProblemID,
			&i.PublicID,
			&i.OwnerID,
			&i.SortOrder,
			&i.Note,
			&i.Title,
			&i.Difficulty,
			&i.Visibility,
			&i.SubmissionCount,
			&i.AcceptedCount,
			&i.Tags,
			&i.UserStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleSets = `-- name: ListVisibleSets :many
SELECT s.id,s.public_id,s.title,s.description,s.author_id,COALESCE(author.username,'') AS author_name,
 s.visibility,s.created_at,s.updated_at,s.domain_id,s.owner_id,owner.username AS owner_name,
 grants.grant_rank,COALESCE(item_stats.all_items_visible,true)::boolean AS all_items_visible,
 COALESCE(item_stats.problem_count,0)::integer AS problem_count,COALESCE(item_stats.solved_count,0)::integer AS solved_count
FROM problem_sets s LEFT JOIN users author ON author.id=s.author_id JOIN users owner ON owner.id=s.owner_id
LEFT JOIN LATERAL (SELECT COALESCE(max(CASE WHEN a.role='editor' THEN 2 ELSE 1 END),0)::integer AS grant_rank
 FROM problem_set_access a WHERE a.set_id=s.id AND a.domain_id=s.domain_id
 AND (a.user_id=NULLIF($1::text,'')::uuid OR a.group_id IN (SELECT group_id FROM domain_group_members WHERE domain_id=s.domain_id AND user_id=NULLIF($1::text,'')::uuid))) grants ON true
LEFT JOIN LATERAL (
 SELECT count(*) FILTER(WHERE visible)::integer AS problem_count,
 count(*) FILTER(WHERE visible AND solved)::integer AS solved_count,
 COALESCE(bool_and(visible),true)::boolean AS all_items_visible
 FROM (SELECT ((p.visibility='public' AND p.published_version IS NOT NULL) OR $2::boolean OR
 ($3::boolean AND (p.owner_id=NULLIF($1::text,'')::uuid OR EXISTS(
 SELECT 1 FROM problem_access pa WHERE pa.problem_id=p.id AND pa.domain_id=p.domain_id
 AND (pa.user_id=NULLIF($1::text,'')::uuid OR pa.group_id IN (SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($1::text,'')::uuid)))))) AS visible,EXISTS(SELECT 1 FROM submissions sub WHERE sub.problem_id=p.id AND sub.user_id=NULLIF($1::text,'')::uuid AND sub.contest_id IS NULL AND sub.status='Accepted') AS solved
 FROM problem_set_problems item JOIN problems p ON p.id=item.problem_id
 WHERE item.set_id=s.id AND item.domain_id=s.domain_id) item_access) item_stats ON true
WHERE s.domain_id=$4::uuid AND (s.visibility='public' OR $2::boolean OR ($3::boolean AND (s.owner_id=NULLIF($1::text,'')::uuid OR grants.grant_rank>0)))
AND ($5::text='' OR s.author_id=NULLIF($5::text,'')::uuid)
AND ($6::text='' OR s.title ILIKE '%'||$6::text||'%' OR s.description ILIKE '%'||$6::text||'%')
ORDER BY s.created_at DESC,s.id DESC LIMIT $8::integer OFFSET $7::integer
`

type ListVisibleSetsParams struct {
	ViewerID     string
	IsManager    bool
	ActiveMember bool
	DomainID     string
	AuthorID     string
	Keyword      string
	PageOffset   int
	PageLimit    int
}

type ListVisibleSetsRow struct {
	ID              string
	PublicID        string
	Title           string
	Description     string
	AuthorID        *string
	AuthorName      string
	Visibility      string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DomainID        string
	OwnerID         string
	OwnerName       string
	GrantRank       int
	AllItemsVisible bool
	ProblemCount    int
	SolvedCount     int
}

func (q *Queries) ListVisibleSets(ctx context.Context, arg ListVisibleSetsParams) ([]ListVisibleSetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleSets,
		arg.ViewerID,
		arg.IsManager,
		arg.ActiveMember,
		arg.DomainID,
		arg.AuthorID,
		arg.Keyword,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleSetsRow{}
	for rows.Next() {
		var i ListVisibleSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.Description,
			&i.AuthorID,
			&i.AuthorName,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DomainID,
			&i.OwnerID,
			&i.OwnerName,
			&i.GrantRank,
			&i.AllItemsVisible,
			&i.ProblemCount,
			&i.SolvedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
