// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: write.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createProblemSet = `-- name: CreateProblemSet :one
INSERT INTO problem_sets(title,description,visibility,author_id,owner_id,domain_id)
	 VALUES($1::text,$2::text,$3::text,$4::uuid,$4::uuid,$5::uuid) RETURNING id
`

type CreateProblemSetParams struct {
	Title       string
	Description string
	Visibility  string
	AuthorID    string
	DomainID    string
}

func (q *Queries) CreateProblemSet(ctx context.Context, arg CreateProblemSetParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createProblemSet,
		arg.Title,
		arg.Description,
		arg.Visibility,
		arg.AuthorID,
		arg.DomainID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteProblemSet = `-- name: DeleteProblemSet :exec
DELETE FROM problem_sets WHERE id=$1::uuid
`

func (q *Queries) DeleteProblemSet(ctx context.Context, setID string) error {
	_, err := q.db.ExecContext(ctx, deleteProblemSet, setID)
	return err
}

const deleteProblemSetGrant = `-- name: DeleteProblemSetGrant :execrows
DELETE FROM problem_set_access WHERE set_id=$1::uuid AND id=$2::bigint AND domain_id=$3::uuid
`

type DeleteProblemSetGrantParams struct {
	SetID    string
	GrantID  int64
	DomainID string
}

func (q *Queries) DeleteProblemSetGrant(ctx context.Context, arg DeleteProblemSetGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProblemSetGrant, arg.SetID, arg.GrantID, arg.DomainID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProblemSetItems = `-- name: DeleteProblemSetItems :exec
DELETE FROM problem_set_problems WHERE set_id=$1::uuid
`

func (q *Queries) DeleteProblemSetItems(ctx context.Context, setID string) error {
	_, err := q.db.ExecContext(ctx, deleteProblemSetItems, setID)
	return err
}

const deleteProblemSetOwnerGrants = `-- name: DeleteProblemSetOwnerGrants :exec
DELETE FROM problem_set_access WHERE set_id=$1::uuid AND user_id=$2::uuid
`

type DeleteProblemSetOwnerGrantsParams struct {
	SetID  string
	UserID string
}

func (q *Queries) DeleteProblemSetOwnerGrants(ctx context.Context, arg DeleteProblemSetOwnerGrantsParams) error {
	_, err := q.db.ExecContext(ctx, deleteProblemSetOwnerGrants, arg.SetID, arg.UserID)
	return err
}

const findProblemSetCollaborator = `-- name: FindProblemSetCollaborator :one
SELECT m.user_id FROM domain_members m JOIN users u ON u.id=m.user_id
	 WHERE m.domain_id=$1::uuid AND u.username=$2::text AND m.status='active' AND u.disabled_at IS NULL FOR SHARE OF u
`

type FindProblemSetCollaboratorParams struct {
	DomainID string
	Username string
}

func (q *Queries) FindProblemSetCollaborator(ctx context.Context, arg FindProblemSetCollaboratorParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findProblemSetCollaborator, arg.DomainID, arg.Username)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const grantSetGroup = `-- name: GrantSetGroup :exec
INSERT INTO problem_set_access(domain_id,set_id,group_id,role,granted_by)
VALUES($1::uuid,$2::uuid,$3::uuid,$4::text,$5::uuid)
ON CONFLICT(set_id,group_id) WHERE group_id IS NOT NULL DO UPDATE SET role=EXCLUDED.role,granted_by=EXCLUDED.granted_by
`

type GrantSetGroupParams struct {
	DomainID  string
	SetID     string
	SubjectID string
	Role      string
	ActorID   string
}

func (q *Queries) GrantSetGroup(ctx context.Context, arg GrantSetGroupParams) error {
	_, err := q.db.ExecContext(ctx, grantSetGroup,
		arg.DomainID,
		arg.SetID,
		arg.SubjectID,
		arg.Role,
		arg.ActorID,
	)
	return err
}

const grantSetUser = `-- name: GrantSetUser :exec
INSERT INTO problem_set_access(domain_id,set_id,user_id,role,granted_by)
VALUES($1::uuid,$2::uuid,$3::uuid,$4::text,$5::uuid)
ON CONFLICT(set_id,user_id) WHERE user_id IS NOT NULL DO UPDATE SET role=EXCLUDED.role,granted_by=EXCLUDED.granted_by
`

type GrantSetUserParams struct {
	DomainID  string
	SetID     string
	SubjectID string
	Role      string
	ActorID   string
}

func (q *Queries) GrantSetUser(ctx context.Context, arg GrantSetUserParams) error {
	_, err := q.db.ExecContext(ctx, grantSetUser,
		arg.DomainID,
		arg.SetID,
		arg.SubjectID,
		arg.Role,
		arg.ActorID,
	)
	return err
}

const insertProblemSetItem = `-- name: InsertProblemSetItem :exec
INSERT INTO problem_set_problems(domain_id,set_id,problem_id,sort_order,note) VALUES($1::uuid,$2::uuid,$3::uuid,$4::integer,$5::text)
`

type InsertProblemSetItemParams struct {
	DomainID  string
	SetID     string
	ProblemID string
	SortOrder int
	Note      string
}

func (q *Queries) InsertProblemSetItem(ctx context.Context, arg InsertProblemSetItemParams) error {
	_, err := q.db.ExecContext(ctx, insertProblemSetItem,
		arg.DomainID,
		arg.SetID,
		arg.ProblemID,
		arg.SortOrder,
		arg.Note,
	)
	return err
}

const listProblemSetGrants = `-- name: ListProblemSetGrants :many
SELECT a.id,a.user_id,u.username,a.group_id,g.name AS group_name,a.role
	 FROM problem_set_access a LEFT JOIN users u ON u.id=a.user_id LEFT JOIN domain_groups g ON g.id=a.group_id
	 WHERE a.domain_id=$1::uuid AND a.set_id=$2::uuid ORDER BY a.id
`

type ListProblemSetGrantsParams struct {
	DomainID string
	SetID    string
}

type ListProblemSetGrantsRow struct {
	ID        int64
	UserID    *string
	Username  sql.NullString
	GroupID   *string
	GroupName sql.NullString
	Role      string
}

func (q *Queries) ListProblemSetGrants(ctx context.Context, arg ListProblemSetGrantsParams) ([]ListProblemSetGrantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProblemSetGrants, arg.DomainID, arg.SetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProblemSetGrantsRow{}
	for rows.Next() {
		var i ListProblemSetGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.GroupID,
			&i.GroupName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemSetProblemIDs = `-- name: ListProblemSetProblemIDs :many
SELECT problem_id FROM problem_set_problems WHERE set_id=$1::uuid
`

func (q *Queries) ListProblemSetProblemIDs(ctx context.Context, setID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProblemSetProblemIDs, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var problem_id string
		if err := rows.Scan(&problem_id); err != nil {
			return nil, err
		}
		items = append(items, problem_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProblemSetAccess = `-- name: LockProblemSetAccess :one
SELECT id,owner_id,visibility FROM problem_sets WHERE id=$1::uuid AND domain_id=$2::uuid FOR UPDATE
`

type LockProblemSetAccessParams struct {
	SetID    string
	DomainID string
}

type LockProblemSetAccessRow struct {
	ID         string
	OwnerID    string
	Visibility string
}

func (q *Queries) LockProblemSetAccess(ctx context.Context, arg LockProblemSetAccessParams) (LockProblemSetAccessRow, error) {
	row := q.db.QueryRowContext(ctx, lockProblemSetAccess, arg.SetID, arg.DomainID)
	var i LockProblemSetAccessRow
	err := row.Scan(&i.ID, &i.OwnerID, &i.Visibility)
	return i, err
}

const recordProblemSetAudit = `-- name: RecordProblemSetAudit :exec
INSERT INTO domain_audit_events(domain_id,actor_id,action,target) VALUES($1::uuid,$2::uuid,$3::text,$4::text)
`

type RecordProblemSetAuditParams struct {
	DomainID string
	ActorID  string
	Action   string
	Target   string
}

func (q *Queries) RecordProblemSetAudit(ctx context.Context, arg RecordProblemSetAuditParams) error {
	_, err := q.db.ExecContext(ctx, recordProblemSetAudit,
		arg.DomainID,
		arg.ActorID,
		arg.Action,
		arg.Target,
	)
	return err
}

const resolveProblemSetGrantGroup = `-- name: ResolveProblemSetGrantGroup :one
SELECT id FROM domain_groups WHERE domain_id=$1::uuid AND (id::text=$2::text OR public_id::text=$2::text)
`

type ResolveProblemSetGrantGroupParams struct {
	DomainID string
	GroupRef string
}

func (q *Queries) ResolveProblemSetGrantGroup(ctx context.Context, arg ResolveProblemSetGrantGroupParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveProblemSetGrantGroup, arg.DomainID, arg.GroupRef)
	var id string
	err := row.Scan(&id)
	return id, err
}

const touchProblemSet = `-- name: TouchProblemSet :exec
UPDATE problem_sets SET updated_at=now() WHERE id=$1::uuid
`

func (q *Queries) TouchProblemSet(ctx context.Context, setID string) error {
	_, err := q.db.ExecContext(ctx, touchProblemSet, setID)
	return err
}

const transferProblemSetOwner = `-- name: TransferProblemSetOwner :exec
UPDATE problem_sets SET owner_id=$1::uuid,updated_at=now() WHERE id=$2::uuid
`

type TransferProblemSetOwnerParams struct {
	OwnerID string
	SetID   string
}

func (q *Queries) TransferProblemSetOwner(ctx context.Context, arg TransferProblemSetOwnerParams) error {
	_, err := q.db.ExecContext(ctx, transferProblemSetOwner, arg.OwnerID, arg.SetID)
	return err
}

const updateProblemSet = `-- name: UpdateProblemSet :exec
UPDATE problem_sets SET title=$1::text,description=$2::text,visibility=$3::text,updated_at=now() WHERE id=$4::uuid
`

type UpdateProblemSetParams struct {
	Title       string
	Description string
	Visibility  string
	SetID       string
}

func (q *Queries) UpdateProblemSet(ctx context.Context, arg UpdateProblemSetParams) error {
	_, err := q.db.ExecContext(ctx, updateProblemSet,
		arg.Title,
		arg.Description,
		arg.Visibility,
		arg.SetID,
	)
	return err
}
