// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: numbers.sql

package dbgen

import (
	"context"
)

const resolveEditorialNumber = `-- name: ResolveEditorialNumber :one
SELECT id FROM editorials WHERE domain_id=$1::uuid AND public_id=$2::bigint
`

type ResolveEditorialNumberParams struct {
	DomainID string
	PublicID int64
}

func (q *Queries) ResolveEditorialNumber(ctx context.Context, arg ResolveEditorialNumberParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveEditorialNumber, arg.DomainID, arg.PublicID)
	var id string
	err := row.Scan(&id)
	return id, err
}
