// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: build.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const claimBuild = `-- name: ClaimBuild :one
WITH candidate AS (
		   SELECT id FROM problem_build_jobs
		   WHERE ((state = 'queued' AND available_at <= now())
		      OR (state = 'running' AND lease_expires_at < clock_timestamp() AND problem_build_jobs.attempt < $1))
		      AND source_tree_hash IS NOT NULL AND $2::boolean
		   ORDER BY priority DESC, available_at, created_at
		   FOR UPDATE SKIP LOCKED
		   LIMIT 1
		 ), claimed AS (
		   UPDATE problem_build_jobs AS job
		   SET state = 'running', stage = 'compile', attempt = job.attempt + 1,
		       worker_id = $3::text, lease_token = gen_random_uuid(),
		       lease_expires_at = clock_timestamp() + ($4::bigint * interval '1 millisecond'),
		       started_at = COALESCE(job.started_at, now()), error_message = '',
		       package_path='',package_sha256='',package_cases=0,package_manifest='{}',toolchain_key='',
		       tests_json='[]',solutions_json='[]',validation_json='[]',progress_done=0,progress_total=0
		   FROM candidate
		   WHERE job.id = candidate.id
		   RETURNING job.id, job.problem_id, job.input_json, job.source_tree_hash, job.source_revision, job.data_hash, job.check_policy, job.toolchain_key, job.state, job.stage, job.priority, job.attempt, job.available_at, job.worker_id, job.lease_token, job.lease_expires_at, job.progress_done, job.progress_total, job.log, job.error_message, job.tests_json, job.solutions_json, job.validation_json, job.package_path, job.package_sha256, job.package_cases, job.package_manifest, job.created_by, job.created_at, job.started_at, job.finished_at
		 )
		 SELECT id, problem_id, (SELECT pnum.public_id::text FROM problems pnum WHERE pnum.id=problem_build_jobs.problem_id)::text AS problem_number, state, stage, attempt,
	COALESCE(worker_id, '')::text AS worker_id, COALESCE(lease_token::text, '')::text AS lease_token,
	COALESCE(lease_expires_at, TIMESTAMPTZ 'epoch')::timestamptz AS lease_expires_at,
	progress_done, progress_total, log, error_message, tests_json, solutions_json,
	package_path, package_sha256, package_cases, created_by, created_at, started_at, finished_at FROM claimed AS problem_build_jobs
`

type ClaimBuildParams struct {
	MaxAttempts   int
	AcceptsChecks bool
	WorkerID      string
	LeaseMs       int64
}

type ClaimBuildRow struct {
	ID             string
	ProblemID      string
	ProblemNumber  string
	State          string
	Stage          string
	Attempt        int
	WorkerID       string
	LeaseToken     string
	LeaseExpiresAt time.Time
	ProgressDone   int
	ProgressTotal  int
	Log            string
	ErrorMessage   string
	TestsJson      json.RawMessage
	SolutionsJson  json.RawMessage
	PackagePath    string
	PackageSha256  string
	PackageCases   int
	CreatedBy      *string
	CreatedAt      time.Time
	StartedAt      *time.Time
	FinishedAt     *time.Time
}

func (q *Queries) ClaimBuild(ctx context.Context, arg ClaimBuildParams) (ClaimBuildRow, error) {
	row := q.db.QueryRowContext(ctx, claimBuild,
		arg.MaxAttempts,
		arg.AcceptsChecks,
		arg.WorkerID,
		arg.LeaseMs,
	)
	var i ClaimBuildRow
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.ProblemNumber,
		&i.State,
		&i.Stage,
		&i.Attempt,
		&i.WorkerID,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.ProgressDone,
		&i.ProgressTotal,
		&i.Log,
		&i.ErrorMessage,
		&i.TestsJson,
		&i.SolutionsJson,
		&i.PackagePath,
		&i.PackageSha256,
		&i.PackageCases,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const completeBuild = `-- name: CompleteBuild :execrows
UPDATE problem_build_jobs
		 SET state = $1, stage = 'done', finished_at = clock_timestamp(), lease_expires_at = NULL,
		     log = left(log || $2, $3), error_message = left($4, 4096),
		     tests_json = $5, solutions_json = $6, validation_json=$7,
		     progress_done = GREATEST(progress_done, progress_total)
		 WHERE problem_build_jobs.id = $8 AND worker_id = $9::text AND lease_token = $10::uuid
		   AND state = 'running' AND lease_expires_at > clock_timestamp() AND problem_id = $11
`

type CompleteBuildParams struct {
	State          string
	Log            string
	LogLimit       int32
	ErrorMessage   string
	TestsJson      json.RawMessage
	SolutionsJson  json.RawMessage
	ValidationJson json.RawMessage
	BuildID        string
	WorkerID       string
	LeaseToken     string
	ProblemID      string
}

func (q *Queries) CompleteBuild(ctx context.Context, arg CompleteBuildParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeBuild,
		arg.State,
		arg.Log,
		arg.LogLimit,
		arg.ErrorMessage,
		arg.TestsJson,
		arg.SolutionsJson,
		arg.ValidationJson,
		arg.BuildID,
		arg.WorkerID,
		arg.LeaseToken,
		arg.ProblemID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failExhaustedBuilds = `-- name: FailExhaustedBuilds :exec
UPDATE problem_build_jobs
		 SET state = 'dead', stage = 'done', finished_at = clock_timestamp(), lease_expires_at = NULL,
		     error_message = 'build worker lease expired too many times'
		 WHERE state = 'running' AND lease_expires_at < clock_timestamp() AND attempt >= $1
`

func (q *Queries) FailExhaustedBuilds(ctx context.Context, maxAttempts int) error {
	_, err := q.db.ExecContext(ctx, failExhaustedBuilds, maxAttempts)
	return err
}

const getBuildInput = `-- name: GetBuildInput :one
SELECT b.input_json,p.domain_id FROM problem_build_jobs b JOIN problems p ON p.id=b.problem_id WHERE b.id=$1
`

type GetBuildInputRow struct {
	InputJson json.RawMessage
	DomainID  string
}

func (q *Queries) GetBuildInput(ctx context.Context, buildID string) (GetBuildInputRow, error) {
	row := q.db.QueryRowContext(ctx, getBuildInput, buildID)
	var i GetBuildInputRow
	err := row.Scan(&i.InputJson, &i.DomainID)
	return i, err
}

const getBuildUploadTarget = `-- name: GetBuildUploadTarget :one
SELECT problem_id FROM problem_build_jobs
		 WHERE problem_build_jobs.id = $1 AND worker_id = $2::text AND lease_token = $3::uuid
		   AND state = 'running' AND lease_expires_at > clock_timestamp()
`

type GetBuildUploadTargetParams struct {
	BuildID    string
	WorkerID   string
	LeaseToken string
}

func (q *Queries) GetBuildUploadTarget(ctx context.Context, arg GetBuildUploadTargetParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getBuildUploadTarget, arg.BuildID, arg.WorkerID, arg.LeaseToken)
	var problem_id string
	err := row.Scan(&problem_id)
	return problem_id, err
}

const lockBuildForCompletion = `-- name: LockBuildForCompletion :one
SELECT state, problem_id, package_path, package_sha256, package_cases, package_manifest
		 FROM problem_build_jobs WHERE problem_build_jobs.id = $1 FOR UPDATE
`

type LockBuildForCompletionRow struct {
	State           string
	ProblemID       string
	PackagePath     string
	PackageSha256   string
	PackageCases    int
	PackageManifest json.RawMessage
}

func (q *Queries) LockBuildForCompletion(ctx context.Context, buildID string) (LockBuildForCompletionRow, error) {
	row := q.db.QueryRowContext(ctx, lockBuildForCompletion, buildID)
	var i LockBuildForCompletionRow
	err := row.Scan(
		&i.State,
		&i.ProblemID,
		&i.PackagePath,
		&i.PackageSha256,
		&i.PackageCases,
		&i.PackageManifest,
	)
	return i, err
}

const notifyBuildJob = `-- name: NotifyBuildJob :exec
SELECT pg_notify('vertex_problem_builds', $1)
`

func (q *Queries) NotifyBuildJob(ctx context.Context, buildID string) error {
	_, err := q.db.ExecContext(ctx, notifyBuildJob, buildID)
	return err
}

const recordBuildArtifact = `-- name: RecordBuildArtifact :execrows
UPDATE problem_build_jobs
		 SET package_path = $1, package_sha256 = $2, package_cases = $3, package_manifest=$4, stage = 'package'
		 WHERE problem_build_jobs.id = $5 AND problem_id = $6 AND worker_id = $7::text AND lease_token = $8::uuid
		   AND state = 'running' AND lease_expires_at > clock_timestamp()
`

type RecordBuildArtifactParams struct {
	PackagePath     string
	PackageSha256   string
	PackageCases    int
	PackageManifest json.RawMessage
	BuildID         string
	ProblemID       string
	WorkerID        string
	LeaseToken      string
}

func (q *Queries) RecordBuildArtifact(ctx context.Context, arg RecordBuildArtifactParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordBuildArtifact,
		arg.PackagePath,
		arg.PackageSha256,
		arg.PackageCases,
		arg.PackageManifest,
		arg.BuildID,
		arg.ProblemID,
		arg.WorkerID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renewBuildLease = `-- name: RenewBuildLease :one
WITH renewed AS (
		   UPDATE problem_build_jobs
		   SET lease_expires_at = clock_timestamp() + ($1::bigint * interval '1 millisecond'),
		       stage = COALESCE(NULLIF($2::text, ''), stage),
		       progress_done = GREATEST(progress_done, $3),
		       progress_total = GREATEST(progress_total, $4),
		       log = left(log || $5, $6)
		   WHERE problem_build_jobs.id = $7 AND worker_id = $8::text AND lease_token = $9::uuid
		     AND state = 'running' AND lease_expires_at > clock_timestamp()
		   RETURNING 1
		 )
		 SELECT count(*)::int FROM renewed
`

type RenewBuildLeaseParams struct {
	LeaseMs       int64
	Stage         string
	ProgressDone  int
	ProgressTotal int
	Log           string
	LogLimit      int32
	BuildID       string
	WorkerID      string
	LeaseToken    string
}

func (q *Queries) RenewBuildLease(ctx context.Context, arg RenewBuildLeaseParams) (int, error) {
	row := q.db.QueryRowContext(ctx, renewBuildLease,
		arg.LeaseMs,
		arg.Stage,
		arg.ProgressDone,
		arg.ProgressTotal,
		arg.Log,
		arg.LogLimit,
		arg.BuildID,
		arg.WorkerID,
		arg.LeaseToken,
	)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}
