// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const cancelMaterialCheck = `-- name: CancelMaterialCheck :exec
UPDATE problem_build_jobs SET state='cancelled',stage='done',finished_at=clock_timestamp(),lease_expires_at=NULL
WHERE problem_build_jobs.problem_id=$1 AND problem_build_jobs.id=$2 AND source_tree_hash IS NOT NULL AND state IN ('queued','running')
AND (source_revision IS NOT NULL OR created_by=$3 OR EXISTS(SELECT 1 FROM problem_commits c WHERE c.problem_id=problem_build_jobs.problem_id AND c.tree_hash=source_tree_hash))
`

type CancelMaterialCheckParams struct {
	ProblemID string
	ID        string
	ActorID   *string
}

func (q *Queries) CancelMaterialCheck(ctx context.Context, arg CancelMaterialCheckParams) error {
	_, err := q.db.ExecContext(ctx, cancelMaterialCheck, arg.ProblemID, arg.ID, arg.ActorID)
	return err
}

const enqueueMaterialCheck = `-- name: EnqueueMaterialCheck :one
INSERT INTO problem_build_jobs(problem_id,input_json,source_tree_hash,source_revision,data_hash,check_policy,created_by)
VALUES($1,$2,$3,$4,$5,$6,$7)
RETURNING id
`

type EnqueueMaterialCheckParams struct {
	ProblemID      string
	InputJson      json.RawMessage
	TreeHash       string
	SourceRevision sql.NullInt64
	DataHash       string
	CheckPolicy    string
	ActorID        *string
}

func (q *Queries) EnqueueMaterialCheck(ctx context.Context, arg EnqueueMaterialCheckParams) (string, error) {
	row := q.db.QueryRowContext(ctx, enqueueMaterialCheck,
		arg.ProblemID,
		arg.InputJson,
		arg.TreeHash,
		arg.SourceRevision,
		arg.DataHash,
		arg.CheckPolicy,
		arg.ActorID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const findActiveCheck = `-- name: FindActiveCheck :one
SELECT id FROM problem_build_jobs WHERE problem_build_jobs.problem_id=$1 AND source_tree_hash=$2
AND created_by=$3 AND state IN ('queued','running')
`

type FindActiveCheckParams struct {
	ProblemID string
	TreeHash  string
	ActorID   *string
}

func (q *Queries) FindActiveCheck(ctx context.Context, arg FindActiveCheckParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findActiveCheck, arg.ProblemID, arg.TreeHash, arg.ActorID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listMaterialChecks = `-- name: ListMaterialChecks :many
SELECT id,source_tree_hash,source_revision,
COALESCE((SELECT min(c.revision) FROM problem_commits c WHERE c.problem_id=problem_build_jobs.problem_id AND c.tree_hash=source_tree_hash),0)::bigint AS matching_revision,
data_hash,check_policy,toolchain_key,state,stage,progress_done,progress_total,
package_cases,created_at,started_at,finished_at
FROM problem_build_jobs WHERE problem_build_jobs.problem_id=$1 AND source_tree_hash IS NOT NULL
AND (source_revision IS NOT NULL OR created_by=$2 OR EXISTS(SELECT 1 FROM problem_commits c WHERE c.problem_id=problem_build_jobs.problem_id AND c.tree_hash=source_tree_hash))
ORDER BY created_at DESC,id DESC LIMIT $3::integer
`

type ListMaterialChecksParams struct {
	ProblemID string
	ActorID   *string
	PageLimit int
}

type ListMaterialChecksRow struct {
	ID               string
	SourceTreeHash   string
	SourceRevision   sql.NullInt64
	MatchingRevision int64
	DataHash         string
	CheckPolicy      string
	ToolchainKey     string
	State            string
	Stage            string
	ProgressDone     int
	ProgressTotal    int
	PackageCases     int
	CreatedAt        time.Time
	StartedAt        *time.Time
	FinishedAt       *time.Time
}

func (q *Queries) ListMaterialChecks(ctx context.Context, arg ListMaterialChecksParams) ([]ListMaterialChecksRow, error) {
	rows, err := q.db.QueryContext(ctx, listMaterialChecks, arg.ProblemID, arg.ActorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaterialChecksRow{}
	for rows.Next() {
		var i ListMaterialChecksRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceTreeHash,
			&i.SourceRevision,
			&i.MatchingRevision,
			&i.DataHash,
			&i.CheckPolicy,
			&i.ToolchainKey,
			&i.State,
			&i.Stage,
			&i.ProgressDone,
			&i.ProgressTotal,
			&i.PackageCases,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readCheckBinding = `-- name: ReadCheckBinding :one
SELECT source_tree_hash,source_revision,data_hash,check_policy FROM problem_build_jobs WHERE id=$1
`

type ReadCheckBindingRow struct {
	SourceTreeHash string
	SourceRevision sql.NullInt64
	DataHash       string
	CheckPolicy    string
}

func (q *Queries) ReadCheckBinding(ctx context.Context, id string) (ReadCheckBindingRow, error) {
	row := q.db.QueryRowContext(ctx, readCheckBinding, id)
	var i ReadCheckBindingRow
	err := row.Scan(
		&i.SourceTreeHash,
		&i.SourceRevision,
		&i.DataHash,
		&i.CheckPolicy,
	)
	return i, err
}

const readMaterialCheck = `-- name: ReadMaterialCheck :one
SELECT id,source_tree_hash,source_revision,
COALESCE((SELECT min(c.revision) FROM problem_commits c WHERE c.problem_id=problem_build_jobs.problem_id AND c.tree_hash=source_tree_hash),0)::bigint AS matching_revision,
data_hash,check_policy,toolchain_key,state,stage,progress_done,progress_total,log,error_message,
tests_json,solutions_json,validation_json,package_cases,created_at,started_at,finished_at
FROM problem_build_jobs WHERE problem_build_jobs.problem_id=$1 AND problem_build_jobs.id=$2 AND source_tree_hash IS NOT NULL
AND (source_revision IS NOT NULL OR created_by=$3 OR EXISTS(SELECT 1 FROM problem_commits c WHERE c.problem_id=problem_build_jobs.problem_id AND c.tree_hash=source_tree_hash))
`

type ReadMaterialCheckParams struct {
	ProblemID string
	ID        string
	ActorID   *string
}

type ReadMaterialCheckRow struct {
	ID               string
	SourceTreeHash   string
	SourceRevision   sql.NullInt64
	MatchingRevision int64
	DataHash         string
	CheckPolicy      string
	ToolchainKey     string
	State            string
	Stage            string
	ProgressDone     int
	ProgressTotal    int
	Log              string
	ErrorMessage     string
	TestsJson        json.RawMessage
	SolutionsJson    json.RawMessage
	ValidationJson   json.RawMessage
	PackageCases     int
	CreatedAt        time.Time
	StartedAt        *time.Time
	FinishedAt       *time.Time
}

func (q *Queries) ReadMaterialCheck(ctx context.Context, arg ReadMaterialCheckParams) (ReadMaterialCheckRow, error) {
	row := q.db.QueryRowContext(ctx, readMaterialCheck, arg.ProblemID, arg.ID, arg.ActorID)
	var i ReadMaterialCheckRow
	err := row.Scan(
		&i.ID,
		&i.SourceTreeHash,
		&i.SourceRevision,
		&i.MatchingRevision,
		&i.DataHash,
		&i.CheckPolicy,
		&i.ToolchainKey,
		&i.State,
		&i.Stage,
		&i.ProgressDone,
		&i.ProgressTotal,
		&i.Log,
		&i.ErrorMessage,
		&i.TestsJson,
		&i.SolutionsJson,
		&i.ValidationJson,
		&i.PackageCases,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const recordCheckToolchain = `-- name: RecordCheckToolchain :execrows
UPDATE problem_build_jobs SET toolchain_key=$1
WHERE id=$2 AND worker_id=$3 AND lease_token=$4
AND source_tree_hash IS NOT NULL AND state='running' AND lease_expires_at>clock_timestamp()
`

type RecordCheckToolchainParams struct {
	ToolchainKey string
	ID           string
	WorkerID     sql.NullString
	LeaseToken   *string
}

func (q *Queries) RecordCheckToolchain(ctx context.Context, arg RecordCheckToolchainParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordCheckToolchain,
		arg.ToolchainKey,
		arg.ID,
		arg.WorkerID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveCheckContent = `-- name: ResolveCheckContent :one
SELECT b.problem_id,o.sha256,o.byte_size FROM problem_build_jobs b
JOIN problem_tree_blobs t ON t.problem_id=b.problem_id AND t.tree_hash=b.source_tree_hash
JOIN problem_blobs o ON o.problem_id=t.problem_id AND o.sha256=t.sha256
WHERE b.id=$1 AND o.sha256=$2 AND b.worker_id=$3
AND b.lease_token=$4 AND b.state='running' AND b.lease_expires_at>clock_timestamp()
`

type ResolveCheckContentParams struct {
	BuildID    string
	Sha256     string
	WorkerID   sql.NullString
	LeaseToken *string
}

type ResolveCheckContentRow struct {
	ProblemID string
	Sha256    string
	ByteSize  int64
}

func (q *Queries) ResolveCheckContent(ctx context.Context, arg ResolveCheckContentParams) (ResolveCheckContentRow, error) {
	row := q.db.QueryRowContext(ctx, resolveCheckContent,
		arg.BuildID,
		arg.Sha256,
		arg.WorkerID,
		arg.LeaseToken,
	)
	var i ResolveCheckContentRow
	err := row.Scan(&i.ProblemID, &i.Sha256, &i.ByteSize)
	return i, err
}
