// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commit_releases.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createCommittedRelease = `-- name: CreateCommittedRelease :one
INSERT INTO problem_versions(problem_id,version_no,source_revision,source_tree_hash,check_id,toolchain_key,
title,statement_md,difficulty,source,time_limit_ms,memory_limit_kb,judge_type,statement_language,tags_json,config_json,testdata_path,sha256,case_count,checker,created_by)
VALUES($1,$2,$3,$4,$5,$6,
$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,'artifact',$20)
RETURNING version_no,source_revision,source_tree_hash,check_id,toolchain_key,statement_language,created_at
`

type CreateCommittedReleaseParams struct {
	ProblemID         string
	VersionNo         int
	SourceRevision    sql.NullInt64
	TreeHash          sql.NullString
	CheckID           *string
	ToolchainKey      string
	Title             string
	StatementMd       string
	Difficulty        int
	Source            string
	TimeLimitMs       int
	MemoryLimitKb     int
	JudgeType         string
	StatementLanguage string
	TagsJson          json.RawMessage
	ConfigJson        json.RawMessage
	TestdataPath      string
	Sha256            string
	CaseCount         int
	ActorID           *string
}

type CreateCommittedReleaseRow struct {
	VersionNo         int
	SourceRevision    sql.NullInt64
	SourceTreeHash    sql.NullString
	CheckID           *string
	ToolchainKey      string
	StatementLanguage string
	CreatedAt         time.Time
}

func (q *Queries) CreateCommittedRelease(ctx context.Context, arg CreateCommittedReleaseParams) (CreateCommittedReleaseRow, error) {
	row := q.db.QueryRowContext(ctx, createCommittedRelease,
		arg.ProblemID,
		arg.VersionNo,
		arg.SourceRevision,
		arg.TreeHash,
		arg.CheckID,
		arg.ToolchainKey,
		arg.Title,
		arg.StatementMd,
		arg.Difficulty,
		arg.Source,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.JudgeType,
		arg.StatementLanguage,
		arg.TagsJson,
		arg.ConfigJson,
		arg.TestdataPath,
		arg.Sha256,
		arg.CaseCount,
		arg.ActorID,
	)
	var i CreateCommittedReleaseRow
	err := row.Scan(
		&i.VersionNo,
		&i.SourceRevision,
		&i.SourceTreeHash,
		&i.CheckID,
		&i.ToolchainKey,
		&i.StatementLanguage,
		&i.CreatedAt,
	)
	return i, err
}

const currentReleasedVersion = `-- name: CurrentReleasedVersion :one
SELECT COALESCE(published_version,0)::integer FROM problems WHERE id=$1
`

func (q *Queries) CurrentReleasedVersion(ctx context.Context, id string) (int, error) {
	row := q.db.QueryRowContext(ctx, currentReleasedVersion, id)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const listCommittedReleases = `-- name: ListCommittedReleases :many
SELECT version_no,source_revision,source_tree_hash,check_id,toolchain_key,statement_language,created_at
FROM problem_versions WHERE problem_id=$1 AND source_revision IS NOT NULL ORDER BY version_no DESC LIMIT 100
`

type ListCommittedReleasesRow struct {
	VersionNo         int
	SourceRevision    sql.NullInt64
	SourceTreeHash    sql.NullString
	CheckID           *string
	ToolchainKey      string
	StatementLanguage string
	CreatedAt         time.Time
}

func (q *Queries) ListCommittedReleases(ctx context.Context, problemID string) ([]ListCommittedReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommittedReleases, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommittedReleasesRow{}
	for rows.Next() {
		var i ListCommittedReleasesRow
		if err := rows.Scan(
			&i.VersionNo,
			&i.SourceRevision,
			&i.SourceTreeHash,
			&i.CheckID,
			&i.ToolchainKey,
			&i.StatementLanguage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicationCheckArtifact = `-- name: PublicationCheckArtifact :one
SELECT package_path,package_sha256,package_cases,package_manifest,toolchain_key,data_hash,check_policy
FROM problem_build_jobs WHERE problem_id=$1 AND id=$2 AND source_tree_hash IS NOT NULL AND state='succeeded'
`

type PublicationCheckArtifactParams struct {
	ProblemID string
	ID        string
}

type PublicationCheckArtifactRow struct {
	PackagePath     string
	PackageSha256   string
	PackageCases    int
	PackageManifest json.RawMessage
	ToolchainKey    string
	DataHash        string
	CheckPolicy     string
}

func (q *Queries) PublicationCheckArtifact(ctx context.Context, arg PublicationCheckArtifactParams) (PublicationCheckArtifactRow, error) {
	row := q.db.QueryRowContext(ctx, publicationCheckArtifact, arg.ProblemID, arg.ID)
	var i PublicationCheckArtifactRow
	err := row.Scan(
		&i.PackagePath,
		&i.PackageSha256,
		&i.PackageCases,
		&i.PackageManifest,
		&i.ToolchainKey,
		&i.DataHash,
		&i.CheckPolicy,
	)
	return i, err
}

const readCommittedRelease = `-- name: ReadCommittedRelease :one
SELECT version_no,source_revision,source_tree_hash,check_id,toolchain_key,statement_language,created_at
FROM problem_versions WHERE problem_id=$1 AND version_no=$2 AND source_revision IS NOT NULL
`

type ReadCommittedReleaseParams struct {
	ProblemID string
	VersionNo int
}

type ReadCommittedReleaseRow struct {
	VersionNo         int
	SourceRevision    sql.NullInt64
	SourceTreeHash    sql.NullString
	CheckID           *string
	ToolchainKey      string
	StatementLanguage string
	CreatedAt         time.Time
}

func (q *Queries) ReadCommittedRelease(ctx context.Context, arg ReadCommittedReleaseParams) (ReadCommittedReleaseRow, error) {
	row := q.db.QueryRowContext(ctx, readCommittedRelease, arg.ProblemID, arg.VersionNo)
	var i ReadCommittedReleaseRow
	err := row.Scan(
		&i.VersionNo,
		&i.SourceRevision,
		&i.SourceTreeHash,
		&i.CheckID,
		&i.ToolchainKey,
		&i.StatementLanguage,
		&i.CreatedAt,
	)
	return i, err
}
