// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copy.sql

package dbgen

import (
	"context"
	"time"
)

const getCopySourceDomain = `-- name: GetCopySourceDomain :one
SELECT id FROM domains WHERE slug=$1
`

func (q *Queries) GetCopySourceDomain(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCopySourceDomain, slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getInheritedAttribution = `-- name: GetInheritedAttribution :one
SELECT COALESCE((SELECT attribution FROM problem_origins WHERE problem_id=$1),'')::text
`

func (q *Queries) GetInheritedAttribution(ctx context.Context, problemID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getInheritedAttribution, problemID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const getProblemOrigin = `-- name: GetProblemOrigin :one
SELECT source_domain_id,source_domain_slug,source_problem_id,source_problem_number,source_version,source_title,source_sha256,attribution,copied_by,copied_at FROM problem_origins WHERE problem_id=$1
`

type GetProblemOriginRow struct {
	SourceDomainID      string
	SourceDomainSlug    string
	SourceProblemID     string
	SourceProblemNumber string
	SourceVersion       int
	SourceTitle         string
	SourceSha256        string
	Attribution         string
	CopiedBy            *string
	CopiedAt            time.Time
}

func (q *Queries) GetProblemOrigin(ctx context.Context, problemID string) (GetProblemOriginRow, error) {
	row := q.db.QueryRowContext(ctx, getProblemOrigin, problemID)
	var i GetProblemOriginRow
	err := row.Scan(
		&i.SourceDomainID,
		&i.SourceDomainSlug,
		&i.SourceProblemID,
		&i.SourceProblemNumber,
		&i.SourceVersion,
		&i.SourceTitle,
		&i.SourceSha256,
		&i.Attribution,
		&i.CopiedBy,
		&i.CopiedAt,
	)
	return i, err
}

const recordProblemCopyAudit = `-- name: RecordProblemCopyAudit :exec
INSERT INTO domain_audit_events(domain_id,actor_id,action,target) VALUES($1,$2,$3,$4)
`

type RecordProblemCopyAuditParams struct {
	DomainID string
	ActorID  *string
	Action   string
	Target   string
}

func (q *Queries) RecordProblemCopyAudit(ctx context.Context, arg RecordProblemCopyAuditParams) error {
	_, err := q.db.ExecContext(ctx, recordProblemCopyAudit,
		arg.DomainID,
		arg.ActorID,
		arg.Action,
		arg.Target,
	)
	return err
}

const resolveCopySourceNumber = `-- name: ResolveCopySourceNumber :one
SELECT id,public_id FROM problems WHERE domain_id=$1::uuid AND public_id=$2::bigint
`

type ResolveCopySourceNumberParams struct {
	DomainID      string
	ProblemNumber int64
}

type ResolveCopySourceNumberRow struct {
	ID       string
	PublicID string
}

func (q *Queries) ResolveCopySourceNumber(ctx context.Context, arg ResolveCopySourceNumberParams) (ResolveCopySourceNumberRow, error) {
	row := q.db.QueryRowContext(ctx, resolveCopySourceNumber, arg.DomainID, arg.ProblemNumber)
	var i ResolveCopySourceNumberRow
	err := row.Scan(&i.ID, &i.PublicID)
	return i, err
}

const saveProblemOrigin = `-- name: SaveProblemOrigin :one
INSERT INTO problem_origins(problem_id,source_domain_id,source_domain_slug,source_problem_id,source_problem_number,source_version,source_title,source_sha256,attribution,copied_by)
 VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING source_domain_id,source_domain_slug,source_problem_id,source_problem_number,source_version,source_title,source_sha256,attribution,copied_by,copied_at
`

type SaveProblemOriginParams struct {
	ProblemID           string
	SourceDomainID      string
	SourceDomainSlug    string
	SourceProblemID     string
	SourceProblemNumber string
	SourceVersion       int
	SourceTitle         string
	SourceSha256        string
	Attribution         string
	CopiedBy            *string
}

type SaveProblemOriginRow struct {
	SourceDomainID      string
	SourceDomainSlug    string
	SourceProblemID     string
	SourceProblemNumber string
	SourceVersion       int
	SourceTitle         string
	SourceSha256        string
	Attribution         string
	CopiedBy            *string
	CopiedAt            time.Time
}

func (q *Queries) SaveProblemOrigin(ctx context.Context, arg SaveProblemOriginParams) (SaveProblemOriginRow, error) {
	row := q.db.QueryRowContext(ctx, saveProblemOrigin,
		arg.ProblemID,
		arg.SourceDomainID,
		arg.SourceDomainSlug,
		arg.SourceProblemID,
		arg.SourceProblemNumber,
		arg.SourceVersion,
		arg.SourceTitle,
		arg.SourceSha256,
		arg.Attribution,
		arg.CopiedBy,
	)
	var i SaveProblemOriginRow
	err := row.Scan(
		&i.SourceDomainID,
		&i.SourceDomainSlug,
		&i.SourceProblemID,
		&i.SourceProblemNumber,
		&i.SourceVersion,
		&i.SourceTitle,
		&i.SourceSha256,
		&i.Attribution,
		&i.CopiedBy,
		&i.CopiedAt,
	)
	return i, err
}
