// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const applyPackageImport = `-- name: ApplyPackageImport :execrows
UPDATE problem_imports SET applied_at=now() WHERE problem_id=$1 AND actor_id=$2 AND id=$3 AND applied_at IS NULL AND expires_at>now()
`

type ApplyPackageImportParams struct {
	ProblemID string
	ActorID   string
	ID        string
}

func (q *Queries) ApplyPackageImport(ctx context.Context, arg ApplyPackageImportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, applyPackageImport, arg.ProblemID, arg.ActorID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createPackageImport = `-- name: CreatePackageImport :one
INSERT INTO problem_imports(problem_id,actor_id,base_etag,archive_hash,tree_hash,plan_json)
VALUES($1,$2,$3,$4,$5,$6) RETURNING id,base_etag,plan_json,expires_at,applied_at
`

type CreatePackageImportParams struct {
	ProblemID   string
	ActorID     string
	BaseEtag    string
	ArchiveHash string
	TreeHash    string
	PlanJson    json.RawMessage
}

type CreatePackageImportRow struct {
	ID        string
	BaseEtag  string
	PlanJson  json.RawMessage
	ExpiresAt time.Time
	AppliedAt *time.Time
}

func (q *Queries) CreatePackageImport(ctx context.Context, arg CreatePackageImportParams) (CreatePackageImportRow, error) {
	row := q.db.QueryRowContext(ctx, createPackageImport,
		arg.ProblemID,
		arg.ActorID,
		arg.BaseEtag,
		arg.ArchiveHash,
		arg.TreeHash,
		arg.PlanJson,
	)
	var i CreatePackageImportRow
	err := row.Scan(
		&i.ID,
		&i.BaseEtag,
		&i.PlanJson,
		&i.ExpiresAt,
		&i.AppliedAt,
	)
	return i, err
}

const findExportCheck = `-- name: FindExportCheck :one
SELECT package_path,package_manifest,toolchain_key,data_hash,check_policy
FROM problem_build_jobs WHERE problem_build_jobs.problem_id=$1 AND data_hash=$2
AND check_policy=$3 AND state='succeeded' AND source_tree_hash IS NOT NULL
AND (created_by=$4 OR source_revision IS NOT NULL OR EXISTS(
 SELECT 1 FROM problem_commits c WHERE c.problem_id=problem_build_jobs.problem_id AND c.tree_hash=source_tree_hash))
ORDER BY finished_at DESC,id DESC LIMIT 1
`

type FindExportCheckParams struct {
	ProblemID   string
	DataHash    string
	CheckPolicy string
	ActorID     *string
}

type FindExportCheckRow struct {
	PackagePath     string
	PackageManifest json.RawMessage
	ToolchainKey    string
	DataHash        string
	CheckPolicy     string
}

func (q *Queries) FindExportCheck(ctx context.Context, arg FindExportCheckParams) (FindExportCheckRow, error) {
	row := q.db.QueryRowContext(ctx, findExportCheck,
		arg.ProblemID,
		arg.DataHash,
		arg.CheckPolicy,
		arg.ActorID,
	)
	var i FindExportCheckRow
	err := row.Scan(
		&i.PackagePath,
		&i.PackageManifest,
		&i.ToolchainKey,
		&i.DataHash,
		&i.CheckPolicy,
	)
	return i, err
}

const grantImportBlobs = `-- name: GrantImportBlobs :exec
INSERT INTO problem_blob_uploads(problem_id,sha256,actor_id)
SELECT $1::uuid,unnest($2::text[]),$3::uuid
ON CONFLICT(problem_id,sha256,actor_id) DO UPDATE SET created_at=now()
`

type GrantImportBlobsParams struct {
	ProblemID string
	Hashes    []string
	ActorID   string
}

func (q *Queries) GrantImportBlobs(ctx context.Context, arg GrantImportBlobsParams) error {
	_, err := q.db.ExecContext(ctx, grantImportBlobs, arg.ProblemID, pq.Array(arg.Hashes), arg.ActorID)
	return err
}

const readPackageImport = `-- name: ReadPackageImport :one
SELECT id,base_etag,plan_json,expires_at,applied_at FROM problem_imports WHERE problem_id=$1 AND actor_id=$2 AND id=$3
`

type ReadPackageImportParams struct {
	ProblemID string
	ActorID   string
	ID        string
}

type ReadPackageImportRow struct {
	ID        string
	BaseEtag  string
	PlanJson  json.RawMessage
	ExpiresAt time.Time
	AppliedAt *time.Time
}

func (q *Queries) ReadPackageImport(ctx context.Context, arg ReadPackageImportParams) (ReadPackageImportRow, error) {
	row := q.db.QueryRowContext(ctx, readPackageImport, arg.ProblemID, arg.ActorID, arg.ID)
	var i ReadPackageImportRow
	err := row.Scan(
		&i.ID,
		&i.BaseEtag,
		&i.PlanJson,
		&i.ExpiresAt,
		&i.AppliedAt,
	)
	return i, err
}

const registerImportBlobs = `-- name: RegisterImportBlobs :exec
INSERT INTO problem_blobs(problem_id,sha256,byte_size)
SELECT $1::uuid,unnest($2::text[]),unnest($3::bigint[])
ON CONFLICT DO NOTHING
`

type RegisterImportBlobsParams struct {
	ProblemID string
	Hashes    []string
	Sizes     []int64
}

func (q *Queries) RegisterImportBlobs(ctx context.Context, arg RegisterImportBlobsParams) error {
	_, err := q.db.ExecContext(ctx, registerImportBlobs, arg.ProblemID, pq.Array(arg.Hashes), pq.Array(arg.Sizes))
	return err
}
