// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: garbage.sql

package dbgen

import (
	"context"
	"time"
)

const expireBlobGrants = `-- name: ExpireBlobGrants :execrows
DELETE FROM problem_blob_uploads WHERE ctid IN (
 SELECT ctid FROM problem_blob_uploads WHERE problem_blob_uploads.problem_id=$1 AND created_at<$2::timestamptz ORDER BY created_at LIMIT 1000
)
`

type ExpireBlobGrantsParams struct {
	ProblemID string
	Cutoff    time.Time
}

func (q *Queries) ExpireBlobGrants(ctx context.Context, arg ExpireBlobGrantsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireBlobGrants, arg.ProblemID, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expirePackageImports = `-- name: ExpirePackageImports :execrows
DELETE FROM problem_imports WHERE id IN (
 SELECT id FROM problem_imports WHERE problem_imports.problem_id=$1 AND expires_at<$2::timestamptz ORDER BY expires_at LIMIT 1000
)
`

type ExpirePackageImportsParams struct {
	ProblemID string
	Cutoff    time.Time
}

func (q *Queries) ExpirePackageImports(ctx context.Context, arg ExpirePackageImportsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expirePackageImports, arg.ProblemID, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const garbageNamespaces = `-- name: GarbageNamespaces :many
SELECT problem_id::text FROM (
 SELECT problem_id FROM problem_content_trees UNION SELECT problem_id FROM problem_blobs UNION SELECT problem_id FROM problem_imports
) candidates WHERE problem_id::text>$1::text ORDER BY problem_id LIMIT $2::integer
`

type GarbageNamespacesParams struct {
	AfterID   string
	PageLimit int
}

func (q *Queries) GarbageNamespaces(ctx context.Context, arg GarbageNamespacesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, garbageNamespaces, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var problem_id string
		if err := rows.Scan(&problem_id); err != nil {
			return nil, err
		}
		items = append(items, problem_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAuthoringBlobs = `-- name: PruneAuthoringBlobs :execrows
DELETE FROM problem_blobs WHERE (problem_id,sha256) IN (
 SELECT b.problem_id,b.sha256 FROM problem_blobs b WHERE b.problem_id=$1 AND b.created_at<$2::timestamptz
 AND NOT EXISTS(SELECT 1 FROM problem_tree_blobs t WHERE t.problem_id=b.problem_id AND t.sha256=b.sha256)
 AND NOT EXISTS(SELECT 1 FROM problem_version_files f WHERE f.problem_id=b.problem_id AND f.blob_sha256=b.sha256)
 AND NOT EXISTS(SELECT 1 FROM problem_blob_uploads u WHERE u.problem_id=b.problem_id AND u.sha256=b.sha256)
 AND NOT EXISTS(SELECT 1 FROM problem_imports i WHERE i.problem_id=b.problem_id AND i.archive_hash=b.sha256)
 AND NOT EXISTS(SELECT 1 FROM problem_merge_sessions m, jsonb_array_elements(CASE WHEN jsonb_typeof(m.result_json#>'{tree,entries}')='array' THEN m.result_json#>'{tree,entries}' ELSE '[]'::jsonb END) e WHERE m.problem_id=b.problem_id AND e#>>'{blob,sha256}'=b.sha256)
 ORDER BY b.created_at LIMIT 1000
)
`

type PruneAuthoringBlobsParams struct {
	ProblemID string
	Cutoff    time.Time
}

func (q *Queries) PruneAuthoringBlobs(ctx context.Context, arg PruneAuthoringBlobsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAuthoringBlobs, arg.ProblemID, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneAuthoringTrees = `-- name: PruneAuthoringTrees :execrows
DELETE FROM problem_content_trees WHERE (problem_id,tree_hash) IN (
 SELECT t.problem_id,t.tree_hash FROM problem_content_trees t
 WHERE t.problem_id=$1 AND t.created_at<$2::timestamptz
 AND NOT EXISTS(SELECT 1 FROM problem_commits c WHERE c.problem_id=t.problem_id AND c.tree_hash=t.tree_hash)
 AND NOT EXISTS(SELECT 1 FROM problem_authoring_heads h WHERE h.problem_id=t.problem_id AND (h.tree_hash=t.tree_hash OR h.initial_tree_hash=t.tree_hash))
 AND NOT EXISTS(SELECT 1 FROM problem_working_copies w WHERE w.problem_id=t.problem_id AND w.tree_hash=t.tree_hash)
 AND NOT EXISTS(SELECT 1 FROM problem_merge_sessions m WHERE m.problem_id=t.problem_id AND (m.local_tree=t.tree_hash OR m.remote_tree=t.tree_hash))
 AND NOT EXISTS(SELECT 1 FROM problem_imports i WHERE i.problem_id=t.problem_id AND i.tree_hash=t.tree_hash)
 AND NOT EXISTS(SELECT 1 FROM problem_build_jobs b WHERE b.problem_id=t.problem_id AND b.source_tree_hash=t.tree_hash)
 AND NOT EXISTS(SELECT 1 FROM problem_versions v WHERE v.problem_id=t.problem_id AND v.source_tree_hash=t.tree_hash)
 ORDER BY t.created_at LIMIT 1000
)
`

type PruneAuthoringTreesParams struct {
	ProblemID string
	Cutoff    time.Time
}

func (q *Queries) PruneAuthoringTrees(ctx context.Context, arg PruneAuthoringTreesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAuthoringTrees, arg.ProblemID, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseGarbageStorageLock = `-- name: ReleaseGarbageStorageLock :exec
SELECT pg_advisory_unlock(hashtextextended($1::text,0))
`

func (q *Queries) ReleaseGarbageStorageLock(ctx context.Context, resourceKey string) error {
	_, err := q.db.ExecContext(ctx, releaseGarbageStorageLock, resourceKey)
	return err
}

const retainedAuthoringArtifacts = `-- name: RetainedAuthoringArtifacts :many
SELECT testdata_path AS storage_path FROM problem_versions WHERE testdata_path<>'' AND testdata_path LIKE $1::text||'/%'
UNION SELECT package_path AS storage_path FROM problem_build_jobs WHERE package_path<>'' AND package_path LIKE $1::text||'/%'
`

func (q *Queries) RetainedAuthoringArtifacts(ctx context.Context, namespaceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, retainedAuthoringArtifacts, namespaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var storage_path string
		if err := rows.Scan(&storage_path); err != nil {
			return nil, err
		}
		items = append(items, storage_path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retainedAuthoringBlobs = `-- name: RetainedAuthoringBlobs :many
SELECT sha256 FROM problem_blobs WHERE problem_id=$1
`

func (q *Queries) RetainedAuthoringBlobs(ctx context.Context, problemID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, retainedAuthoringBlobs, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var sha256 string
		if err := rows.Scan(&sha256); err != nil {
			return nil, err
		}
		items = append(items, sha256)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryGarbageStorageLock = `-- name: TryGarbageStorageLock :one
SELECT pg_try_advisory_lock(hashtextextended($1::text,0))::boolean
`

func (q *Queries) TryGarbageStorageLock(ctx context.Context, resourceKey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, tryGarbageStorageLock, resourceKey)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
