// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library.sql

package dbgen

import (
	"context"
	"time"
)

const listAuthoringLibrary = `-- name: ListAuthoringLibrary :many
WITH visible AS (
 SELECT p.public_id,p.owner_id,p.visibility,COALESCE(u.username,'')::text AS owner_name,
 COALESCE(NULLIF(t.summary->>'title',''),p.title)::text AS title,
 COALESCE(t.summary->>'source',p.source)::text AS source,
 grants.grant_rank,
 (w.actor_id IS NOT NULL)::boolean AS has_copy,
 COALESCE(w.tree_hash IS DISTINCT FROM COALESCE(base.tree_hash,h.initial_tree_hash) AND w.actor_id IS NOT NULL,false)::boolean AS has_changes,
 EXISTS(SELECT 1 FROM problem_merge_sessions m WHERE m.problem_id=p.id AND m.actor_id=NULLIF($6::text,'')::uuid)::boolean AS has_conflict,
 COALESCE(w.base_revision,0)::bigint AS base_revision,COALESCE(h.revision,0)::bigint AS head_revision,
 COALESCE(p.published_version,0)::integer AS published_version,COALESCE(v.source_revision,0)::bigint AS published_revision,
 COALESCE(check_run.id::text,'')::text AS check_id,COALESCE(check_run.state,'')::text AS check_state,
 COALESCE(check_run.source_tree_hash=t.tree_hash,false)::boolean AS check_matches,
 GREATEST(p.updated_at,w.updated_at,head_commit.created_at)::timestamptz AS updated_at
 FROM problems p
 LEFT JOIN users u ON u.id=p.owner_id
 LEFT JOIN problem_authoring_heads h ON h.problem_id=p.id
 LEFT JOIN problem_commits head_commit ON head_commit.problem_id=p.id AND head_commit.revision=h.revision
 LEFT JOIN problem_working_copies w ON w.problem_id=p.id AND w.actor_id=NULLIF($6::text,'')::uuid
 LEFT JOIN problem_commits base ON base.problem_id=p.id AND base.revision=w.base_revision
 LEFT JOIN problem_content_trees t ON t.problem_id=p.id AND t.tree_hash=COALESCE(w.tree_hash,h.tree_hash,h.initial_tree_hash)
 LEFT JOIN problem_versions v ON v.problem_id=p.id AND v.version_no=p.published_version
 LEFT JOIN LATERAL (SELECT COALESCE(max(CASE WHEN a.role='editor' THEN 2 ELSE 1 END),0)::integer AS grant_rank
   FROM problem_access a WHERE a.problem_id=p.id AND a.domain_id=p.domain_id
   AND (a.user_id=NULLIF($6::text,'')::uuid OR a.group_id IN (
     SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($6::text,'')::uuid))) grants ON true
 LEFT JOIN LATERAL (SELECT b.id,b.state,b.source_tree_hash FROM problem_build_jobs b
   WHERE b.problem_id=p.id AND b.source_tree_hash IS NOT NULL
   AND (b.created_by=NULLIF($6::text,'')::uuid OR b.source_revision IS NOT NULL OR EXISTS(
     SELECT 1 FROM problem_commits c WHERE c.problem_id=b.problem_id AND c.tree_hash=b.source_tree_hash))
   ORDER BY b.created_at DESC,b.id DESC LIMIT 1) check_run ON true
 WHERE p.domain_id=$7::uuid
 AND ($8::boolean OR ($9::boolean AND (p.owner_id=NULLIF($6::text,'')::uuid OR grants.grant_rank>0)))
)
SELECT visible.public_id, visible.owner_id, visible.visibility, visible.owner_name, visible.title, visible.source, visible.grant_rank, visible.has_copy, visible.has_changes, visible.has_conflict, visible.base_revision, visible.head_revision, visible.published_version, visible.published_revision, visible.check_id, visible.check_state, visible.check_matches, visible.updated_at,count(*) OVER()::bigint AS total FROM visible
WHERE ($1::text='' OR visible.visibility=$1::text)
AND ($2::text='' OR title ILIKE '%'||$2::text||'%' OR source ILIKE '%'||$2::text||'%' OR public_id::text=$2::text)
AND ($3::text='' OR ($3::text='changes' AND has_changes) OR ($3::text='conflicts' AND has_conflict) OR ($3::text='unpublished' AND published_version=0))
ORDER BY updated_at DESC,public_id DESC LIMIT $5::integer OFFSET $4::integer
`

type ListAuthoringLibraryParams struct {
	Visibility   string
	Keyword      string
	Status       string
	PageOffset   int
	PageLimit    int
	ActorID      string
	DomainID     string
	IsManager    bool
	ActiveMember bool
}

type ListAuthoringLibraryRow struct {
	PublicID          string
	OwnerID           string
	Visibility        string
	OwnerName         string
	Title             string
	Source            string
	GrantRank         int
	HasCopy           bool
	HasChanges        bool
	HasConflict       bool
	BaseRevision      int64
	HeadRevision      int64
	PublishedVersion  int
	PublishedRevision int64
	CheckID           string
	CheckState        string
	CheckMatches      bool
	UpdatedAt         time.Time
	Total             int64
}

func (q *Queries) ListAuthoringLibrary(ctx context.Context, arg ListAuthoringLibraryParams) ([]ListAuthoringLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthoringLibrary,
		arg.Visibility,
		arg.Keyword,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
		arg.ActorID,
		arg.DomainID,
		arg.IsManager,
		arg.ActiveMember,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthoringLibraryRow{}
	for rows.Next() {
		var i ListAuthoringLibraryRow
		if err := rows.Scan(
			&i.PublicID,
			&i.OwnerID,
			&i.Visibility,
			&i.OwnerName,
			&i.Title,
			&i.Source,
			&i.GrantRank,
			&i.HasCopy,
			&i.HasChanges,
			&i.HasConflict,
			&i.BaseRevision,
			&i.HeadRevision,
			&i.PublishedVersion,
			&i.PublishedRevision,
			&i.CheckID,
			&i.CheckState,
			&i.CheckMatches,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
