// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type ProblemCommit struct {
	ProblemID      string
	Revision       int64
	ParentRevision sql.NullInt64
	TreeHash       string
	AuthorID       *string
	Message        string
	RequestID      string
	RequestEtag    string
	CreatedAt      time.Time
}

type ProblemMergeSession struct {
	ID             string
	ProblemID      string
	ActorID        string
	Etag           string
	CopyEtag       string
	BaseRevision   sql.NullInt64
	RemoteRevision sql.NullInt64
	LocalTree      string
	RemoteTree     string
	ResultJson     json.RawMessage
	UpdatedAt      time.Time
}
