// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: package_write.sql

package dbgen

import (
	"context"
)

const bumpPackageRevision = `-- name: BumpPackageRevision :one
UPDATE problems SET package_revision = package_revision + 1, data_revision=data_revision+CASE WHEN $3::boolean THEN 1 ELSE 0 END
		 WHERE id = $1 AND domain_id = $2
		 RETURNING package_revision
`

type BumpPackageRevisionParams struct {
	ID          string
	DomainID    string
	DataChanged bool
}

func (q *Queries) BumpPackageRevision(ctx context.Context, arg BumpPackageRevisionParams) (int, error) {
	row := q.db.QueryRowContext(ctx, bumpPackageRevision, arg.ID, arg.DomainID, arg.DataChanged)
	var package_revision int
	err := row.Scan(&package_revision)
	return package_revision, err
}

const clearDeletedWorkspaceStatement = `-- name: ClearDeletedWorkspaceStatement :exec
UPDATE problem_workspaces SET statement_md='',updated_at=now() WHERE problem_id=$1 AND statement_language=$2
`

type ClearDeletedWorkspaceStatementParams struct {
	ProblemID         string
	StatementLanguage string
}

func (q *Queries) ClearDeletedWorkspaceStatement(ctx context.Context, arg ClearDeletedWorkspaceStatementParams) error {
	_, err := q.db.ExecContext(ctx, clearDeletedWorkspaceStatement, arg.ProblemID, arg.StatementLanguage)
	return err
}

const closeTestOrderGap = `-- name: CloseTestOrderGap :exec
UPDATE problem_tests SET test_index = test_index - 1
			 WHERE problem_tests.problem_id = $1 AND test_index > $2
`

type CloseTestOrderGapParams struct {
	ProblemID string
	TestIndex int
}

func (q *Queries) CloseTestOrderGap(ctx context.Context, arg CloseTestOrderGapParams) error {
	_, err := q.db.ExecContext(ctx, closeTestOrderGap, arg.ProblemID, arg.TestIndex)
	return err
}

const createProblemTest = `-- name: CreateProblemTest :one
INSERT INTO problem_tests
			   (problem_id, test_index, group_name, source, input_data, generate_cmd,
			    is_sample, points, description)
			 VALUES ($1,
			   COALESCE((SELECT max(test_index) FROM problem_tests WHERE problem_tests.problem_id = $1), 0) + 1,
			   $2, $3, $4, $5, $6, $7, $8)
			 RETURNING id, problem_id, test_index, group_name, source, input_data,
	generate_cmd, is_sample, points, description
`

type CreateProblemTestParams struct {
	ProblemID   string
	GroupName   string
	Source      string
	InputData   string
	GenerateCmd string
	IsSample    bool
	Points      int
	Description string
}

func (q *Queries) CreateProblemTest(ctx context.Context, arg CreateProblemTestParams) (ProblemTest, error) {
	row := q.db.QueryRowContext(ctx, createProblemTest,
		arg.ProblemID,
		arg.GroupName,
		arg.Source,
		arg.InputData,
		arg.GenerateCmd,
		arg.IsSample,
		arg.Points,
		arg.Description,
	)
	var i ProblemTest
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.TestIndex,
		&i.GroupName,
		&i.Source,
		&i.InputData,
		&i.GenerateCmd,
		&i.IsSample,
		&i.Points,
		&i.Description,
	)
	return i, err
}

const deactivateOtherProblemFiles = `-- name: DeactivateOtherProblemFiles :exec
UPDATE problem_files SET is_active = FALSE, updated_at = now()
				 WHERE problem_files.problem_id = $1 AND kind = $2 AND is_active AND name <> $3
`

type DeactivateOtherProblemFilesParams struct {
	ProblemID string
	Kind      string
	Name      string
}

func (q *Queries) DeactivateOtherProblemFiles(ctx context.Context, arg DeactivateOtherProblemFilesParams) error {
	_, err := q.db.ExecContext(ctx, deactivateOtherProblemFiles, arg.ProblemID, arg.Kind, arg.Name)
	return err
}

const deleteProblemFile = `-- name: DeleteProblemFile :execrows
DELETE FROM problem_files WHERE problem_files.problem_id = $1 AND problem_files.id = $2
`

type DeleteProblemFileParams struct {
	ProblemID string
	ID        int64
}

func (q *Queries) DeleteProblemFile(ctx context.Context, arg DeleteProblemFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProblemFile, arg.ProblemID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProblemStatement = `-- name: DeleteProblemStatement :execrows
DELETE FROM problem_statements WHERE problem_id = $1 AND language = $2
`

type DeleteProblemStatementParams struct {
	ProblemID string
	Language  string
}

func (q *Queries) DeleteProblemStatement(ctx context.Context, arg DeleteProblemStatementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProblemStatement, arg.ProblemID, arg.Language)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProblemTest = `-- name: DeleteProblemTest :one
DELETE FROM problem_tests WHERE problem_tests.problem_id = $1 AND problem_tests.id = $2 RETURNING test_index
`

type DeleteProblemTestParams struct {
	ProblemID string
	ID        int64
}

func (q *Queries) DeleteProblemTest(ctx context.Context, arg DeleteProblemTestParams) (int, error) {
	row := q.db.QueryRowContext(ctx, deleteProblemTest, arg.ProblemID, arg.ID)
	var test_index int
	err := row.Scan(&test_index)
	return test_index, err
}

const getTestOrderBounds = `-- name: GetTestOrderBounds :one
SELECT test_index,
			        (SELECT count(*)::int FROM problem_tests WHERE problem_tests.problem_id = $1)::integer AS total_tests
			 FROM problem_tests WHERE problem_tests.problem_id = $1 AND problem_tests.id = $2
`

type GetTestOrderBoundsParams struct {
	ProblemID string
	ID        int64
}

type GetTestOrderBoundsRow struct {
	TestIndex  int
	TotalTests int
}

func (q *Queries) GetTestOrderBounds(ctx context.Context, arg GetTestOrderBoundsParams) (GetTestOrderBoundsRow, error) {
	row := q.db.QueryRowContext(ctx, getTestOrderBounds, arg.ProblemID, arg.ID)
	var i GetTestOrderBoundsRow
	err := row.Scan(&i.TestIndex, &i.TotalTests)
	return i, err
}

const listProblemStatements = `-- name: ListProblemStatements :many
SELECT problem_id, language, name, legend, input_format, output_format,
		        notes, tutorial, scoring, updated_at
		 FROM problem_statements WHERE problem_id = $1
		 AND EXISTS (SELECT 1 FROM problems WHERE id = $1 AND domain_id = $2)
		 ORDER BY language
`

type ListProblemStatementsParams struct {
	ProblemID string
	DomainID  string
}

func (q *Queries) ListProblemStatements(ctx context.Context, arg ListProblemStatementsParams) ([]ProblemStatement, error) {
	rows, err := q.db.QueryContext(ctx, listProblemStatements, arg.ProblemID, arg.DomainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProblemStatement{}
	for rows.Next() {
		var i ProblemStatement
		if err := rows.Scan(
			&i.ProblemID,
			&i.Language,
			&i.Name,
			&i.Legend,
			&i.InputFormat,
			&i.OutputFormat,
			&i.Notes,
			&i.Tutorial,
			&i.Scoring,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const parkTestForReorder = `-- name: ParkTestForReorder :exec
UPDATE problem_tests
			 SET test_index = (SELECT max(test_index) + 1 FROM problem_tests WHERE problem_tests.problem_id = $1)
			 WHERE problem_tests.problem_id = $1 AND problem_tests.id = $2
`

type ParkTestForReorderParams struct {
	ProblemID string
	ID        int64
}

func (q *Queries) ParkTestForReorder(ctx context.Context, arg ParkTestForReorderParams) error {
	_, err := q.db.ExecContext(ctx, parkTestForReorder, arg.ProblemID, arg.ID)
	return err
}

const setTestOrder = `-- name: SetTestOrder :exec
UPDATE problem_tests SET test_index = $3 WHERE problem_tests.problem_id = $1 AND problem_tests.id = $2
`

type SetTestOrderParams struct {
	ProblemID string
	ID        int64
	TestIndex int
}

func (q *Queries) SetTestOrder(ctx context.Context, arg SetTestOrderParams) error {
	_, err := q.db.ExecContext(ctx, setTestOrder, arg.ProblemID, arg.ID, arg.TestIndex)
	return err
}

const shiftTestsLeft = `-- name: ShiftTestsLeft :exec
UPDATE problem_tests SET test_index = test_index - 1
				 WHERE problem_tests.problem_id = $1::uuid AND test_index > $2::integer AND test_index <= $3::integer
`

type ShiftTestsLeftParams struct {
	ProblemID  string
	RangeStart int
	RangeEnd   int
}

func (q *Queries) ShiftTestsLeft(ctx context.Context, arg ShiftTestsLeftParams) error {
	_, err := q.db.ExecContext(ctx, shiftTestsLeft, arg.ProblemID, arg.RangeStart, arg.RangeEnd)
	return err
}

const shiftTestsRight = `-- name: ShiftTestsRight :exec
UPDATE problem_tests SET test_index = test_index + 1
				 WHERE problem_tests.problem_id = $1::uuid AND test_index >= $2::integer AND test_index < $3::integer
`

type ShiftTestsRightParams struct {
	ProblemID  string
	RangeStart int
	RangeEnd   int
}

func (q *Queries) ShiftTestsRight(ctx context.Context, arg ShiftTestsRightParams) error {
	_, err := q.db.ExecContext(ctx, shiftTestsRight, arg.ProblemID, arg.RangeStart, arg.RangeEnd)
	return err
}

const updateProblemTest = `-- name: UpdateProblemTest :one
UPDATE problem_tests
			 SET group_name = $3, source = $4, input_data = $5, generate_cmd = $6,
			     is_sample = $7, points = $8, description = $9
			 WHERE problem_tests.problem_id = $1 AND problem_tests.id = $2
			 RETURNING id, problem_id, test_index, group_name, source, input_data,
	generate_cmd, is_sample, points, description
`

type UpdateProblemTestParams struct {
	ProblemID   string
	ID          int64
	GroupName   string
	Source      string
	InputData   string
	GenerateCmd string
	IsSample    bool
	Points      int
	Description string
}

func (q *Queries) UpdateProblemTest(ctx context.Context, arg UpdateProblemTestParams) (ProblemTest, error) {
	row := q.db.QueryRowContext(ctx, updateProblemTest,
		arg.ProblemID,
		arg.ID,
		arg.GroupName,
		arg.Source,
		arg.InputData,
		arg.GenerateCmd,
		arg.IsSample,
		arg.Points,
		arg.Description,
	)
	var i ProblemTest
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.TestIndex,
		&i.GroupName,
		&i.Source,
		&i.InputData,
		&i.GenerateCmd,
		&i.IsSample,
		&i.Points,
		&i.Description,
	)
	return i, err
}

const upsertProblemFile = `-- name: UpsertProblemFile :one
INSERT INTO problem_files
			   (problem_id, kind, name, language, source_code, expected_verdict, is_active)
			 VALUES ($1, $2, $3, $4, $5, $6, $7)
			 ON CONFLICT (problem_id, kind, name) DO UPDATE SET
			   language = EXCLUDED.language, source_code = EXCLUDED.source_code,
			   expected_verdict = EXCLUDED.expected_verdict,
			   is_active = EXCLUDED.is_active, updated_at = now()
			 RETURNING id, problem_id, kind, name, language, source_code,
	expected_verdict, is_active, created_at, updated_at
`

type UpsertProblemFileParams struct {
	ProblemID       string
	Kind            string
	Name            string
	Language        string
	SourceCode      string
	ExpectedVerdict string
	IsActive        bool
}

func (q *Queries) UpsertProblemFile(ctx context.Context, arg UpsertProblemFileParams) (ProblemFile, error) {
	row := q.db.QueryRowContext(ctx, upsertProblemFile,
		arg.ProblemID,
		arg.Kind,
		arg.Name,
		arg.Language,
		arg.SourceCode,
		arg.ExpectedVerdict,
		arg.IsActive,
	)
	var i ProblemFile
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Kind,
		&i.Name,
		&i.Language,
		&i.SourceCode,
		&i.ExpectedVerdict,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProblemStatement = `-- name: UpsertProblemStatement :one
INSERT INTO problem_statements
			   (problem_id, language, name, legend, input_format, output_format, notes, tutorial, scoring)
			 VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
			 ON CONFLICT (problem_id, language) DO UPDATE SET
			   name = EXCLUDED.name, legend = EXCLUDED.legend,
			   input_format = EXCLUDED.input_format, output_format = EXCLUDED.output_format,
			   notes = EXCLUDED.notes, tutorial = EXCLUDED.tutorial,
			   scoring = EXCLUDED.scoring, updated_at = now()
			 RETURNING problem_id, language, name, legend, input_format, output_format,
			           notes, tutorial, scoring, updated_at
`

type UpsertProblemStatementParams struct {
	ProblemID    string
	Language     string
	Name         string
	Legend       string
	InputFormat  string
	OutputFormat string
	Notes        string
	Tutorial     string
	Scoring      string
}

func (q *Queries) UpsertProblemStatement(ctx context.Context, arg UpsertProblemStatementParams) (ProblemStatement, error) {
	row := q.db.QueryRowContext(ctx, upsertProblemStatement,
		arg.ProblemID,
		arg.Language,
		arg.Name,
		arg.Legend,
		arg.InputFormat,
		arg.OutputFormat,
		arg.Notes,
		arg.Tutorial,
		arg.Scoring,
	)
	var i ProblemStatement
	err := row.Scan(
		&i.ProblemID,
		&i.Language,
		&i.Name,
		&i.Legend,
		&i.InputFormat,
		&i.OutputFormat,
		&i.Notes,
		&i.Tutorial,
		&i.Scoring,
		&i.UpdatedAt,
	)
	return i, err
}
