// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: package_read.sql

package dbgen

import (
	"context"
	"time"
)

const getPackageMetadata = `-- name: GetPackageMetadata :one
SELECT problem.id, problem.public_id, w.title, problem.visibility, w.judge_type,
		        w.statement_language, w.time_limit_ms, w.memory_limit_kb,
		        problem.package_revision, COALESCE(testdata.data_revision,0)::integer AS built_revision, problem.last_built_at,
		        COALESCE(testdata.case_count, 0), COALESCE(testdata.checker, ''),
		        COALESCE(testdata.data_version, 0), COALESCE(testdata.sha256, ''), problem.data_revision AS data_revision,
		        COALESCE(problem.published_version,0), COALESCE(v.workspace_revision,-1)::integer AS published_revision,COALESCE(v.artifact_version,0)::integer AS published_artifact_version
		 FROM problems AS problem
		 JOIN problem_workspaces w ON w.problem_id=problem.id
		 LEFT JOIN problem_testdata AS testdata ON testdata.problem_id = problem.id
		 LEFT JOIN problem_versions v ON v.problem_id=problem.id AND v.version_no=problem.published_version
		 WHERE problem.id = $1 AND problem.domain_id = $2
`

type GetPackageMetadataParams struct {
	ID       string
	DomainID string
}

type GetPackageMetadataRow struct {
	ID                       string
	PublicID                 string
	Title                    string
	Visibility               string
	JudgeType                string
	StatementLanguage        string
	TimeLimitMs              int
	MemoryLimitKb            int
	PackageRevision          int
	BuiltRevision            int
	LastBuiltAt              *time.Time
	CaseCount                int
	Checker                  string
	DataVersion              int
	Sha256                   string
	DataRevision             int
	PublishedVersion         int
	PublishedRevision        int
	PublishedArtifactVersion int
}

func (q *Queries) GetPackageMetadata(ctx context.Context, arg GetPackageMetadataParams) (GetPackageMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getPackageMetadata, arg.ID, arg.DomainID)
	var i GetPackageMetadataRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Visibility,
		&i.JudgeType,
		&i.StatementLanguage,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.PackageRevision,
		&i.BuiltRevision,
		&i.LastBuiltAt,
		&i.CaseCount,
		&i.Checker,
		&i.DataVersion,
		&i.Sha256,
		&i.DataRevision,
		&i.PublishedVersion,
		&i.PublishedRevision,
		&i.PublishedArtifactVersion,
	)
	return i, err
}

const getPackageSnapshotHeader = `-- name: GetPackageSnapshotHeader :one
SELECT p.id,w.title,w.time_limit_ms,w.memory_limit_kb,w.judge_type,p.package_revision,p.domain_id,p.data_revision
		 FROM problems p JOIN problem_workspaces w ON w.problem_id=p.id WHERE p.id=$1
`

type GetPackageSnapshotHeaderRow struct {
	ID              string
	Title           string
	TimeLimitMs     int
	MemoryLimitKb   int
	JudgeType       string
	PackageRevision int
	DomainID        string
	DataRevision    int
}

func (q *Queries) GetPackageSnapshotHeader(ctx context.Context, id string) (GetPackageSnapshotHeaderRow, error) {
	row := q.db.QueryRowContext(ctx, getPackageSnapshotHeader, id)
	var i GetPackageSnapshotHeaderRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.JudgeType,
		&i.PackageRevision,
		&i.DomainID,
		&i.DataRevision,
	)
	return i, err
}

const getProblemFile = `-- name: GetProblemFile :one
SELECT id, problem_id, kind, name, language, source_code,
	expected_verdict, is_active, created_at, updated_at FROM problem_files WHERE problem_files.problem_id = $1 AND problem_files.id = $2
		 AND EXISTS (SELECT 1 FROM problems WHERE problems.id = $1 AND domain_id = $3)
`

type GetProblemFileParams struct {
	ProblemID string
	ID        int64
	DomainID  string
}

func (q *Queries) GetProblemFile(ctx context.Context, arg GetProblemFileParams) (ProblemFile, error) {
	row := q.db.QueryRowContext(ctx, getProblemFile, arg.ProblemID, arg.ID, arg.DomainID)
	var i ProblemFile
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Kind,
		&i.Name,
		&i.Language,
		&i.SourceCode,
		&i.ExpectedVerdict,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProblemTest = `-- name: GetProblemTest :one
SELECT id, problem_id, test_index, group_name, source, input_data,
	generate_cmd, is_sample, points, description FROM problem_tests WHERE problem_tests.problem_id =$1 AND id=$2
`

type GetProblemTestParams struct {
	ProblemID string
	ID        int64
}

func (q *Queries) GetProblemTest(ctx context.Context, arg GetProblemTestParams) (ProblemTest, error) {
	row := q.db.QueryRowContext(ctx, getProblemTest, arg.ProblemID, arg.ID)
	var i ProblemTest
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.TestIndex,
		&i.GroupName,
		&i.Source,
		&i.InputData,
		&i.GenerateCmd,
		&i.IsSample,
		&i.Points,
		&i.Description,
	)
	return i, err
}

const listPackageFiles = `-- name: ListPackageFiles :many
SELECT id, problem_id, kind, name, language,
 CASE WHEN $1::boolean THEN source_code ELSE '' END::text AS source_code,
 expected_verdict, is_active, created_at, updated_at
FROM problem_files WHERE problem_id = $2::uuid
ORDER BY kind, is_active DESC, name
`

type ListPackageFilesParams struct {
	IncludeSource bool
	ProblemID     string
}

type ListPackageFilesRow struct {
	ID              int64
	ProblemID       string
	Kind            string
	Name            string
	Language        string
	SourceCode      string
	ExpectedVerdict string
	IsActive        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListPackageFiles(ctx context.Context, arg ListPackageFilesParams) ([]ListPackageFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPackageFiles, arg.IncludeSource, arg.ProblemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackageFilesRow{}
	for rows.Next() {
		var i ListPackageFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Kind,
			&i.Name,
			&i.Language,
			&i.SourceCode,
			&i.ExpectedVerdict,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageTests = `-- name: ListPackageTests :many
SELECT id, problem_id, test_index, group_name, source,
 CASE WHEN $1::boolean THEN input_data ELSE left(input_data,512) END::text AS input_data,
 generate_cmd, is_sample, points, description
FROM problem_tests WHERE problem_id = $2::uuid ORDER BY test_index
`

type ListPackageTestsParams struct {
	IncludeInput bool
	ProblemID    string
}

type ListPackageTestsRow struct {
	ID          int64
	ProblemID   string
	TestIndex   int
	GroupName   string
	Source      string
	InputData   string
	GenerateCmd string
	IsSample    bool
	Points      int
	Description string
}

func (q *Queries) ListPackageTests(ctx context.Context, arg ListPackageTestsParams) ([]ListPackageTestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPackageTests, arg.IncludeInput, arg.ProblemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackageTestsRow{}
	for rows.Next() {
		var i ListPackageTestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.TestIndex,
			&i.GroupName,
			&i.Source,
			&i.InputData,
			&i.GenerateCmd,
			&i.IsSample,
			&i.Points,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
