// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presentation.sql

package dbgen

import (
	"context"
)

const createPublishedFile = `-- name: CreatePublishedFile :exec
INSERT INTO problem_version_files(problem_id,version_no,file_id,path,filename,media_type,purpose,blob_sha256,byte_size,sample_index,preview,truncated,is_binary,embedded)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
`

type CreatePublishedFileParams struct {
	ProblemID   string
	VersionNo   int
	FileID      string
	Path        string
	Filename    string
	MediaType   string
	Purpose     string
	BlobSha256  string
	ByteSize    int64
	SampleIndex int
	Preview     string
	Truncated   bool
	IsBinary    bool
	Embedded    bool
}

func (q *Queries) CreatePublishedFile(ctx context.Context, arg CreatePublishedFileParams) error {
	_, err := q.db.ExecContext(ctx, createPublishedFile,
		arg.ProblemID,
		arg.VersionNo,
		arg.FileID,
		arg.Path,
		arg.Filename,
		arg.MediaType,
		arg.Purpose,
		arg.BlobSha256,
		arg.ByteSize,
		arg.SampleIndex,
		arg.Preview,
		arg.Truncated,
		arg.IsBinary,
		arg.Embedded,
	)
	return err
}
