// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: release.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createProblemRelease = `-- name: CreateProblemRelease :one
INSERT INTO problem_versions
	 (problem_id,version_no,workspace_revision,data_revision,artifact_version,title,statement_md,difficulty,source,time_limit_ms,memory_limit_kb,judge_type,statement_language,tags_json,statements_json,package_json,config_json,testdata_path,sha256,case_count,checker,spj_source,created_by,files_json,samples_json)
	 VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25) RETURNING version_no,workspace_revision,artifact_version,statement_language,sha256,case_count,created_at
`

type CreateProblemReleaseParams struct {
	ProblemID         string
	VersionNo         int
	WorkspaceRevision int
	DataRevision      int
	ArtifactVersion   int
	Title             string
	StatementMd       string
	Difficulty        int
	Source            string
	TimeLimitMs       int
	MemoryLimitKb     int
	JudgeType         string
	StatementLanguage string
	TagsJson          json.RawMessage
	StatementsJson    json.RawMessage
	PackageJson       json.RawMessage
	ConfigJson        json.RawMessage
	TestdataPath      string
	Sha256            string
	CaseCount         int
	Checker           string
	SpjSource         string
	CreatedBy         *string
	FilesJson         json.RawMessage
	SamplesJson       json.RawMessage
}

type CreateProblemReleaseRow struct {
	VersionNo         int
	WorkspaceRevision int
	ArtifactVersion   int
	StatementLanguage string
	Sha256            string
	CaseCount         int
	CreatedAt         time.Time
}

func (q *Queries) CreateProblemRelease(ctx context.Context, arg CreateProblemReleaseParams) (CreateProblemReleaseRow, error) {
	row := q.db.QueryRowContext(ctx, createProblemRelease,
		arg.ProblemID,
		arg.VersionNo,
		arg.WorkspaceRevision,
		arg.DataRevision,
		arg.ArtifactVersion,
		arg.Title,
		arg.StatementMd,
		arg.Difficulty,
		arg.Source,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.JudgeType,
		arg.StatementLanguage,
		arg.TagsJson,
		arg.StatementsJson,
		arg.PackageJson,
		arg.ConfigJson,
		arg.TestdataPath,
		arg.Sha256,
		arg.CaseCount,
		arg.Checker,
		arg.SpjSource,
		arg.CreatedBy,
		arg.FilesJson,
		arg.SamplesJson,
	)
	var i CreateProblemReleaseRow
	err := row.Scan(
		&i.VersionNo,
		&i.WorkspaceRevision,
		&i.ArtifactVersion,
		&i.StatementLanguage,
		&i.Sha256,
		&i.CaseCount,
		&i.CreatedAt,
	)
	return i, err
}

const deletePublishedProblemTags = `-- name: DeletePublishedProblemTags :exec
DELETE FROM problem_tags WHERE problem_id=$1
`

func (q *Queries) DeletePublishedProblemTags(ctx context.Context, problemID string) error {
	_, err := q.db.ExecContext(ctx, deletePublishedProblemTags, problemID)
	return err
}

const ensurePublishedTags = `-- name: EnsurePublishedTags :exec
INSERT INTO tags(domain_id,name) SELECT $1,value FROM jsonb_array_elements_text($2::jsonb) WHERE value<>'' ON CONFLICT(domain_id,name) DO NOTHING
`

type EnsurePublishedTagsParams struct {
	DomainID string
	TagsJson json.RawMessage
}

func (q *Queries) EnsurePublishedTags(ctx context.Context, arg EnsurePublishedTagsParams) error {
	_, err := q.db.ExecContext(ctx, ensurePublishedTags, arg.DomainID, arg.TagsJson)
	return err
}

const getProblemRelease = `-- name: GetProblemRelease :one
SELECT version_no,workspace_revision,artifact_version,statement_language,sha256,case_count,created_at FROM problem_versions WHERE problem_id=$1 AND version_no=$2
`

type GetProblemReleaseParams struct {
	ProblemID string
	VersionNo int
}

type GetProblemReleaseRow struct {
	VersionNo         int
	WorkspaceRevision int
	ArtifactVersion   int
	StatementLanguage string
	Sha256            string
	CaseCount         int
	CreatedAt         time.Time
}

func (q *Queries) GetProblemRelease(ctx context.Context, arg GetProblemReleaseParams) (GetProblemReleaseRow, error) {
	row := q.db.QueryRowContext(ctx, getProblemRelease, arg.ProblemID, arg.VersionNo)
	var i GetProblemReleaseRow
	err := row.Scan(
		&i.VersionNo,
		&i.WorkspaceRevision,
		&i.ArtifactVersion,
		&i.StatementLanguage,
		&i.Sha256,
		&i.CaseCount,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicationTestdata = `-- name: GetPublicationTestdata :one
SELECT data_version,data_revision,storage_path,sha256,case_count,checker,spj_source,config_json,samples_json
	 FROM problem_testdata WHERE problem_id=$1
`

type GetPublicationTestdataRow struct {
	DataVersion  int
	DataRevision int
	StoragePath  string
	Sha256       string
	CaseCount    int
	Checker      string
	SpjSource    string
	ConfigJson   json.RawMessage
	SamplesJson  json.RawMessage
}

func (q *Queries) GetPublicationTestdata(ctx context.Context, problemID string) (GetPublicationTestdataRow, error) {
	row := q.db.QueryRowContext(ctx, getPublicationTestdata, problemID)
	var i GetPublicationTestdataRow
	err := row.Scan(
		&i.DataVersion,
		&i.DataRevision,
		&i.StoragePath,
		&i.Sha256,
		&i.CaseCount,
		&i.Checker,
		&i.SpjSource,
		&i.ConfigJson,
		&i.SamplesJson,
	)
	return i, err
}

const getPublicationWorkspace = `-- name: GetPublicationWorkspace :one
SELECT p.package_revision,p.data_revision,COALESCE(p.published_version,0),w.title,w.statement_md,w.difficulty,w.source,w.time_limit_ms,w.memory_limit_kb,w.judge_type,w.statement_language,w.tags_json
	 FROM problems p JOIN problem_workspaces w ON w.problem_id=p.id WHERE p.id=$1
`

type GetPublicationWorkspaceRow struct {
	PackageRevision   int
	DataRevision      int
	PublishedVersion  int
	Title             string
	StatementMd       string
	Difficulty        int
	Source            string
	TimeLimitMs       int
	MemoryLimitKb     int
	JudgeType         string
	StatementLanguage string
	TagsJson          json.RawMessage
}

func (q *Queries) GetPublicationWorkspace(ctx context.Context, id string) (GetPublicationWorkspaceRow, error) {
	row := q.db.QueryRowContext(ctx, getPublicationWorkspace, id)
	var i GetPublicationWorkspaceRow
	err := row.Scan(
		&i.PackageRevision,
		&i.DataRevision,
		&i.PublishedVersion,
		&i.Title,
		&i.StatementMd,
		&i.Difficulty,
		&i.Source,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.JudgeType,
		&i.StatementLanguage,
		&i.TagsJson,
	)
	return i, err
}

const insertPublishedProblemTags = `-- name: InsertPublishedProblemTags :exec
INSERT INTO problem_tags(domain_id,problem_id,tag_id) SELECT $1,$2,t.id FROM tags t WHERE t.domain_id=$1 AND t.name IN (SELECT value FROM jsonb_array_elements_text($3::jsonb))
`

type InsertPublishedProblemTagsParams struct {
	DomainID  string
	ProblemID string
	TagsJson  json.RawMessage
}

func (q *Queries) InsertPublishedProblemTags(ctx context.Context, arg InsertPublishedProblemTagsParams) error {
	_, err := q.db.ExecContext(ctx, insertPublishedProblemTags, arg.DomainID, arg.ProblemID, arg.TagsJson)
	return err
}

const listProblemReleases = `-- name: ListProblemReleases :many
SELECT version_no,workspace_revision,artifact_version,statement_language,sha256,case_count,created_at FROM problem_versions WHERE problem_id=$1 ORDER BY version_no DESC LIMIT 100
`

type ListProblemReleasesRow struct {
	VersionNo         int
	WorkspaceRevision int
	ArtifactVersion   int
	StatementLanguage string
	Sha256            string
	CaseCount         int
	CreatedAt         time.Time
}

func (q *Queries) ListProblemReleases(ctx context.Context, problemID string) ([]ListProblemReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProblemReleases, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProblemReleasesRow{}
	for rows.Next() {
		var i ListProblemReleasesRow
		if err := rows.Scan(
			&i.VersionNo,
			&i.WorkspaceRevision,
			&i.ArtifactVersion,
			&i.StatementLanguage,
			&i.Sha256,
			&i.CaseCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextProblemVersion = `-- name: NextProblemVersion :one
SELECT (COALESCE(max(version_no),0)+1)::integer FROM problem_versions WHERE problem_id=$1
`

func (q *Queries) NextProblemVersion(ctx context.Context, problemID string) (int, error) {
	row := q.db.QueryRowContext(ctx, nextProblemVersion, problemID)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const publishProblem = `-- name: PublishProblem :exec
UPDATE problems SET title=$2,statement_md=$3,difficulty=$4,source=$5,time_limit_ms=$6,memory_limit_kb=$7,judge_type=$8,statement_language=$9,published_version=$10,updated_at=now() WHERE id=$1
`

type PublishProblemParams struct {
	ID                string
	Title             string
	StatementMd       string
	Difficulty        int
	Source            string
	TimeLimitMs       int
	MemoryLimitKb     int
	JudgeType         string
	StatementLanguage string
	PublishedVersion  sql.NullInt32
}

func (q *Queries) PublishProblem(ctx context.Context, arg PublishProblemParams) error {
	_, err := q.db.ExecContext(ctx, publishProblem,
		arg.ID,
		arg.Title,
		arg.StatementMd,
		arg.Difficulty,
		arg.Source,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.JudgeType,
		arg.StatementLanguage,
		arg.PublishedVersion,
	)
	return err
}

const recordProblemPublication = `-- name: RecordProblemPublication :exec
INSERT INTO domain_audit_events(domain_id,actor_id,action,target) VALUES($1,$2,'problem.publish',$3)
`

type RecordProblemPublicationParams struct {
	DomainID string
	ActorID  *string
	Target   string
}

func (q *Queries) RecordProblemPublication(ctx context.Context, arg RecordProblemPublicationParams) error {
	_, err := q.db.ExecContext(ctx, recordProblemPublication, arg.DomainID, arg.ActorID, arg.Target)
	return err
}

const snapshotProblemFiles = `-- name: SnapshotProblemFiles :one
SELECT COALESCE(jsonb_agg(to_jsonb(f) ORDER BY kind,name),'[]'::jsonb)::jsonb FROM problem_files f WHERE problem_id=$1
`

func (q *Queries) SnapshotProblemFiles(ctx context.Context, problemID string) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, snapshotProblemFiles, problemID)
	var column_1 json.RawMessage
	err := row.Scan(&column_1)
	return column_1, err
}

const snapshotProblemStatements = `-- name: SnapshotProblemStatements :one
SELECT COALESCE(jsonb_agg(to_jsonb(s) ORDER BY language),'[]'::jsonb)::jsonb FROM problem_statements s WHERE problem_id=$1
`

func (q *Queries) SnapshotProblemStatements(ctx context.Context, problemID string) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, snapshotProblemStatements, problemID)
	var column_1 json.RawMessage
	err := row.Scan(&column_1)
	return column_1, err
}
