// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: release.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const deletePublishedProblemTags = `-- name: DeletePublishedProblemTags :exec
DELETE FROM problem_tags WHERE problem_id=$1
`

func (q *Queries) DeletePublishedProblemTags(ctx context.Context, problemID string) error {
	_, err := q.db.ExecContext(ctx, deletePublishedProblemTags, problemID)
	return err
}

const ensurePublishedTags = `-- name: EnsurePublishedTags :exec
INSERT INTO tags(domain_id,name) SELECT $1,value FROM jsonb_array_elements_text($2::jsonb) WHERE value<>'' ON CONFLICT(domain_id,name) DO NOTHING
`

type EnsurePublishedTagsParams struct {
	DomainID string
	TagsJson json.RawMessage
}

func (q *Queries) EnsurePublishedTags(ctx context.Context, arg EnsurePublishedTagsParams) error {
	_, err := q.db.ExecContext(ctx, ensurePublishedTags, arg.DomainID, arg.TagsJson)
	return err
}

const insertPublishedProblemTags = `-- name: InsertPublishedProblemTags :exec
INSERT INTO problem_tags(domain_id,problem_id,tag_id) SELECT $1,$2,t.id FROM tags t WHERE t.domain_id=$1 AND t.name IN (SELECT value FROM jsonb_array_elements_text($3::jsonb))
`

type InsertPublishedProblemTagsParams struct {
	DomainID  string
	ProblemID string
	TagsJson  json.RawMessage
}

func (q *Queries) InsertPublishedProblemTags(ctx context.Context, arg InsertPublishedProblemTagsParams) error {
	_, err := q.db.ExecContext(ctx, insertPublishedProblemTags, arg.DomainID, arg.ProblemID, arg.TagsJson)
	return err
}

const nextProblemVersion = `-- name: NextProblemVersion :one
SELECT (COALESCE(max(version_no),0)+1)::integer FROM problem_versions WHERE problem_id=$1
`

func (q *Queries) NextProblemVersion(ctx context.Context, problemID string) (int, error) {
	row := q.db.QueryRowContext(ctx, nextProblemVersion, problemID)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const publishProblem = `-- name: PublishProblem :exec
UPDATE problems SET title=$2,statement_md=$3,difficulty=$4,source=$5,time_limit_ms=$6,memory_limit_kb=$7,judge_type=$8,statement_language=$9,published_version=$10,updated_at=now() WHERE id=$1
`

type PublishProblemParams struct {
	ID                string
	Title             string
	StatementMd       string
	Difficulty        int
	Source            string
	TimeLimitMs       int
	MemoryLimitKb     int
	JudgeType         string
	StatementLanguage string
	PublishedVersion  sql.NullInt32
}

func (q *Queries) PublishProblem(ctx context.Context, arg PublishProblemParams) error {
	_, err := q.db.ExecContext(ctx, publishProblem,
		arg.ID,
		arg.Title,
		arg.StatementMd,
		arg.Difficulty,
		arg.Source,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.JudgeType,
		arg.StatementLanguage,
		arg.PublishedVersion,
	)
	return err
}

const recordProblemPublication = `-- name: RecordProblemPublication :exec
INSERT INTO domain_audit_events(domain_id,actor_id,action,target) VALUES($1,$2,'problem.publish',$3)
`

type RecordProblemPublicationParams struct {
	DomainID string
	ActorID  *string
	Target   string
}

func (q *Queries) RecordProblemPublication(ctx context.Context, arg RecordProblemPublicationParams) error {
	_, err := q.db.ExecContext(ctx, recordProblemPublication, arg.DomainID, arg.ActorID, arg.Target)
	return err
}
