// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replica.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createCopiedCheck = `-- name: CreateCopiedCheck :one
INSERT INTO problem_build_jobs(problem_id,input_json,source_tree_hash,data_hash,check_policy,toolchain_key,state,stage,
progress_done,progress_total,log,tests_json,solutions_json,validation_json,package_path,package_sha256,package_cases,package_manifest,created_by,finished_at)
VALUES($1,$2,$3,$4,$5,$6,'succeeded','copied',
$7,$7,$8,$9,'[]',$10,$11,$12,$7,$13,$14,now()) RETURNING id
`

type CreateCopiedCheckParams struct {
	ProblemID       string
	InputJson       json.RawMessage
	TreeHash        string
	DataHash        string
	CheckPolicy     string
	ToolchainKey    string
	CaseCount       int
	Log             string
	TestsJson       json.RawMessage
	ValidationJson  json.RawMessage
	PackagePath     string
	PackageSha256   string
	PackageManifest json.RawMessage
	ActorID         *string
}

func (q *Queries) CreateCopiedCheck(ctx context.Context, arg CreateCopiedCheckParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createCopiedCheck,
		arg.ProblemID,
		arg.InputJson,
		arg.TreeHash,
		arg.DataHash,
		arg.CheckPolicy,
		arg.ToolchainKey,
		arg.CaseCount,
		arg.Log,
		arg.TestsJson,
		arg.ValidationJson,
		arg.PackagePath,
		arg.PackageSha256,
		arg.PackageManifest,
		arg.ActorID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createRevisionCopy = `-- name: CreateRevisionCopy :one
INSERT INTO problems(domain_id,owner_id,author_id,title,statement_md,difficulty,source,time_limit_ms,memory_limit_kb,judge_type,statement_language,visibility)
SELECT $1,$2,$2,title,statement_md,difficulty,source,time_limit_ms,memory_limit_kb,judge_type,statement_language,'private'
FROM problem_versions WHERE problem_versions.id=$3 RETURNING id,public_id
`

type CreateRevisionCopyParams struct {
	DomainID string
	OwnerID  string
	ID       int64
}

type CreateRevisionCopyRow struct {
	ID       string
	PublicID string
}

func (q *Queries) CreateRevisionCopy(ctx context.Context, arg CreateRevisionCopyParams) (CreateRevisionCopyRow, error) {
	row := q.db.QueryRowContext(ctx, createRevisionCopy, arg.DomainID, arg.OwnerID, arg.ID)
	var i CreateRevisionCopyRow
	err := row.Scan(&i.ID, &i.PublicID)
	return i, err
}

const readCopyRelease = `-- name: ReadCopyRelease :one
SELECT v.id,v.title,v.source_revision,v.source_tree_hash,v.testdata_path,v.sha256,v.case_count,v.config_json,
v.toolchain_key,b.data_hash,b.check_policy
FROM problem_versions v JOIN problem_build_jobs b ON b.id=v.check_id AND b.problem_id=v.problem_id
WHERE v.problem_id=$1 AND v.version_no=$2 AND v.source_revision IS NOT NULL AND v.source_tree_hash IS NOT NULL AND b.state='succeeded' AND v.checker='artifact'
`

type ReadCopyReleaseParams struct {
	ProblemID string
	VersionNo int
}

type ReadCopyReleaseRow struct {
	ID             int64
	Title          string
	SourceRevision sql.NullInt64
	SourceTreeHash sql.NullString
	TestdataPath   string
	Sha256         string
	CaseCount      int
	ConfigJson     json.RawMessage
	ToolchainKey   string
	DataHash       string
	CheckPolicy    string
}

func (q *Queries) ReadCopyRelease(ctx context.Context, arg ReadCopyReleaseParams) (ReadCopyReleaseRow, error) {
	row := q.db.QueryRowContext(ctx, readCopyRelease, arg.ProblemID, arg.VersionNo)
	var i ReadCopyReleaseRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SourceRevision,
		&i.SourceTreeHash,
		&i.TestdataPath,
		&i.Sha256,
		&i.CaseCount,
		&i.ConfigJson,
		&i.ToolchainKey,
		&i.DataHash,
		&i.CheckPolicy,
	)
	return i, err
}
