// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revisions.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const advanceAuthoringHead = `-- name: AdvanceAuthoringHead :exec
UPDATE problem_authoring_heads SET revision=$2,tree_hash=$3 WHERE problem_id=$1
`

type AdvanceAuthoringHeadParams struct {
	ProblemID string
	Revision  sql.NullInt64
	TreeHash  string
}

func (q *Queries) AdvanceAuthoringHead(ctx context.Context, arg AdvanceAuthoringHeadParams) error {
	_, err := q.db.ExecContext(ctx, advanceAuthoringHead, arg.ProblemID, arg.Revision, arg.TreeHash)
	return err
}

const availableAuthoringBlobs = `-- name: AvailableAuthoringBlobs :many
SELECT b.sha256,b.byte_size FROM problem_blobs b
WHERE b.problem_id=$1 AND b.sha256=ANY($2::text[])
AND (
    EXISTS(SELECT 1 FROM problem_blob_uploads u WHERE u.problem_id=b.problem_id AND u.sha256=b.sha256 AND u.actor_id=$3)
    OR EXISTS(SELECT 1 FROM problem_tree_blobs tb JOIN problem_commits c USING(problem_id,tree_hash) WHERE tb.problem_id=b.problem_id AND tb.sha256=b.sha256)
    OR EXISTS(SELECT 1 FROM problem_tree_blobs tb JOIN problem_working_copies w USING(problem_id,tree_hash) WHERE tb.problem_id=b.problem_id AND tb.sha256=b.sha256 AND w.actor_id=$3)
    OR EXISTS(SELECT 1 FROM problem_tree_blobs tb JOIN problem_build_jobs j ON j.problem_id=tb.problem_id AND j.source_tree_hash=tb.tree_hash WHERE tb.problem_id=b.problem_id AND tb.sha256=b.sha256 AND j.created_by=$3)
    OR EXISTS(SELECT 1 FROM problem_merge_sessions m, jsonb_array_elements(CASE WHEN jsonb_typeof(m.result_json#>'{tree,entries}')='array' THEN m.result_json#>'{tree,entries}' ELSE '[]'::jsonb END) e WHERE m.problem_id=b.problem_id AND m.actor_id=$3 AND e#>>'{blob,sha256}'=b.sha256)
)
`

type AvailableAuthoringBlobsParams struct {
	ProblemID string
	Digests   []string
	ActorID   string
}

type AvailableAuthoringBlobsRow struct {
	Sha256   string
	ByteSize int64
}

func (q *Queries) AvailableAuthoringBlobs(ctx context.Context, arg AvailableAuthoringBlobsParams) ([]AvailableAuthoringBlobsRow, error) {
	rows, err := q.db.QueryContext(ctx, availableAuthoringBlobs, arg.ProblemID, pq.Array(arg.Digests), arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailableAuthoringBlobsRow{}
	for rows.Next() {
		var i AvailableAuthoringBlobsRow
		if err := rows.Scan(&i.Sha256, &i.ByteSize); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMergeSession = `-- name: DeleteMergeSession :exec
DELETE FROM problem_merge_sessions WHERE problem_id=$1 AND actor_id=$2
`

type DeleteMergeSessionParams struct {
	ProblemID string
	ActorID   string
}

func (q *Queries) DeleteMergeSession(ctx context.Context, arg DeleteMergeSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteMergeSession, arg.ProblemID, arg.ActorID)
	return err
}

const findContentCommitRequest = `-- name: FindContentCommitRequest :one
SELECT problem_id, revision, parent_revision, tree_hash, author_id, message, request_id, request_etag, created_at FROM problem_commits WHERE problem_id=$1 AND author_id=$2 AND request_id=$3
`

type FindContentCommitRequestParams struct {
	ProblemID string
	ActorID   *string
	RequestID string
}

func (q *Queries) FindContentCommitRequest(ctx context.Context, arg FindContentCommitRequestParams) (ProblemCommit, error) {
	row := q.db.QueryRowContext(ctx, findContentCommitRequest, arg.ProblemID, arg.ActorID, arg.RequestID)
	var i ProblemCommit
	err := row.Scan(
		&i.ProblemID,
		&i.Revision,
		&i.ParentRevision,
		&i.TreeHash,
		&i.AuthorID,
		&i.Message,
		&i.RequestID,
		&i.RequestEtag,
		&i.CreatedAt,
	)
	return i, err
}

const grantAuthoringBlobUpload = `-- name: GrantAuthoringBlobUpload :exec
INSERT INTO problem_blob_uploads(problem_id,sha256,actor_id) VALUES($1,$2,$3)
ON CONFLICT(problem_id,sha256,actor_id) DO UPDATE SET created_at=now()
`

type GrantAuthoringBlobUploadParams struct {
	ProblemID string
	Sha256    string
	ActorID   string
}

func (q *Queries) GrantAuthoringBlobUpload(ctx context.Context, arg GrantAuthoringBlobUploadParams) error {
	_, err := q.db.ExecContext(ctx, grantAuthoringBlobUpload, arg.ProblemID, arg.Sha256, arg.ActorID)
	return err
}

const initialProblemMaterial = `-- name: InitialProblemMaterial :one
SELECT title,statement_md,statement_language,source,judge_type,time_limit_ms,memory_limit_kb,difficulty FROM problems WHERE id=$1
`

type InitialProblemMaterialRow struct {
	Title             string
	StatementMd       string
	StatementLanguage string
	Source            string
	JudgeType         string
	TimeLimitMs       int
	MemoryLimitKb     int
	Difficulty        int
}

func (q *Queries) InitialProblemMaterial(ctx context.Context, id string) (InitialProblemMaterialRow, error) {
	row := q.db.QueryRowContext(ctx, initialProblemMaterial, id)
	var i InitialProblemMaterialRow
	err := row.Scan(
		&i.Title,
		&i.StatementMd,
		&i.StatementLanguage,
		&i.Source,
		&i.JudgeType,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.Difficulty,
	)
	return i, err
}

const initializeAuthoringHead = `-- name: InitializeAuthoringHead :exec
INSERT INTO problem_authoring_heads(problem_id,tree_hash,initial_tree_hash)
VALUES($1,$2,$2) ON CONFLICT DO NOTHING
`

type InitializeAuthoringHeadParams struct {
	ProblemID string
	TreeHash  string
}

func (q *Queries) InitializeAuthoringHead(ctx context.Context, arg InitializeAuthoringHeadParams) error {
	_, err := q.db.ExecContext(ctx, initializeAuthoringHead, arg.ProblemID, arg.TreeHash)
	return err
}

const insertAuthoringTree = `-- name: InsertAuthoringTree :exec
INSERT INTO problem_content_trees(problem_id,tree_hash,manifest,summary) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING
`

type InsertAuthoringTreeParams struct {
	ProblemID string
	TreeHash  string
	Manifest  json.RawMessage
	Summary   json.RawMessage
}

func (q *Queries) InsertAuthoringTree(ctx context.Context, arg InsertAuthoringTreeParams) error {
	_, err := q.db.ExecContext(ctx, insertAuthoringTree,
		arg.ProblemID,
		arg.TreeHash,
		arg.Manifest,
		arg.Summary,
	)
	return err
}

const insertAuthoringTreeBlobs = `-- name: InsertAuthoringTreeBlobs :exec
INSERT INTO problem_tree_blobs(problem_id,tree_hash,sha256)
SELECT $1::uuid,$2::text,unnest($3::text[])
ON CONFLICT DO NOTHING
`

type InsertAuthoringTreeBlobsParams struct {
	ProblemID string
	TreeHash  string
	Digests   []string
}

func (q *Queries) InsertAuthoringTreeBlobs(ctx context.Context, arg InsertAuthoringTreeBlobsParams) error {
	_, err := q.db.ExecContext(ctx, insertAuthoringTreeBlobs, arg.ProblemID, arg.TreeHash, pq.Array(arg.Digests))
	return err
}

const insertContentCommit = `-- name: InsertContentCommit :one
INSERT INTO problem_commits(problem_id,revision,parent_revision,tree_hash,author_id,message,request_id,request_etag)
VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING problem_id, revision, parent_revision, tree_hash, author_id, message, request_id, request_etag, created_at
`

type InsertContentCommitParams struct {
	ProblemID      string
	Revision       int64
	ParentRevision sql.NullInt64
	TreeHash       string
	AuthorID       *string
	Message        string
	RequestID      string
	RequestEtag    string
}

func (q *Queries) InsertContentCommit(ctx context.Context, arg InsertContentCommitParams) (ProblemCommit, error) {
	row := q.db.QueryRowContext(ctx, insertContentCommit,
		arg.ProblemID,
		arg.Revision,
		arg.ParentRevision,
		arg.TreeHash,
		arg.AuthorID,
		arg.Message,
		arg.RequestID,
		arg.RequestEtag,
	)
	var i ProblemCommit
	err := row.Scan(
		&i.ProblemID,
		&i.Revision,
		&i.ParentRevision,
		&i.TreeHash,
		&i.AuthorID,
		&i.Message,
		&i.RequestID,
		&i.RequestEtag,
		&i.CreatedAt,
	)
	return i, err
}

const listContentCommits = `-- name: ListContentCommits :many
SELECT problem_id, revision, parent_revision, tree_hash, author_id, message, request_id, request_etag, created_at FROM problem_commits WHERE problem_id=$1
AND ($2::bigint=0 OR revision<$2)
ORDER BY revision DESC LIMIT $3::integer
`

type ListContentCommitsParams struct {
	ProblemID      string
	BeforeRevision int64
	PageLimit      int
}

func (q *Queries) ListContentCommits(ctx context.Context, arg ListContentCommitsParams) ([]ProblemCommit, error) {
	rows, err := q.db.QueryContext(ctx, listContentCommits, arg.ProblemID, arg.BeforeRevision, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProblemCommit{}
	for rows.Next() {
		var i ProblemCommit
		if err := rows.Scan(
			&i.ProblemID,
			&i.Revision,
			&i.ParentRevision,
			&i.TreeHash,
			&i.AuthorID,
			&i.Message,
			&i.RequestID,
			&i.RequestEtag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readAuthoringBlob = `-- name: ReadAuthoringBlob :one
SELECT b.sha256,b.byte_size FROM problem_blobs b
WHERE b.problem_id=$1 AND b.sha256=$2
AND (
    EXISTS(SELECT 1 FROM problem_blob_uploads u WHERE u.problem_id=b.problem_id AND u.sha256=b.sha256 AND u.actor_id=$3)
    OR EXISTS(SELECT 1 FROM problem_version_files f WHERE f.problem_id=b.problem_id AND f.blob_sha256=b.sha256)
    OR EXISTS(SELECT 1 FROM problem_tree_blobs tb JOIN problem_commits c USING(problem_id,tree_hash) WHERE tb.problem_id=b.problem_id AND tb.sha256=b.sha256)
    OR EXISTS(SELECT 1 FROM problem_tree_blobs tb JOIN problem_working_copies w USING(problem_id,tree_hash) WHERE tb.problem_id=b.problem_id AND tb.sha256=b.sha256 AND w.actor_id=$3)
    OR EXISTS(SELECT 1 FROM problem_tree_blobs tb JOIN problem_build_jobs j ON j.problem_id=tb.problem_id AND j.source_tree_hash=tb.tree_hash WHERE tb.problem_id=b.problem_id AND tb.sha256=b.sha256 AND j.created_by=$3)
    OR EXISTS(SELECT 1 FROM problem_merge_sessions m, jsonb_array_elements(CASE WHEN jsonb_typeof(m.result_json#>'{tree,entries}')='array' THEN m.result_json#>'{tree,entries}' ELSE '[]'::jsonb END) e WHERE m.problem_id=b.problem_id AND m.actor_id=$3 AND e#>>'{blob,sha256}'=b.sha256)
)
`

type ReadAuthoringBlobParams struct {
	ProblemID string
	Sha256    string
	ActorID   string
}

type ReadAuthoringBlobRow struct {
	Sha256   string
	ByteSize int64
}

func (q *Queries) ReadAuthoringBlob(ctx context.Context, arg ReadAuthoringBlobParams) (ReadAuthoringBlobRow, error) {
	row := q.db.QueryRowContext(ctx, readAuthoringBlob, arg.ProblemID, arg.Sha256, arg.ActorID)
	var i ReadAuthoringBlobRow
	err := row.Scan(&i.Sha256, &i.ByteSize)
	return i, err
}

const readAuthoringHead = `-- name: ReadAuthoringHead :one
SELECT revision,tree_hash FROM problem_authoring_heads WHERE problem_id=$1
`

type ReadAuthoringHeadRow struct {
	Revision sql.NullInt64
	TreeHash string
}

func (q *Queries) ReadAuthoringHead(ctx context.Context, problemID string) (ReadAuthoringHeadRow, error) {
	row := q.db.QueryRowContext(ctx, readAuthoringHead, problemID)
	var i ReadAuthoringHeadRow
	err := row.Scan(&i.Revision, &i.TreeHash)
	return i, err
}

const readAuthoringTree = `-- name: ReadAuthoringTree :one
SELECT manifest FROM problem_content_trees WHERE problem_id=$1 AND tree_hash=$2
`

type ReadAuthoringTreeParams struct {
	ProblemID string
	TreeHash  string
}

func (q *Queries) ReadAuthoringTree(ctx context.Context, arg ReadAuthoringTreeParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, readAuthoringTree, arg.ProblemID, arg.TreeHash)
	var manifest json.RawMessage
	err := row.Scan(&manifest)
	return manifest, err
}

const readContentCommit = `-- name: ReadContentCommit :one
SELECT problem_id, revision, parent_revision, tree_hash, author_id, message, request_id, request_etag, created_at FROM problem_commits WHERE problem_id=$1 AND revision=$2
`

type ReadContentCommitParams struct {
	ProblemID string
	Revision  int64
}

func (q *Queries) ReadContentCommit(ctx context.Context, arg ReadContentCommitParams) (ProblemCommit, error) {
	row := q.db.QueryRowContext(ctx, readContentCommit, arg.ProblemID, arg.Revision)
	var i ProblemCommit
	err := row.Scan(
		&i.ProblemID,
		&i.Revision,
		&i.ParentRevision,
		&i.TreeHash,
		&i.AuthorID,
		&i.Message,
		&i.RequestID,
		&i.RequestEtag,
		&i.CreatedAt,
	)
	return i, err
}

const readInitialAuthoringTree = `-- name: ReadInitialAuthoringTree :one
SELECT initial_tree_hash FROM problem_authoring_heads WHERE problem_id=$1
`

func (q *Queries) ReadInitialAuthoringTree(ctx context.Context, problemID string) (string, error) {
	row := q.db.QueryRowContext(ctx, readInitialAuthoringTree, problemID)
	var initial_tree_hash string
	err := row.Scan(&initial_tree_hash)
	return initial_tree_hash, err
}

const readMergeSession = `-- name: ReadMergeSession :one
SELECT id, problem_id, actor_id, etag, copy_etag, base_revision, remote_revision, local_tree, remote_tree, result_json, updated_at FROM problem_merge_sessions WHERE problem_id=$1 AND actor_id=$2
`

type ReadMergeSessionParams struct {
	ProblemID string
	ActorID   string
}

func (q *Queries) ReadMergeSession(ctx context.Context, arg ReadMergeSessionParams) (ProblemMergeSession, error) {
	row := q.db.QueryRowContext(ctx, readMergeSession, arg.ProblemID, arg.ActorID)
	var i ProblemMergeSession
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.ActorID,
		&i.Etag,
		&i.CopyEtag,
		&i.BaseRevision,
		&i.RemoteRevision,
		&i.LocalTree,
		&i.RemoteTree,
		&i.ResultJson,
		&i.UpdatedAt,
	)
	return i, err
}

const readWorkingCopy = `-- name: ReadWorkingCopy :one
SELECT w.base_revision,w.tree_hash,w.etag,w.updated_at,h.revision AS head_revision,
       COALESCE(m.id::text,'')::text AS merge_id
FROM problem_working_copies w JOIN problem_authoring_heads h USING(problem_id)
LEFT JOIN problem_merge_sessions m ON m.problem_id=w.problem_id AND m.actor_id=w.actor_id
WHERE w.problem_id=$1 AND w.actor_id=$2
`

type ReadWorkingCopyParams struct {
	ProblemID string
	ActorID   string
}

type ReadWorkingCopyRow struct {
	BaseRevision sql.NullInt64
	TreeHash     string
	Etag         string
	UpdatedAt    time.Time
	HeadRevision sql.NullInt64
	MergeID      string
}

func (q *Queries) ReadWorkingCopy(ctx context.Context, arg ReadWorkingCopyParams) (ReadWorkingCopyRow, error) {
	row := q.db.QueryRowContext(ctx, readWorkingCopy, arg.ProblemID, arg.ActorID)
	var i ReadWorkingCopyRow
	err := row.Scan(
		&i.BaseRevision,
		&i.TreeHash,
		&i.Etag,
		&i.UpdatedAt,
		&i.HeadRevision,
		&i.MergeID,
	)
	return i, err
}

const registerAuthoringBlob = `-- name: RegisterAuthoringBlob :exec
INSERT INTO problem_blobs(problem_id,sha256,byte_size) VALUES($1,$2,$3) ON CONFLICT DO NOTHING
`

type RegisterAuthoringBlobParams struct {
	ProblemID string
	Sha256    string
	ByteSize  int64
}

func (q *Queries) RegisterAuthoringBlob(ctx context.Context, arg RegisterAuthoringBlobParams) error {
	_, err := q.db.ExecContext(ctx, registerAuthoringBlob, arg.ProblemID, arg.Sha256, arg.ByteSize)
	return err
}

const replaceWorkingCopy = `-- name: ReplaceWorkingCopy :execrows
UPDATE problem_working_copies SET tree_hash=$1,base_revision=$2,etag=gen_random_uuid(),updated_at=now()
WHERE problem_id=$3 AND actor_id=$4 AND etag=$5
`

type ReplaceWorkingCopyParams struct {
	TreeHash     string
	BaseRevision sql.NullInt64
	ProblemID    string
	ActorID      string
	Etag         string
}

func (q *Queries) ReplaceWorkingCopy(ctx context.Context, arg ReplaceWorkingCopyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, replaceWorkingCopy,
		arg.TreeHash,
		arg.BaseRevision,
		arg.ProblemID,
		arg.ActorID,
		arg.Etag,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveMergeSession = `-- name: SaveMergeSession :one
INSERT INTO problem_merge_sessions(problem_id,actor_id,copy_etag,base_revision,remote_revision,local_tree,remote_tree,result_json)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT(problem_id,actor_id) DO UPDATE SET id=gen_random_uuid(),etag=gen_random_uuid(),copy_etag=EXCLUDED.copy_etag,
base_revision=EXCLUDED.base_revision,remote_revision=EXCLUDED.remote_revision,local_tree=EXCLUDED.local_tree,
remote_tree=EXCLUDED.remote_tree,result_json=EXCLUDED.result_json,updated_at=now()
RETURNING id, problem_id, actor_id, etag, copy_etag, base_revision, remote_revision, local_tree, remote_tree, result_json, updated_at
`

type SaveMergeSessionParams struct {
	ProblemID      string
	ActorID        string
	CopyEtag       string
	BaseRevision   sql.NullInt64
	RemoteRevision sql.NullInt64
	LocalTree      string
	RemoteTree     string
	ResultJson     json.RawMessage
}

func (q *Queries) SaveMergeSession(ctx context.Context, arg SaveMergeSessionParams) (ProblemMergeSession, error) {
	row := q.db.QueryRowContext(ctx, saveMergeSession,
		arg.ProblemID,
		arg.ActorID,
		arg.CopyEtag,
		arg.BaseRevision,
		arg.RemoteRevision,
		arg.LocalTree,
		arg.RemoteTree,
		arg.ResultJson,
	)
	var i ProblemMergeSession
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.ActorID,
		&i.Etag,
		&i.CopyEtag,
		&i.BaseRevision,
		&i.RemoteRevision,
		&i.LocalTree,
		&i.RemoteTree,
		&i.ResultJson,
		&i.UpdatedAt,
	)
	return i, err
}

const startWorkingCopy = `-- name: StartWorkingCopy :exec
INSERT INTO problem_working_copies(problem_id,actor_id,base_revision,tree_hash)
SELECT h.problem_id,$1,h.revision,h.tree_hash FROM problem_authoring_heads h WHERE h.problem_id=$2
ON CONFLICT DO NOTHING
`

type StartWorkingCopyParams struct {
	ActorID   string
	ProblemID string
}

func (q *Queries) StartWorkingCopy(ctx context.Context, arg StartWorkingCopyParams) error {
	_, err := q.db.ExecContext(ctx, startWorkingCopy, arg.ActorID, arg.ProblemID)
	return err
}

const updateMergeDraft = `-- name: UpdateMergeDraft :execrows
UPDATE problem_merge_sessions SET result_json=$1,etag=gen_random_uuid(),updated_at=now()
WHERE problem_id=$2 AND actor_id=$3 AND id=$4 AND etag=$5
`

type UpdateMergeDraftParams struct {
	ResultJson json.RawMessage
	ProblemID  string
	ActorID    string
	ID         string
	Etag       string
}

func (q *Queries) UpdateMergeDraft(ctx context.Context, arg UpdateMergeDraftParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMergeDraft,
		arg.ResultJson,
		arg.ProblemID,
		arg.ActorID,
		arg.ID,
		arg.Etag,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
