// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package dbgen

import (
	"context"
)

const getPublishedFile = `-- name: GetPublishedFile :one
SELECT f.file_id,f.path,f.filename,f.media_type,f.purpose,f.blob_sha256,f.byte_size,f.sample_index,f.preview,f.truncated,f.is_binary,f.embedded
FROM problem_version_files f JOIN problems p ON p.id=f.problem_id
WHERE p.domain_id=$1 AND f.problem_id=$2 AND f.version_no=$3 AND f.file_id=$4
`

type GetPublishedFileParams struct {
	DomainID  string
	ProblemID string
	VersionNo int
	FileID    string
}

type GetPublishedFileRow struct {
	FileID      string
	Path        string
	Filename    string
	MediaType   string
	Purpose     string
	BlobSha256  string
	ByteSize    int64
	SampleIndex int
	Preview     string
	Truncated   bool
	IsBinary    bool
	Embedded    bool
}

func (q *Queries) GetPublishedFile(ctx context.Context, arg GetPublishedFileParams) (GetPublishedFileRow, error) {
	row := q.db.QueryRowContext(ctx, getPublishedFile,
		arg.DomainID,
		arg.ProblemID,
		arg.VersionNo,
		arg.FileID,
	)
	var i GetPublishedFileRow
	err := row.Scan(
		&i.FileID,
		&i.Path,
		&i.Filename,
		&i.MediaType,
		&i.Purpose,
		&i.BlobSha256,
		&i.ByteSize,
		&i.SampleIndex,
		&i.Preview,
		&i.Truncated,
		&i.IsBinary,
		&i.Embedded,
	)
	return i, err
}

const listPublishedFiles = `-- name: ListPublishedFiles :many
SELECT f.file_id,f.path,f.filename,f.media_type,f.purpose,f.blob_sha256,f.byte_size,f.sample_index,f.preview,f.truncated,f.is_binary,f.embedded
FROM problem_version_files f JOIN problems p ON p.id=f.problem_id
WHERE p.domain_id=$1 AND f.problem_id=$2 AND f.version_no=$3
ORDER BY f.sample_index,f.purpose,f.file_id
`

type ListPublishedFilesParams struct {
	DomainID  string
	ProblemID string
	VersionNo int
}

type ListPublishedFilesRow struct {
	FileID      string
	Path        string
	Filename    string
	MediaType   string
	Purpose     string
	BlobSha256  string
	ByteSize    int64
	SampleIndex int
	Preview     string
	Truncated   bool
	IsBinary    bool
	Embedded    bool
}

func (q *Queries) ListPublishedFiles(ctx context.Context, arg ListPublishedFilesParams) ([]ListPublishedFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedFiles, arg.DomainID, arg.ProblemID, arg.VersionNo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedFilesRow{}
	for rows.Next() {
		var i ListPublishedFilesRow
		if err := rows.Scan(
			&i.FileID,
			&i.Path,
			&i.Filename,
			&i.MediaType,
			&i.Purpose,
			&i.BlobSha256,
			&i.ByteSize,
			&i.SampleIndex,
			&i.Preview,
			&i.Truncated,
			&i.IsBinary,
			&i.Embedded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
