// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: numbers.sql

package dbgen

import (
	"context"
)

const resolveProblemNumber = `-- name: ResolveProblemNumber :one
SELECT id FROM problems WHERE domain_id=$1::uuid AND public_id=$2::bigint
`

type ResolveProblemNumberParams struct {
	DomainID string
	PublicID int64
}

func (q *Queries) ResolveProblemNumber(ctx context.Context, arg ResolveProblemNumberParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveProblemNumber, arg.DomainID, arg.PublicID)
	var id string
	err := row.Scan(&id)
	return id, err
}
