// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: problem.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const advanceTestdataRevision = `-- name: AdvanceTestdataRevision :one
UPDATE problems SET package_revision=package_revision+1,data_revision=data_revision+1 WHERE id=$1::uuid RETURNING data_revision
`

func (q *Queries) AdvanceTestdataRevision(ctx context.Context, problemID string) (int, error) {
	row := q.db.QueryRowContext(ctx, advanceTestdataRevision, problemID)
	var data_revision int
	err := row.Scan(&data_revision)
	return data_revision, err
}

const compareProblemWorkspace = `-- name: CompareProblemWorkspace :one
SELECT (title,statement_md,difficulty,source,time_limit_ms,memory_limit_kb,tags_json) IS DISTINCT FROM ($1::text,$2::text,$3::integer,$4::text,$5::integer,$6::integer,$7::jsonb) AS metadata_changed,
 (time_limit_ms,memory_limit_kb) IS DISTINCT FROM ($5::integer,$6::integer) AS data_changed FROM problem_workspaces WHERE problem_workspaces.problem_id=$8::uuid
`

type CompareProblemWorkspaceParams struct {
	Title         string
	StatementMd   string
	Difficulty    int
	Source        string
	TimeLimitMs   int
	MemoryLimitKb int
	Tags          json.RawMessage
	ProblemID     string
}

type CompareProblemWorkspaceRow struct {
	MetadataChanged bool
	DataChanged     bool
}

func (q *Queries) CompareProblemWorkspace(ctx context.Context, arg CompareProblemWorkspaceParams) (CompareProblemWorkspaceRow, error) {
	row := q.db.QueryRowContext(ctx, compareProblemWorkspace,
		arg.Title,
		arg.StatementMd,
		arg.Difficulty,
		arg.Source,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.Tags,
		arg.ProblemID,
	)
	var i CompareProblemWorkspaceRow
	err := row.Scan(&i.MetadataChanged, &i.DataChanged)
	return i, err
}

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems AS p (title, statement_md, difficulty, source,
		                      time_limit_ms, memory_limit_kb, visibility, author_id, owner_id, domain_id)
		 VALUES ($1::text, $2::text, $3::integer, $4::text, $5::integer, $6::integer, $7::text, $8::uuid, $8::uuid, $9::uuid)
		 RETURNING p.id,p.public_id,p.title,p.statement_md,p.difficulty,p.source,
 p.time_limit_ms,p.memory_limit_kb,p.visibility,p.author_id,p.submission_count,p.accepted_count,p.solved_user_count,
 p.judge_type,p.created_at,p.updated_at,p.owner_id,p.domain_id,COALESCE(p.published_version,0)::integer AS published_version,
 COALESCE((SELECT jsonb_agg(t.name ORDER BY t.name) FROM problem_tags pt JOIN tags t ON t.id=pt.tag_id WHERE pt.problem_id=p.id),'[]'::jsonb)::jsonb AS tags,COALESCE((SELECT u.username FROM users u WHERE u.id=p.owner_id),'')::text AS owner_name,0::integer AS grant_rank
`

type CreateProblemParams struct {
	Title         string
	StatementMd   string
	Difficulty    int
	Source        string
	TimeLimitMs   int
	MemoryLimitKb int
	Visibility    string
	AuthorID      string
	DomainID      string
}

type CreateProblemRow struct {
	ID               string
	PublicID         string
	Title            string
	StatementMd      string
	Difficulty       int
	Source           string
	TimeLimitMs      int
	MemoryLimitKb    int
	Visibility       string
	AuthorID         *string
	SubmissionCount  int
	AcceptedCount    int
	SolvedUserCount  int
	JudgeType        string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	OwnerID          string
	DomainID         string
	PublishedVersion int
	Tags             json.RawMessage
	OwnerName        string
	GrantRank        int
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (CreateProblemRow, error) {
	row := q.db.QueryRowContext(ctx, createProblem,
		arg.Title,
		arg.StatementMd,
		arg.Difficulty,
		arg.Source,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.Visibility,
		arg.AuthorID,
		arg.DomainID,
	)
	var i CreateProblemRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.StatementMd,
		&i.Difficulty,
		&i.Source,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.Visibility,
		&i.AuthorID,
		&i.SubmissionCount,
		&i.AcceptedCount,
		&i.SolvedUserCount,
		&i.JudgeType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.DomainID,
		&i.PublishedVersion,
		&i.Tags,
		&i.OwnerName,
		&i.GrantRank,
	)
	return i, err
}

const deleteProblem = `-- name: DeleteProblem :execrows
DELETE FROM problems WHERE id = $1::uuid AND domain_id = $2::uuid
`

type DeleteProblemParams struct {
	ProblemID string
	DomainID  string
}

func (q *Queries) DeleteProblem(ctx context.Context, arg DeleteProblemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProblem, arg.ProblemID, arg.DomainID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProblemGrant = `-- name: DeleteProblemGrant :execrows
DELETE FROM problem_access WHERE problem_id=$1::uuid AND id=$2::bigint AND domain_id=$3::uuid
`

type DeleteProblemGrantParams struct {
	ProblemID string
	GrantID   int64
	DomainID  string
}

func (q *Queries) DeleteProblemGrant(ctx context.Context, arg DeleteProblemGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProblemGrant, arg.ProblemID, arg.GrantID, arg.DomainID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProblemOwnerGrants = `-- name: DeleteProblemOwnerGrants :exec
DELETE FROM problem_access WHERE problem_id=$1::uuid AND user_id=$2::uuid
`

type DeleteProblemOwnerGrantsParams struct {
	ProblemID string
	UserID    string
}

func (q *Queries) DeleteProblemOwnerGrants(ctx context.Context, arg DeleteProblemOwnerGrantsParams) error {
	_, err := q.db.ExecContext(ctx, deleteProblemOwnerGrants, arg.ProblemID, arg.UserID)
	return err
}

const findProblemCollaborator = `-- name: FindProblemCollaborator :one
SELECT m.user_id FROM domain_members m JOIN users u ON u.id=m.user_id
	 WHERE m.domain_id=$1::uuid AND u.username=$2::text AND m.status='active' AND u.disabled_at IS NULL
	 FOR SHARE OF u
`

type FindProblemCollaboratorParams struct {
	DomainID string
	Username string
}

func (q *Queries) FindProblemCollaborator(ctx context.Context, arg FindProblemCollaboratorParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findProblemCollaborator, arg.DomainID, arg.Username)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getProblem = `-- name: GetProblem :one
SELECT p.id,p.public_id,p.title,p.statement_md,p.difficulty,p.source,
 p.time_limit_ms,p.memory_limit_kb,p.visibility,p.author_id,p.submission_count,p.accepted_count,p.solved_user_count,
 p.judge_type,p.created_at,p.updated_at,p.owner_id,p.domain_id,COALESCE(p.published_version,0)::integer AS published_version,
 COALESCE((SELECT jsonb_agg(t.name ORDER BY t.name) FROM problem_tags pt JOIN tags t ON t.id=pt.tag_id WHERE pt.problem_id=p.id),'[]'::jsonb)::jsonb AS tags,COALESCE((SELECT u.username FROM users u WHERE u.id=p.owner_id),'')::text AS owner_name,0::integer AS grant_rank
FROM problems p WHERE p.id=$1::uuid AND p.domain_id=$2::uuid
`

type GetProblemParams struct {
	ProblemID string
	DomainID  string
}

type GetProblemRow struct {
	ID               string
	PublicID         string
	Title            string
	StatementMd      string
	Difficulty       int
	Source           string
	TimeLimitMs      int
	MemoryLimitKb    int
	Visibility       string
	AuthorID         *string
	SubmissionCount  int
	AcceptedCount    int
	SolvedUserCount  int
	JudgeType        string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	OwnerID          string
	DomainID         string
	PublishedVersion int
	Tags             json.RawMessage
	OwnerName        string
	GrantRank        int
}

func (q *Queries) GetProblem(ctx context.Context, arg GetProblemParams) (GetProblemRow, error) {
	row := q.db.QueryRowContext(ctx, getProblem, arg.ProblemID, arg.DomainID)
	var i GetProblemRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.StatementMd,
		&i.Difficulty,
		&i.Source,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.Visibility,
		&i.AuthorID,
		&i.SubmissionCount,
		&i.AcceptedCount,
		&i.SolvedUserCount,
		&i.JudgeType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.DomainID,
		&i.PublishedVersion,
		&i.Tags,
		&i.OwnerName,
		&i.GrantRank,
	)
	return i, err
}

const getProblemAccess = `-- name: GetProblemAccess :one
SELECT id,owner_id,visibility,COALESCE(published_version,0)::integer AS published_version FROM problems WHERE id=$1::uuid AND domain_id=$2::uuid
`

type GetProblemAccessParams struct {
	ProblemID string
	DomainID  string
}

type GetProblemAccessRow struct {
	ID               string
	OwnerID          string
	Visibility       string
	PublishedVersion int
}

func (q *Queries) GetProblemAccess(ctx context.Context, arg GetProblemAccessParams) (GetProblemAccessRow, error) {
	row := q.db.QueryRowContext(ctx, getProblemAccess, arg.ProblemID, arg.DomainID)
	var i GetProblemAccessRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Visibility,
		&i.PublishedVersion,
	)
	return i, err
}

const getProblemGrantRank = `-- name: GetProblemGrantRank :one
SELECT COALESCE(max(CASE WHEN role='editor' THEN 2 ELSE 1 END),0)::integer
		 FROM problem_access a WHERE a.domain_id=$1::uuid AND a.problem_id=$2::uuid
		 AND (a.user_id=$3::uuid OR a.group_id IN (
		   SELECT group_id FROM domain_group_members WHERE domain_id=$1::uuid AND user_id=$3::uuid))
`

type GetProblemGrantRankParams struct {
	DomainID  string
	ProblemID string
	ViewerID  string
}

func (q *Queries) GetProblemGrantRank(ctx context.Context, arg GetProblemGrantRankParams) (int, error) {
	row := q.db.QueryRowContext(ctx, getProblemGrantRank, arg.DomainID, arg.ProblemID, arg.ViewerID)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const getProblemWorkspace = `-- name: GetProblemWorkspace :one
SELECT p.id,p.public_id,w.title,w.statement_md,w.difficulty,w.source,
 w.time_limit_ms,w.memory_limit_kb,p.visibility,p.author_id,p.submission_count,p.accepted_count,p.solved_user_count,
 w.judge_type,p.created_at,w.updated_at,p.owner_id,p.domain_id,COALESCE(p.published_version,0)::integer AS published_version,
 w.tags_json AS tags,COALESCE((SELECT u.username FROM users u WHERE u.id=p.owner_id),'')::text AS owner_name,0::integer AS grant_rank
FROM problems p JOIN problem_workspaces w ON w.problem_id=p.id WHERE p.id=$1::uuid AND p.domain_id=$2::uuid
`

type GetProblemWorkspaceParams struct {
	ProblemID string
	DomainID  string
}

type GetProblemWorkspaceRow struct {
	ID               string
	PublicID         string
	Title            string
	StatementMd      string
	Difficulty       int
	Source           string
	TimeLimitMs      int
	MemoryLimitKb    int
	Visibility       string
	AuthorID         *string
	SubmissionCount  int
	AcceptedCount    int
	SolvedUserCount  int
	JudgeType        string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	OwnerID          string
	DomainID         string
	PublishedVersion int
	Tags             json.RawMessage
	OwnerName        string
	GrantRank        int
}

func (q *Queries) GetProblemWorkspace(ctx context.Context, arg GetProblemWorkspaceParams) (GetProblemWorkspaceRow, error) {
	row := q.db.QueryRowContext(ctx, getProblemWorkspace, arg.ProblemID, arg.DomainID)
	var i GetProblemWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.StatementMd,
		&i.Difficulty,
		&i.Source,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.Visibility,
		&i.AuthorID,
		&i.SubmissionCount,
		&i.AcceptedCount,
		&i.SolvedUserCount,
		&i.JudgeType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.DomainID,
		&i.PublishedVersion,
		&i.Tags,
		&i.OwnerName,
		&i.GrantRank,
	)
	return i, err
}

const getPublishedTestdata = `-- name: GetPublishedTestdata :one
SELECT v.problem_id,v.artifact_version,v.testdata_path,v.sha256,v.case_count,v.checker,v.spj_source,v.config_json
		 FROM problem_versions v JOIN problems p ON p.id=v.problem_id AND p.published_version=v.version_no
		 WHERE p.id=$1::uuid AND p.domain_id=$2::uuid
`

type GetPublishedTestdataParams struct {
	ProblemID string
	DomainID  string
}

type GetPublishedTestdataRow struct {
	ProblemID       string
	ArtifactVersion int
	TestdataPath    string
	Sha256          string
	CaseCount       int
	Checker         string
	SpjSource       string
	ConfigJson      json.RawMessage
}

func (q *Queries) GetPublishedTestdata(ctx context.Context, arg GetPublishedTestdataParams) (GetPublishedTestdataRow, error) {
	row := q.db.QueryRowContext(ctx, getPublishedTestdata, arg.ProblemID, arg.DomainID)
	var i GetPublishedTestdataRow
	err := row.Scan(
		&i.ProblemID,
		&i.ArtifactVersion,
		&i.TestdataPath,
		&i.Sha256,
		&i.CaseCount,
		&i.Checker,
		&i.SpjSource,
		&i.ConfigJson,
	)
	return i, err
}

const grantProblemGroup = `-- name: GrantProblemGroup :exec
INSERT INTO problem_access(domain_id,problem_id,group_id,role,granted_by)
VALUES($1::uuid,$2::uuid,$3::uuid,$4::text,$5::uuid)
ON CONFLICT(problem_id,group_id) WHERE group_id IS NOT NULL DO UPDATE SET role=EXCLUDED.role,granted_by=EXCLUDED.granted_by
`

type GrantProblemGroupParams struct {
	DomainID  string
	ProblemID string
	SubjectID string
	Role      string
	ActorID   string
}

func (q *Queries) GrantProblemGroup(ctx context.Context, arg GrantProblemGroupParams) error {
	_, err := q.db.ExecContext(ctx, grantProblemGroup,
		arg.DomainID,
		arg.ProblemID,
		arg.SubjectID,
		arg.Role,
		arg.ActorID,
	)
	return err
}

const grantProblemUser = `-- name: GrantProblemUser :exec
INSERT INTO problem_access(domain_id,problem_id,user_id,role,granted_by)
VALUES($1::uuid,$2::uuid,$3::uuid,$4::text,$5::uuid)
ON CONFLICT(problem_id,user_id) WHERE user_id IS NOT NULL DO UPDATE SET role=EXCLUDED.role,granted_by=EXCLUDED.granted_by
`

type GrantProblemUserParams struct {
	DomainID  string
	ProblemID string
	SubjectID string
	Role      string
	ActorID   string
}

func (q *Queries) GrantProblemUser(ctx context.Context, arg GrantProblemUserParams) error {
	_, err := q.db.ExecContext(ctx, grantProblemUser,
		arg.DomainID,
		arg.ProblemID,
		arg.SubjectID,
		arg.Role,
		arg.ActorID,
	)
	return err
}

const hasProblemReferences = `-- name: HasProblemReferences :one
SELECT COALESCE(EXISTS(SELECT 1 FROM submissions WHERE submissions.problem_id =$1::uuid) OR EXISTS(SELECT 1 FROM contest_problems WHERE contest_problems.problem_id =$1::uuid),false)::boolean AS referenced
`

func (q *Queries) HasProblemReferences(ctx context.Context, problemID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasProblemReferences, problemID)
	var referenced bool
	err := row.Scan(&referenced)
	return referenced, err
}

const listProblemGrants = `-- name: ListProblemGrants :many
SELECT a.id,a.user_id,u.username,a.group_id,g.name AS group_name,a.role
	 FROM problem_access a LEFT JOIN users u ON u.id=a.user_id LEFT JOIN domain_groups g ON g.id=a.group_id
	 WHERE a.problem_id=$1::uuid AND a.domain_id=$2::uuid ORDER BY a.id
`

type ListProblemGrantsParams struct {
	ProblemID string
	DomainID  string
}

type ListProblemGrantsRow struct {
	ID        int64
	UserID    *string
	Username  sql.NullString
	GroupID   *string
	GroupName sql.NullString
	Role      string
}

func (q *Queries) ListProblemGrants(ctx context.Context, arg ListProblemGrantsParams) ([]ListProblemGrantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProblemGrants, arg.ProblemID, arg.DomainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProblemGrantsRow{}
	for rows.Next() {
		var i ListProblemGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.GroupID,
			&i.GroupName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicProblemTags = `-- name: ListPublicProblemTags :many
SELECT t.name, count(*)::int AS problem_count
		 FROM tags t
		 JOIN problem_tags pt ON pt.tag_id = t.id
		 JOIN problems p ON p.id = pt.problem_id AND p.visibility = 'public' AND p.published_version IS NOT NULL
		 WHERE p.domain_id = $1::uuid
		 GROUP BY t.name
		 ORDER BY problem_count DESC, t.name ASC
`

type ListPublicProblemTagsRow struct {
	Name         string
	ProblemCount int
}

func (q *Queries) ListPublicProblemTags(ctx context.Context, domainID string) ([]ListPublicProblemTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicProblemTags, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicProblemTagsRow{}
	for rows.Next() {
		var i ListPublicProblemTagsRow
		if err := rows.Scan(&i.Name, &i.ProblemCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProblemStatuses = `-- name: ListUserProblemStatuses :many
SELECT problem_id, bool_or(status = 'Accepted') AS solved
		 FROM submissions
		 WHERE user_id = $1::uuid AND problem_id = ANY($2::uuid[]) AND contest_id IS NULL AND domain_id = $3::uuid
		 GROUP BY problem_id
`

type ListUserProblemStatusesParams struct {
	ViewerID   string
	ProblemIds []string
	DomainID   string
}

type ListUserProblemStatusesRow struct {
	ProblemID string
	Solved    bool
}

func (q *Queries) ListUserProblemStatuses(ctx context.Context, arg ListUserProblemStatusesParams) ([]ListUserProblemStatusesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserProblemStatuses, arg.ViewerID, pq.Array(arg.ProblemIds), arg.DomainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserProblemStatusesRow{}
	for rows.Next() {
		var i ListUserProblemStatusesRow
		if err := rows.Scan(&i.ProblemID, &i.Solved); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPracticeCounters = `-- name: LockPracticeCounters :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockPracticeCounters(ctx context.Context, lockKey string) error {
	_, err := q.db.ExecContext(ctx, lockPracticeCounters, lockKey)
	return err
}

const lockProblemAccess = `-- name: LockProblemAccess :one
SELECT id,owner_id,visibility,COALESCE(published_version,0)::integer AS published_version FROM problems WHERE id=$1::uuid AND domain_id=$2::uuid FOR UPDATE
`

type LockProblemAccessParams struct {
	ProblemID string
	DomainID  string
}

type LockProblemAccessRow struct {
	ID               string
	OwnerID          string
	Visibility       string
	PublishedVersion int
}

func (q *Queries) LockProblemAccess(ctx context.Context, arg LockProblemAccessParams) (LockProblemAccessRow, error) {
	row := q.db.QueryRowContext(ctx, lockProblemAccess, arg.ProblemID, arg.DomainID)
	var i LockProblemAccessRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Visibility,
		&i.PublishedVersion,
	)
	return i, err
}

const rebuildPracticeCounters = `-- name: RebuildPracticeCounters :exec
UPDATE problems SET
		   submission_count = (SELECT count(*) FROM submissions
		     WHERE submissions.problem_id = $1::uuid AND contest_id IS NULL AND judged_at IS NOT NULL),
		   accepted_count = (SELECT count(*) FROM submissions
		     WHERE submissions.problem_id = $1::uuid AND contest_id IS NULL AND status = 'Accepted'),
		   solved_user_count = (SELECT count(DISTINCT user_id) FROM submissions
		     WHERE submissions.problem_id = $1::uuid AND contest_id IS NULL AND status = 'Accepted')
		 WHERE id = $1::uuid
`

func (q *Queries) RebuildPracticeCounters(ctx context.Context, problemID string) error {
	_, err := q.db.ExecContext(ctx, rebuildPracticeCounters, problemID)
	return err
}

const recordProblemAccessAudit = `-- name: RecordProblemAccessAudit :exec
INSERT INTO domain_audit_events(domain_id,actor_id,action,target) VALUES($1::uuid,$2::uuid,$3::text,$4::text)
`

type RecordProblemAccessAuditParams struct {
	DomainID string
	ActorID  string
	Action   string
	Target   string
}

func (q *Queries) RecordProblemAccessAudit(ctx context.Context, arg RecordProblemAccessAuditParams) error {
	_, err := q.db.ExecContext(ctx, recordProblemAccessAudit,
		arg.DomainID,
		arg.ActorID,
		arg.Action,
		arg.Target,
	)
	return err
}

const resolveProblemGrantGroup = `-- name: ResolveProblemGrantGroup :one
SELECT id FROM domain_groups WHERE domain_id=$1::uuid AND (id::text=$2::text OR public_id::text=$2::text)
`

type ResolveProblemGrantGroupParams struct {
	DomainID string
	GroupRef string
}

func (q *Queries) ResolveProblemGrantGroup(ctx context.Context, arg ResolveProblemGrantGroupParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveProblemGrantGroup, arg.DomainID, arg.GroupRef)
	var id string
	err := row.Scan(&id)
	return id, err
}

const saveImportedTestdata = `-- name: SaveImportedTestdata :exec
INSERT INTO problem_testdata (problem_id, data_version, storage_path, sha256, case_count, checker, data_revision)
		 VALUES ($1::uuid, 1, $2::text, $3::text, $4::integer, $5::text, $6::integer)
		 ON CONFLICT (problem_id) DO UPDATE SET
		   data_version = problem_testdata.data_version + 1,
		   storage_path = EXCLUDED.storage_path,
		   sha256 = EXCLUDED.sha256,
		   case_count = EXCLUDED.case_count,
		   checker = EXCLUDED.checker, data_revision=EXCLUDED.data_revision,
		   build_id=NULL,samples_json='[]',config_json='{}',spj_source=''
`

type SaveImportedTestdataParams struct {
	ProblemID    string
	StoragePath  string
	Sha256       string
	CaseCount    int
	Checker      string
	DataRevision int
}

func (q *Queries) SaveImportedTestdata(ctx context.Context, arg SaveImportedTestdataParams) error {
	_, err := q.db.ExecContext(ctx, saveImportedTestdata,
		arg.ProblemID,
		arg.StoragePath,
		arg.Sha256,
		arg.CaseCount,
		arg.Checker,
		arg.DataRevision,
	)
	return err
}

const setWorkspaceTags = `-- name: SetWorkspaceTags :exec
UPDATE problem_workspaces SET tags_json=$1::jsonb WHERE problem_id=$2::uuid
`

type SetWorkspaceTagsParams struct {
	Tags      json.RawMessage
	ProblemID string
}

func (q *Queries) SetWorkspaceTags(ctx context.Context, arg SetWorkspaceTagsParams) error {
	_, err := q.db.ExecContext(ctx, setWorkspaceTags, arg.Tags, arg.ProblemID)
	return err
}

const syncDefaultStatementName = `-- name: SyncDefaultStatementName :exec
UPDATE problem_statements SET name=$1::text,updated_at=now() WHERE problem_statements.problem_id=$2::uuid AND language=(SELECT statement_language FROM problem_workspaces WHERE problem_workspaces.problem_id=$2::uuid) AND name IS DISTINCT FROM $1::text
`

type SyncDefaultStatementNameParams struct {
	Title     string
	ProblemID string
}

func (q *Queries) SyncDefaultStatementName(ctx context.Context, arg SyncDefaultStatementNameParams) error {
	_, err := q.db.ExecContext(ctx, syncDefaultStatementName, arg.Title, arg.ProblemID)
	return err
}

const transferProblemOwner = `-- name: TransferProblemOwner :exec
UPDATE problems SET owner_id=$1::uuid,updated_at=now() WHERE id=$2::uuid AND domain_id=$3::uuid
`

type TransferProblemOwnerParams struct {
	OwnerID   string
	ProblemID string
	DomainID  string
}

func (q *Queries) TransferProblemOwner(ctx context.Context, arg TransferProblemOwnerParams) error {
	_, err := q.db.ExecContext(ctx, transferProblemOwner, arg.OwnerID, arg.ProblemID, arg.DomainID)
	return err
}

const updateProblemRevisions = `-- name: UpdateProblemRevisions :exec
UPDATE problems SET visibility=$1::text,
 package_revision=package_revision+CASE WHEN $2::boolean THEN 1 ELSE 0 END,
 data_revision=data_revision+CASE WHEN $3::boolean THEN 1 ELSE 0 END,
 updated_at=CASE WHEN visibility<>$1::text THEN now() ELSE updated_at END WHERE id=$4::uuid
`

type UpdateProblemRevisionsParams struct {
	Visibility      string
	MetadataChanged bool
	DataChanged     bool
	ProblemID       string
}

func (q *Queries) UpdateProblemRevisions(ctx context.Context, arg UpdateProblemRevisionsParams) error {
	_, err := q.db.ExecContext(ctx, updateProblemRevisions,
		arg.Visibility,
		arg.MetadataChanged,
		arg.DataChanged,
		arg.ProblemID,
	)
	return err
}

const updateProblemWorkspace = `-- name: UpdateProblemWorkspace :exec
UPDATE problem_workspaces SET title=$1::text,statement_md=$2::text,difficulty=$3::integer,source=$4::text,time_limit_ms=$5::integer,memory_limit_kb=$6::integer,tags_json=$7::jsonb,updated_at=now() WHERE problem_id=$8::uuid
`

type UpdateProblemWorkspaceParams struct {
	Title         string
	StatementMd   string
	Difficulty    int
	Source        string
	TimeLimitMs   int
	MemoryLimitKb int
	Tags          json.RawMessage
	ProblemID     string
}

func (q *Queries) UpdateProblemWorkspace(ctx context.Context, arg UpdateProblemWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, updateProblemWorkspace,
		arg.Title,
		arg.StatementMd,
		arg.Difficulty,
		arg.Source,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.Tags,
		arg.ProblemID,
	)
	return err
}
