// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const countVisibleSubmissions = `-- name: CountVisibleSubmissions :one
SELECT count(*) FROM submissions s JOIN users u ON u.id=s.user_id JOIN problems p ON p.id=s.problem_id
WHERE s.domain_id=$1::uuid AND (
		$2::boolean
		OR s.user_id = NULLIF($3::text,'')::uuid
		OR (
			s.contest_id IS NULL
			AND ((p.visibility = 'public' AND p.published_version IS NOT NULL) OR ($4::boolean AND (p.owner_id = NULLIF($3::text,'')::uuid OR EXISTS (
			 SELECT 1 FROM problem_access a WHERE a.problem_id=p.id AND (a.user_id=NULLIF($3::text,'')::uuid OR a.group_id IN (
			 SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($3::text,'')::uuid))))))
		)
		OR EXISTS (
			SELECT 1 FROM contests c
			WHERE c.id = s.contest_id
			  AND (
				($4::boolean AND c.owner_id = NULLIF($3::text,'')::uuid)
				OR EXISTS (
					SELECT 1 FROM contest_staff staff
					WHERE staff.contest_id = c.id AND staff.user_id = NULLIF($3::text,'')::uuid
				)
				OR (
					c.end_at < now()
					AND c.rankboard_visible
					AND NOT (
						c.freeze_at IS NOT NULL
						AND now() > c.freeze_at
						AND (c.unfreeze_at IS NULL OR now() < c.unfreeze_at)
					)
					AND (
						(c.visibility = 'public' AND (
							p.visibility = 'public'
							OR EXISTS (
								SELECT 1 FROM contest_participants participant
								WHERE participant.contest_id = c.id
								  AND participant.user_id = NULLIF($3::text,'')::uuid
							)
						))
						OR (c.visibility = 'password' AND EXISTS (
							SELECT 1 FROM contest_participants participant
							WHERE participant.contest_id = c.id
							  AND participant.user_id = NULLIF($3::text,'')::uuid
						))
					)
				)
			  )
		)
	)
AND ($5::text='' OR s.user_id::text=$5::text OR u.username=$5::text)
AND ($6::text='' OR s.problem_id=NULLIF($6::text,'')::uuid)
AND ($7::text='' OR s.contest_id=NULLIF($7::text,'')::uuid)
AND ($8::text='' OR s.language=$8::text)
AND ($9::text='' OR (CASE WHEN s.status NOT IN ('Pending','Judging') AND EXISTS (
	 SELECT 1 FROM contests feedback_contest WHERE feedback_contest.id=s.contest_id
	 AND feedback_contest.feedback='none' AND feedback_contest.end_at>=now()
	 AND NOT ($2::boolean OR ($4::boolean AND feedback_contest.owner_id=NULLIF($3::text,'')::uuid)
	 OR EXISTS(SELECT 1 FROM contest_staff staff WHERE staff.contest_id=feedback_contest.id AND staff.user_id=NULLIF($3::text,'')::uuid))
	) THEN 'Submitted' ELSE s.status END)=$9::text)
`

type CountVisibleSubmissionsParams struct {
	DomainID       string
	IsManager      bool
	ViewerID       string
	ActiveMember   bool
	UserFilter     string
	ProblemFilter  string
	ContestFilter  string
	LanguageFilter string
	StatusFilter   string
}

func (q *Queries) CountVisibleSubmissions(ctx context.Context, arg CountVisibleSubmissionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVisibleSubmissions,
		arg.DomainID,
		arg.IsManager,
		arg.ViewerID,
		arg.ActiveMember,
		arg.UserFilter,
		arg.ProblemFilter,
		arg.ContestFilter,
		arg.LanguageFilter,
		arg.StatusFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVisibleProgress = `-- name: GetVisibleProgress :one
SELECT s.id,s.user_id,s.contest_id,s.status,s.score,s.total_time_ms,s.peak_memory_kb,s.compile_result,s.case_results,s.judged_cases,s.total_cases FROM submissions s JOIN problems p ON p.id=s.problem_id
WHERE s.id=$1::uuid AND s.domain_id=$2::uuid AND (
		$3::boolean
		OR s.user_id = NULLIF($4::text,'')::uuid
		OR (
			s.contest_id IS NULL
			AND ((p.visibility = 'public' AND p.published_version IS NOT NULL) OR ($5::boolean AND (p.owner_id = NULLIF($4::text,'')::uuid OR EXISTS (
			 SELECT 1 FROM problem_access a WHERE a.problem_id=p.id AND (a.user_id=NULLIF($4::text,'')::uuid OR a.group_id IN (
			 SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($4::text,'')::uuid))))))
		)
		OR EXISTS (
			SELECT 1 FROM contests c
			WHERE c.id = s.contest_id
			  AND (
				($5::boolean AND c.owner_id = NULLIF($4::text,'')::uuid)
				OR EXISTS (
					SELECT 1 FROM contest_staff staff
					WHERE staff.contest_id = c.id AND staff.user_id = NULLIF($4::text,'')::uuid
				)
				OR (
					c.end_at < now()
					AND c.rankboard_visible
					AND NOT (
						c.freeze_at IS NOT NULL
						AND now() > c.freeze_at
						AND (c.unfreeze_at IS NULL OR now() < c.unfreeze_at)
					)
					AND (
						(c.visibility = 'public' AND (
							p.visibility = 'public'
							OR EXISTS (
								SELECT 1 FROM contest_participants participant
								WHERE participant.contest_id = c.id
								  AND participant.user_id = NULLIF($4::text,'')::uuid
							)
						))
						OR (c.visibility = 'password' AND EXISTS (
							SELECT 1 FROM contest_participants participant
							WHERE participant.contest_id = c.id
							  AND participant.user_id = NULLIF($4::text,'')::uuid
						))
					)
				)
			  )
		)
	)
`

type GetVisibleProgressParams struct {
	SubmissionID string
	DomainID     string
	IsManager    bool
	ViewerID     string
	ActiveMember bool
}

type GetVisibleProgressRow struct {
	ID            string
	UserID        string
	ContestID     *string
	Status        string
	Score         int
	TotalTimeMs   int
	PeakMemoryKb  int
	CompileResult string
	CaseResults   json.RawMessage
	JudgedCases   int
	TotalCases    int
}

func (q *Queries) GetVisibleProgress(ctx context.Context, arg GetVisibleProgressParams) (GetVisibleProgressRow, error) {
	row := q.db.QueryRowContext(ctx, getVisibleProgress,
		arg.SubmissionID,
		arg.DomainID,
		arg.IsManager,
		arg.ViewerID,
		arg.ActiveMember,
	)
	var i GetVisibleProgressRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ContestID,
		&i.Status,
		&i.Score,
		&i.TotalTimeMs,
		&i.PeakMemoryKb,
		&i.CompileResult,
		&i.CaseResults,
		&i.JudgedCases,
		&i.TotalCases,
	)
	return i, err
}

const getVisibleSubmission = `-- name: GetVisibleSubmission :one
SELECT s.id,s.public_id,s.user_id,u.username,s.problem_id,p.public_id AS problem_public_id,v.title AS problem_title,s.language,s.status,s.score,s.total_time_ms,s.peak_memory_kb,s.judged_cases,s.total_cases,s.contest_id,COALESCE(c.public_id::text,'')::text AS contest_public_id,s.submitted_at,s.problem_version,s.source_code,s.compile_result,s.case_results,s.judged_at FROM submissions s JOIN users u ON u.id=s.user_id JOIN problems p ON p.id=s.problem_id JOIN problem_versions v ON v.problem_id=s.problem_id AND v.version_no=s.problem_version LEFT JOIN contests c ON c.id=s.contest_id
WHERE s.id=$1::uuid AND s.domain_id=$2::uuid AND (
		$3::boolean
		OR s.user_id = NULLIF($4::text,'')::uuid
		OR (
			s.contest_id IS NULL
			AND ((p.visibility = 'public' AND p.published_version IS NOT NULL) OR ($5::boolean AND (p.owner_id = NULLIF($4::text,'')::uuid OR EXISTS (
			 SELECT 1 FROM problem_access a WHERE a.problem_id=p.id AND (a.user_id=NULLIF($4::text,'')::uuid OR a.group_id IN (
			 SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($4::text,'')::uuid))))))
		)
		OR EXISTS (
			SELECT 1 FROM contests c
			WHERE c.id = s.contest_id
			  AND (
				($5::boolean AND c.owner_id = NULLIF($4::text,'')::uuid)
				OR EXISTS (
					SELECT 1 FROM contest_staff staff
					WHERE staff.contest_id = c.id AND staff.user_id = NULLIF($4::text,'')::uuid
				)
				OR (
					c.end_at < now()
					AND c.rankboard_visible
					AND NOT (
						c.freeze_at IS NOT NULL
						AND now() > c.freeze_at
						AND (c.unfreeze_at IS NULL OR now() < c.unfreeze_at)
					)
					AND (
						(c.visibility = 'public' AND (
							p.visibility = 'public'
							OR EXISTS (
								SELECT 1 FROM contest_participants participant
								WHERE participant.contest_id = c.id
								  AND participant.user_id = NULLIF($4::text,'')::uuid
							)
						))
						OR (c.visibility = 'password' AND EXISTS (
							SELECT 1 FROM contest_participants participant
							WHERE participant.contest_id = c.id
							  AND participant.user_id = NULLIF($4::text,'')::uuid
						))
					)
				)
			  )
		)
	)
`

type GetVisibleSubmissionParams struct {
	SubmissionID string
	DomainID     string
	IsManager    bool
	ViewerID     string
	ActiveMember bool
}

type GetVisibleSubmissionRow struct {
	ID              string
	PublicID        string
	UserID          string
	Username        string
	ProblemID       string
	ProblemPublicID string
	ProblemTitle    string
	Language        string
	Status          string
	Score           int
	TotalTimeMs     int
	PeakMemoryKb    int
	JudgedCases     int
	TotalCases      int
	ContestID       *string
	ContestPublicID string
	SubmittedAt     time.Time
	ProblemVersion  int
	SourceCode      string
	CompileResult   string
	CaseResults     json.RawMessage
	JudgedAt        *time.Time
}

func (q *Queries) GetVisibleSubmission(ctx context.Context, arg GetVisibleSubmissionParams) (GetVisibleSubmissionRow, error) {
	row := q.db.QueryRowContext(ctx, getVisibleSubmission,
		arg.SubmissionID,
		arg.DomainID,
		arg.IsManager,
		arg.ViewerID,
		arg.ActiveMember,
	)
	var i GetVisibleSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Username,
		&i.ProblemID,
		&i.ProblemPublicID,
		&i.ProblemTitle,
		&i.Language,
		&i.Status,
		&i.Score,
		&i.TotalTimeMs,
		&i.PeakMemoryKb,
		&i.JudgedCases,
		&i.TotalCases,
		&i.ContestID,
		&i.ContestPublicID,
		&i.SubmittedAt,
		&i.ProblemVersion,
		&i.SourceCode,
		&i.CompileResult,
		&i.CaseResults,
		&i.JudgedAt,
	)
	return i, err
}

const listVisibleSubmissions = `-- name: ListVisibleSubmissions :many
SELECT s.id,s.public_id,s.user_id,u.username,s.problem_id,p.public_id AS problem_public_id,v.title AS problem_title,s.language,s.status,s.score,s.total_time_ms,s.peak_memory_kb,s.judged_cases,s.total_cases,s.contest_id,COALESCE(c.public_id::text,'')::text AS contest_public_id,s.submitted_at,s.problem_version FROM submissions s JOIN users u ON u.id=s.user_id JOIN problems p ON p.id=s.problem_id JOIN problem_versions v ON v.problem_id=s.problem_id AND v.version_no=s.problem_version LEFT JOIN contests c ON c.id=s.contest_id
WHERE s.domain_id=$1::uuid AND (
		$2::boolean
		OR s.user_id = NULLIF($3::text,'')::uuid
		OR (
			s.contest_id IS NULL
			AND ((p.visibility = 'public' AND p.published_version IS NOT NULL) OR ($4::boolean AND (p.owner_id = NULLIF($3::text,'')::uuid OR EXISTS (
			 SELECT 1 FROM problem_access a WHERE a.problem_id=p.id AND (a.user_id=NULLIF($3::text,'')::uuid OR a.group_id IN (
			 SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($3::text,'')::uuid))))))
		)
		OR EXISTS (
			SELECT 1 FROM contests c
			WHERE c.id = s.contest_id
			  AND (
				($4::boolean AND c.owner_id = NULLIF($3::text,'')::uuid)
				OR EXISTS (
					SELECT 1 FROM contest_staff staff
					WHERE staff.contest_id = c.id AND staff.user_id = NULLIF($3::text,'')::uuid
				)
				OR (
					c.end_at < now()
					AND c.rankboard_visible
					AND NOT (
						c.freeze_at IS NOT NULL
						AND now() > c.freeze_at
						AND (c.unfreeze_at IS NULL OR now() < c.unfreeze_at)
					)
					AND (
						(c.visibility = 'public' AND (
							p.visibility = 'public'
							OR EXISTS (
								SELECT 1 FROM contest_participants participant
								WHERE participant.contest_id = c.id
								  AND participant.user_id = NULLIF($3::text,'')::uuid
							)
						))
						OR (c.visibility = 'password' AND EXISTS (
							SELECT 1 FROM contest_participants participant
							WHERE participant.contest_id = c.id
							  AND participant.user_id = NULLIF($3::text,'')::uuid
						))
					)
				)
			  )
		)
	)
AND ($5::text='' OR s.user_id::text=$5::text OR u.username=$5::text)
AND ($6::text='' OR s.problem_id=NULLIF($6::text,'')::uuid)
AND ($7::text='' OR s.contest_id=NULLIF($7::text,'')::uuid)
AND ($8::text='' OR s.language=$8::text)
AND ($9::text='' OR (CASE WHEN s.status NOT IN ('Pending','Judging') AND EXISTS (
	 SELECT 1 FROM contests feedback_contest WHERE feedback_contest.id=s.contest_id
	 AND feedback_contest.feedback='none' AND feedback_contest.end_at>=now()
	 AND NOT ($2::boolean OR ($4::boolean AND feedback_contest.owner_id=NULLIF($3::text,'')::uuid)
	 OR EXISTS(SELECT 1 FROM contest_staff staff WHERE staff.contest_id=feedback_contest.id AND staff.user_id=NULLIF($3::text,'')::uuid))
	) THEN 'Submitted' ELSE s.status END)=$9::text)
ORDER BY s.submitted_at DESC,s.id DESC LIMIT $11::integer OFFSET $10::integer
`

type ListVisibleSubmissionsParams struct {
	DomainID       string
	IsManager      bool
	ViewerID       string
	ActiveMember   bool
	UserFilter     string
	ProblemFilter  string
	ContestFilter  string
	LanguageFilter string
	StatusFilter   string
	PageOffset     int
	PageLimit      int
}

type ListVisibleSubmissionsRow struct {
	ID              string
	PublicID        string
	UserID          string
	Username        string
	ProblemID       string
	ProblemPublicID string
	ProblemTitle    string
	Language        string
	Status          string
	Score           int
	TotalTimeMs     int
	PeakMemoryKb    int
	JudgedCases     int
	TotalCases      int
	ContestID       *string
	ContestPublicID string
	SubmittedAt     time.Time
	ProblemVersion  int
}

func (q *Queries) ListVisibleSubmissions(ctx context.Context, arg ListVisibleSubmissionsParams) ([]ListVisibleSubmissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleSubmissions,
		arg.DomainID,
		arg.IsManager,
		arg.ViewerID,
		arg.ActiveMember,
		arg.UserFilter,
		arg.ProblemFilter,
		arg.ContestFilter,
		arg.LanguageFilter,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleSubmissionsRow{}
	for rows.Next() {
		var i ListVisibleSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Username,
			&i.ProblemID,
			&i.ProblemPublicID,
			&i.ProblemTitle,
			&i.Language,
			&i.Status,
			&i.Score,
			&i.TotalTimeMs,
			&i.PeakMemoryKb,
			&i.JudgedCases,
			&i.TotalCases,
			&i.ContestID,
			&i.ContestPublicID,
			&i.SubmittedAt,
			&i.ProblemVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
