// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const countVisibleSubmissions = `-- name: CountVisibleSubmissions :one
SELECT count(*) FROM visible_submissions($1::uuid,$2::text,$3::boolean,$4::boolean,$5::boolean,$6::timestamptz) s JOIN users u ON u.id=s.user_id JOIN problems p ON p.id=s.problem_id
WHERE ($7::text='' OR s.user_id::text=$7::text OR u.username=$7::text)
AND ($8::text='' OR s.problem_id=NULLIF($8::text,'')::uuid)
AND ($9::text='' OR s.contest_id=NULLIF($9::text,'')::uuid)
AND ($10::text='' OR s.language=$10::text)
AND ($11::text='' OR (CASE WHEN EXISTS (SELECT 1 FROM contests frozen_contest
 WHERE frozen_contest.id=s.contest_id AND frozen_contest.domain_id=s.domain_id
 AND frozen_contest.rule <> 'oi' AND frozen_contest.freeze_at IS NOT NULL AND $6::timestamptz > frozen_contest.freeze_at
 AND s.submitted_at >= frozen_contest.freeze_at
 AND (frozen_contest.unfreeze_at IS NULL OR $6::timestamptz < frozen_contest.unfreeze_at)
 AND s.user_id <> NULLIF($2::text,'')::uuid
 AND NOT ($3::boolean OR ($4::boolean AND frozen_contest.owner_id=NULLIF($2::text,'')::uuid)
 OR EXISTS(SELECT 1 FROM contest_staff staff WHERE staff.contest_id=frozen_contest.id AND staff.user_id=NULLIF($2::text,'')::uuid))) THEN 'Pending' WHEN s.status NOT IN ('Pending','Judging') AND EXISTS (
	 SELECT 1 FROM contests feedback_contest WHERE feedback_contest.id=s.contest_id
	 AND (feedback_contest.rule='oi' OR feedback_contest.feedback='none') AND feedback_contest.end_at>=$6::timestamptz
	 AND NOT ($3::boolean OR ($4::boolean AND feedback_contest.owner_id=NULLIF($2::text,'')::uuid)
	 OR EXISTS(SELECT 1 FROM contest_staff staff WHERE staff.contest_id=feedback_contest.id AND staff.user_id=NULLIF($2::text,'')::uuid))
	) THEN 'Submitted' ELSE s.status END)=$11::text)
`

type CountVisibleSubmissionsParams struct {
	DomainID       string
	ViewerID       string
	IsManager      bool
	ActiveMember   bool
	CanSubmit      bool
	AsOf           time.Time
	UserFilter     string
	ProblemFilter  string
	ContestFilter  string
	LanguageFilter string
	StatusFilter   string
}

func (q *Queries) CountVisibleSubmissions(ctx context.Context, arg CountVisibleSubmissionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVisibleSubmissions,
		arg.DomainID,
		arg.ViewerID,
		arg.IsManager,
		arg.ActiveMember,
		arg.CanSubmit,
		arg.AsOf,
		arg.UserFilter,
		arg.ProblemFilter,
		arg.ContestFilter,
		arg.LanguageFilter,
		arg.StatusFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVisibleProgress = `-- name: GetVisibleProgress :one
SELECT (EXISTS (SELECT 1 FROM contests frozen_contest
 WHERE frozen_contest.id=s.contest_id AND frozen_contest.domain_id=s.domain_id
 AND frozen_contest.rule <> 'oi' AND frozen_contest.freeze_at IS NOT NULL AND $1::timestamptz > frozen_contest.freeze_at
 AND s.submitted_at >= frozen_contest.freeze_at
 AND (frozen_contest.unfreeze_at IS NULL OR $1::timestamptz < frozen_contest.unfreeze_at)
 AND s.user_id <> NULLIF($2::text,'')::uuid
 AND NOT ($3::boolean OR ($4::boolean AND frozen_contest.owner_id=NULLIF($2::text,'')::uuid)
 OR EXISTS(SELECT 1 FROM contest_staff staff WHERE staff.contest_id=frozen_contest.id AND staff.user_id=NULLIF($2::text,'')::uuid)))) AS frozen_result, s.id,s.public_id,s.user_id,s.problem_id,s.contest_id,s.status,s.score,s.total_time_ms,s.peak_memory_kb,s.compile_result,s.case_results,s.judged_cases,s.total_cases FROM visible_submissions($5::uuid,$2::text,$3::boolean,$4::boolean,$6::boolean,$1::timestamptz) s JOIN problems p ON p.id=s.problem_id
WHERE s.id=$7::uuid
`

type GetVisibleProgressParams struct {
	AsOf         time.Time
	ViewerID     string
	IsManager    bool
	ActiveMember bool
	DomainID     string
	CanSubmit    bool
	SubmissionID string
}

type GetVisibleProgressRow struct {
	FrozenResult  bool
	ID            string
	PublicID      string
	UserID        string
	ProblemID     string
	ContestID     *string
	Status        string
	Score         int
	TotalTimeMs   int
	PeakMemoryKb  int
	CompileResult string
	CaseResults   json.RawMessage
	JudgedCases   int
	TotalCases    int
}

func (q *Queries) GetVisibleProgress(ctx context.Context, arg GetVisibleProgressParams) (GetVisibleProgressRow, error) {
	row := q.db.QueryRowContext(ctx, getVisibleProgress,
		arg.AsOf,
		arg.ViewerID,
		arg.IsManager,
		arg.ActiveMember,
		arg.DomainID,
		arg.CanSubmit,
		arg.SubmissionID,
	)
	var i GetVisibleProgressRow
	err := row.Scan(
		&i.FrozenResult,
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ProblemID,
		&i.ContestID,
		&i.Status,
		&i.Score,
		&i.TotalTimeMs,
		&i.PeakMemoryKb,
		&i.CompileResult,
		&i.CaseResults,
		&i.JudgedCases,
		&i.TotalCases,
	)
	return i, err
}

const getVisibleSubmission = `-- name: GetVisibleSubmission :one
SELECT (EXISTS (SELECT 1 FROM contests frozen_contest
 WHERE frozen_contest.id=s.contest_id AND frozen_contest.domain_id=s.domain_id
 AND frozen_contest.rule <> 'oi' AND frozen_contest.freeze_at IS NOT NULL AND $1::timestamptz > frozen_contest.freeze_at
 AND s.submitted_at >= frozen_contest.freeze_at
 AND (frozen_contest.unfreeze_at IS NULL OR $1::timestamptz < frozen_contest.unfreeze_at)
 AND s.user_id <> NULLIF($2::text,'')::uuid
 AND NOT ($3::boolean OR ($4::boolean AND frozen_contest.owner_id=NULLIF($2::text,'')::uuid)
 OR EXISTS(SELECT 1 FROM contest_staff staff WHERE staff.contest_id=frozen_contest.id AND staff.user_id=NULLIF($2::text,'')::uuid)))) AS frozen_result, s.id,s.public_id,s.user_id,u.username,s.problem_id,p.public_id AS problem_public_id,v.title AS problem_title,s.language,s.status,s.score,s.total_time_ms,s.peak_memory_kb,s.judged_cases,s.total_cases,s.contest_id,COALESCE(c.public_id::text,'')::text AS contest_public_id,s.submitted_at,s.problem_version,s.source_code,s.compile_result,s.case_results,s.judged_at FROM visible_submissions($5::uuid,$2::text,$3::boolean,$4::boolean,$6::boolean,$1::timestamptz) s JOIN users u ON u.id=s.user_id JOIN problems p ON p.id=s.problem_id JOIN problem_versions v ON v.problem_id=s.problem_id AND v.version_no=s.problem_version LEFT JOIN contests c ON c.id=s.contest_id
WHERE s.id=$7::uuid
`

type GetVisibleSubmissionParams struct {
	AsOf         time.Time
	ViewerID     string
	IsManager    bool
	ActiveMember bool
	DomainID     string
	CanSubmit    bool
	SubmissionID string
}

type GetVisibleSubmissionRow struct {
	FrozenResult    bool
	ID              string
	PublicID        string
	UserID          string
	Username        string
	ProblemID       string
	ProblemPublicID string
	ProblemTitle    string
	Language        string
	Status          string
	Score           int
	TotalTimeMs     int
	PeakMemoryKb    int
	JudgedCases     int
	TotalCases      int
	ContestID       *string
	ContestPublicID string
	SubmittedAt     time.Time
	ProblemVersion  int
	SourceCode      string
	CompileResult   string
	CaseResults     json.RawMessage
	JudgedAt        *time.Time
}

func (q *Queries) GetVisibleSubmission(ctx context.Context, arg GetVisibleSubmissionParams) (GetVisibleSubmissionRow, error) {
	row := q.db.QueryRowContext(ctx, getVisibleSubmission,
		arg.AsOf,
		arg.ViewerID,
		arg.IsManager,
		arg.ActiveMember,
		arg.DomainID,
		arg.CanSubmit,
		arg.SubmissionID,
	)
	var i GetVisibleSubmissionRow
	err := row.Scan(
		&i.FrozenResult,
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Username,
		&i.ProblemID,
		&i.ProblemPublicID,
		&i.ProblemTitle,
		&i.Language,
		&i.Status,
		&i.Score,
		&i.TotalTimeMs,
		&i.PeakMemoryKb,
		&i.JudgedCases,
		&i.TotalCases,
		&i.ContestID,
		&i.ContestPublicID,
		&i.SubmittedAt,
		&i.ProblemVersion,
		&i.SourceCode,
		&i.CompileResult,
		&i.CaseResults,
		&i.JudgedAt,
	)
	return i, err
}

const listVisibleSubmissions = `-- name: ListVisibleSubmissions :many
SELECT (EXISTS (SELECT 1 FROM contests frozen_contest
 WHERE frozen_contest.id=s.contest_id AND frozen_contest.domain_id=s.domain_id
 AND frozen_contest.rule <> 'oi' AND frozen_contest.freeze_at IS NOT NULL AND $1::timestamptz > frozen_contest.freeze_at
 AND s.submitted_at >= frozen_contest.freeze_at
 AND (frozen_contest.unfreeze_at IS NULL OR $1::timestamptz < frozen_contest.unfreeze_at)
 AND s.user_id <> NULLIF($2::text,'')::uuid
 AND NOT ($3::boolean OR ($4::boolean AND frozen_contest.owner_id=NULLIF($2::text,'')::uuid)
 OR EXISTS(SELECT 1 FROM contest_staff staff WHERE staff.contest_id=frozen_contest.id AND staff.user_id=NULLIF($2::text,'')::uuid)))) AS frozen_result, s.id,s.public_id,s.user_id,u.username,s.problem_id,p.public_id AS problem_public_id,v.title AS problem_title,s.language,s.status,s.score,s.total_time_ms,s.peak_memory_kb,s.judged_cases,s.total_cases,s.contest_id,COALESCE(c.public_id::text,'')::text AS contest_public_id,s.submitted_at,s.problem_version FROM visible_submissions($5::uuid,$2::text,$3::boolean,$4::boolean,$6::boolean,$1::timestamptz) s JOIN users u ON u.id=s.user_id JOIN problems p ON p.id=s.problem_id JOIN problem_versions v ON v.problem_id=s.problem_id AND v.version_no=s.problem_version LEFT JOIN contests c ON c.id=s.contest_id
WHERE ($7::text='' OR s.user_id::text=$7::text OR u.username=$7::text)
AND ($8::text='' OR s.problem_id=NULLIF($8::text,'')::uuid)
AND ($9::text='' OR s.contest_id=NULLIF($9::text,'')::uuid)
AND ($10::text='' OR s.language=$10::text)
AND ($11::text='' OR (CASE WHEN EXISTS (SELECT 1 FROM contests frozen_contest
 WHERE frozen_contest.id=s.contest_id AND frozen_contest.domain_id=s.domain_id
 AND frozen_contest.rule <> 'oi' AND frozen_contest.freeze_at IS NOT NULL AND $1::timestamptz > frozen_contest.freeze_at
 AND s.submitted_at >= frozen_contest.freeze_at
 AND (frozen_contest.unfreeze_at IS NULL OR $1::timestamptz < frozen_contest.unfreeze_at)
 AND s.user_id <> NULLIF($2::text,'')::uuid
 AND NOT ($3::boolean OR ($4::boolean AND frozen_contest.owner_id=NULLIF($2::text,'')::uuid)
 OR EXISTS(SELECT 1 FROM contest_staff staff WHERE staff.contest_id=frozen_contest.id AND staff.user_id=NULLIF($2::text,'')::uuid))) THEN 'Pending' WHEN s.status NOT IN ('Pending','Judging') AND EXISTS (
	 SELECT 1 FROM contests feedback_contest WHERE feedback_contest.id=s.contest_id
	 AND (feedback_contest.rule='oi' OR feedback_contest.feedback='none') AND feedback_contest.end_at>=$1::timestamptz
	 AND NOT ($3::boolean OR ($4::boolean AND feedback_contest.owner_id=NULLIF($2::text,'')::uuid)
	 OR EXISTS(SELECT 1 FROM contest_staff staff WHERE staff.contest_id=feedback_contest.id AND staff.user_id=NULLIF($2::text,'')::uuid))
	) THEN 'Submitted' ELSE s.status END)=$11::text)
ORDER BY s.submitted_at DESC,s.id DESC LIMIT $13::integer OFFSET $12::integer
`

type ListVisibleSubmissionsParams struct {
	AsOf           time.Time
	ViewerID       string
	IsManager      bool
	ActiveMember   bool
	DomainID       string
	CanSubmit      bool
	UserFilter     string
	ProblemFilter  string
	ContestFilter  string
	LanguageFilter string
	StatusFilter   string
	PageOffset     int
	PageLimit      int
}

type ListVisibleSubmissionsRow struct {
	FrozenResult    bool
	ID              string
	PublicID        string
	UserID          string
	Username        string
	ProblemID       string
	ProblemPublicID string
	ProblemTitle    string
	Language        string
	Status          string
	Score           int
	TotalTimeMs     int
	PeakMemoryKb    int
	JudgedCases     int
	TotalCases      int
	ContestID       *string
	ContestPublicID string
	SubmittedAt     time.Time
	ProblemVersion  int
}

func (q *Queries) ListVisibleSubmissions(ctx context.Context, arg ListVisibleSubmissionsParams) ([]ListVisibleSubmissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleSubmissions,
		arg.AsOf,
		arg.ViewerID,
		arg.IsManager,
		arg.ActiveMember,
		arg.DomainID,
		arg.CanSubmit,
		arg.UserFilter,
		arg.ProblemFilter,
		arg.ContestFilter,
		arg.LanguageFilter,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleSubmissionsRow{}
	for rows.Next() {
		var i ListVisibleSubmissionsRow
		if err := rows.Scan(
			&i.FrozenResult,
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Username,
			&i.ProblemID,
			&i.ProblemPublicID,
			&i.ProblemTitle,
			&i.Language,
			&i.Status,
			&i.Score,
			&i.TotalTimeMs,
			&i.PeakMemoryKb,
			&i.JudgedCases,
			&i.TotalCases,
			&i.ContestID,
			&i.ContestPublicID,
			&i.SubmittedAt,
			&i.ProblemVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
