// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rejudging_write.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const cancelRejudging = `-- name: CancelRejudging :exec
UPDATE rejudgings SET state = 'cancelled', finished_at = now() WHERE id = $1
`

func (q *Queries) CancelRejudging(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, cancelRejudging, id)
	return err
}

const createRejudging = `-- name: CreateRejudging :one
INSERT INTO rejudgings (contest_id, problem_id, reason, total_count, created_by, domain_id)
		 VALUES ($1, $2, $3, $4, $5, $6)
		 RETURNING id, contest_id, problem_id, reason, state, total_count, created_by, created_at, finished_at
`

type CreateRejudgingParams struct {
	ContestID  *string
	ProblemID  *string
	Reason     string
	TotalCount int
	CreatedBy  *string
	DomainID   string
}

type CreateRejudgingRow struct {
	ID         string
	ContestID  *string
	ProblemID  *string
	Reason     string
	State      string
	TotalCount int
	CreatedBy  *string
	CreatedAt  time.Time
	FinishedAt *time.Time
}

func (q *Queries) CreateRejudging(ctx context.Context, arg CreateRejudgingParams) (CreateRejudgingRow, error) {
	row := q.db.QueryRowContext(ctx, createRejudging,
		arg.ContestID,
		arg.ProblemID,
		arg.Reason,
		arg.TotalCount,
		arg.CreatedBy,
		arg.DomainID,
	)
	var i CreateRejudgingRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ProblemID,
		&i.Reason,
		&i.State,
		&i.TotalCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteCancelledRejudgingCases = `-- name: DeleteCancelledRejudgingCases :exec
DELETE FROM submission_cases AS result
		 USING rejudging_submissions AS member, judge_jobs AS job, submissions AS sub
		 WHERE member.rejudging_id = $1
		   AND job.submission_id = member.submission_id
		   AND job.generation = member.generation
		   AND job.state = 'cancelled'
		   AND sub.id = member.submission_id
		   AND sub.judge_generation = member.generation
		   AND result.submission_id = member.submission_id
`

func (q *Queries) DeleteCancelledRejudgingCases(ctx context.Context, rejudgingID string) error {
	_, err := q.db.ExecContext(ctx, deleteCancelledRejudgingCases, rejudgingID)
	return err
}

const findRejudgingCandidates = `-- name: FindRejudgingCandidates :many
SELECT id FROM submissions WHERE domain_id = $1::uuid
 AND judged_at IS NOT NULL
 AND ($2::text = '' OR contest_id = NULLIF($2::text, '')::uuid)
 AND ($3::text = '' OR problem_id = NULLIF($3::text, '')::uuid)
 AND ($4::text = '' OR user_id = NULLIF($4::text, '')::uuid)
 AND ($5::text = '' OR language = $5::text)
 AND ($6::text = '' OR status = $6::text)
 AND (NOT $7::boolean OR id = ANY($8::uuid[]))
 AND (NOT $9::boolean OR contest_id IS NULL)
 ORDER BY submitted_at, id LIMIT $10::integer
`

type FindRejudgingCandidatesParams struct {
	DomainID       string
	ContestFilter  string
	ProblemFilter  string
	UserFilter     string
	LanguageFilter string
	StatusFilter   string
	FilterIds      bool
	SubmissionIds  []string
	PracticeOnly   bool
	BatchLimit     int
}

func (q *Queries) FindRejudgingCandidates(ctx context.Context, arg FindRejudgingCandidatesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, findRejudgingCandidates,
		arg.DomainID,
		arg.ContestFilter,
		arg.ProblemFilter,
		arg.UserFilter,
		arg.LanguageFilter,
		arg.StatusFilter,
		arg.FilterIds,
		pq.Array(arg.SubmissionIds),
		arg.PracticeOnly,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRejudgingTarget = `-- name: GetRejudgingTarget :one
SELECT contest_id,problem_id FROM rejudgings WHERE id=$1 AND domain_id=$2
`

type GetRejudgingTargetParams struct {
	ID       string
	DomainID string
}

type GetRejudgingTargetRow struct {
	ContestID *string
	ProblemID *string
}

func (q *Queries) GetRejudgingTarget(ctx context.Context, arg GetRejudgingTargetParams) (GetRejudgingTargetRow, error) {
	row := q.db.QueryRowContext(ctx, getRejudgingTarget, arg.ID, arg.DomainID)
	var i GetRejudgingTargetRow
	err := row.Scan(&i.ContestID, &i.ProblemID)
	return i, err
}

const lockActiveJudgeJobs = `-- name: LockActiveJudgeJobs :many
SELECT id FROM judge_jobs WHERE submission_id=ANY($1::uuid[]) AND state IN ('queued','running') ORDER BY id FOR UPDATE
`

func (q *Queries) LockActiveJudgeJobs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, lockActiveJudgeJobs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRejudging = `-- name: LockRejudging :one
SELECT state FROM rejudgings WHERE id = $1 AND domain_id = $2 FOR UPDATE
`

type LockRejudgingParams struct {
	ID       string
	DomainID string
}

func (q *Queries) LockRejudging(ctx context.Context, arg LockRejudgingParams) (string, error) {
	row := q.db.QueryRowContext(ctx, lockRejudging, arg.ID, arg.DomainID)
	var state string
	err := row.Scan(&state)
	return state, err
}

const lockRejudgingSnapshots = `-- name: LockRejudgingSnapshots :many
SELECT id, status, score, total_time_ms, peak_memory_kb, problem_version, compile_result, case_results, judged_cases, total_cases, judged_at
 FROM submissions WHERE domain_id = $1::uuid
 AND judged_at IS NOT NULL
 AND ($2::text = '' OR contest_id = NULLIF($2::text, '')::uuid)
 AND ($3::text = '' OR problem_id = NULLIF($3::text, '')::uuid)
 AND ($4::text = '' OR user_id = NULLIF($4::text, '')::uuid)
 AND ($5::text = '' OR language = $5::text)
 AND ($6::text = '' OR status = $6::text)
 AND (NOT $7::boolean OR id = ANY($8::uuid[]))
 AND (NOT $9::boolean OR contest_id IS NULL)
 AND id = ANY($10::uuid[])
 ORDER BY submitted_at, id LIMIT $11::integer FOR UPDATE
`

type LockRejudgingSnapshotsParams struct {
	DomainID       string
	ContestFilter  string
	ProblemFilter  string
	UserFilter     string
	LanguageFilter string
	StatusFilter   string
	FilterIds      bool
	SubmissionIds  []string
	PracticeOnly   bool
	CandidateIds   []string
	BatchLimit     int
}

type LockRejudgingSnapshotsRow struct {
	ID             string
	Status         string
	Score          int
	TotalTimeMs    int
	PeakMemoryKb   int
	ProblemVersion int
	CompileResult  string
	CaseResults    json.RawMessage
	JudgedCases    int
	TotalCases     int
	JudgedAt       *time.Time
}

func (q *Queries) LockRejudgingSnapshots(ctx context.Context, arg LockRejudgingSnapshotsParams) ([]LockRejudgingSnapshotsRow, error) {
	rows, err := q.db.QueryContext(ctx, lockRejudgingSnapshots,
		arg.DomainID,
		arg.ContestFilter,
		arg.ProblemFilter,
		arg.UserFilter,
		arg.LanguageFilter,
		arg.StatusFilter,
		arg.FilterIds,
		pq.Array(arg.SubmissionIds),
		arg.PracticeOnly,
		pq.Array(arg.CandidateIds),
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockRejudgingSnapshotsRow{}
	for rows.Next() {
		var i LockRejudgingSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Score,
			&i.TotalTimeMs,
			&i.PeakMemoryKb,
			&i.ProblemVersion,
			&i.CompileResult,
			&i.CaseResults,
			&i.JudgedCases,
			&i.TotalCases,
			&i.JudgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreCancelledRejudgingCases = `-- name: RestoreCancelledRejudgingCases :exec
INSERT INTO submission_cases
		   (submission_id, case_index, verdict, time_ms, memory_kb, exit_status, checker_output)
		 SELECT member.submission_id,
		        (item.value->>'caseIndex')::integer,
		        item.value->>'verdict',
		        COALESCE((item.value->>'timeMs')::integer, 0),
		        COALESCE((item.value->>'memoryKb')::integer, 0),
		        COALESCE(item.value->>'exitStatus', ''),
		        COALESCE(item.value->>'checkerOutput', '')
		 FROM rejudging_submissions AS member
		 JOIN judge_jobs AS job
		   ON job.submission_id = member.submission_id
		  AND job.generation = member.generation
		  AND job.state = 'cancelled'
		 JOIN submissions AS sub
		   ON sub.id = member.submission_id
		  AND sub.judge_generation = member.generation
		 CROSS JOIN LATERAL jsonb_array_elements(member.prior_case_results) AS item(value)
		 WHERE member.rejudging_id = $1
`

func (q *Queries) RestoreCancelledRejudgingCases(ctx context.Context, rejudgingID string) error {
	_, err := q.db.ExecContext(ctx, restoreCancelledRejudgingCases, rejudgingID)
	return err
}

const restoreQueuedRejudgingSubmissions = `-- name: RestoreQueuedRejudgingSubmissions :many
WITH cancelled AS (
		   UPDATE judge_jobs AS job
		   SET state = 'cancelled', finished_at = now()
		   FROM rejudging_submissions AS member
		   WHERE member.rejudging_id = $1
		     AND job.submission_id = member.submission_id
		     AND job.generation = member.generation
		     AND job.state = 'queued'
		   RETURNING job.submission_id, job.generation
		 )
		 UPDATE submissions AS sub
		 SET status = member.prior_status,
		     problem_version = member.prior_problem_version,
		     score = member.prior_score,
		     total_time_ms = member.prior_total_time_ms,
		     peak_memory_kb = member.prior_peak_memory_kb,
		     compile_result = member.prior_compile_result,
		     case_results = member.prior_case_results,
		     judged_cases = member.prior_judged_cases,
		     total_cases = member.prior_total_cases,
		     judged_at = member.prior_judged_at
		 FROM rejudging_submissions AS member
		 JOIN cancelled
		   ON cancelled.submission_id = member.submission_id
		  AND cancelled.generation = member.generation
		 WHERE member.rejudging_id = $1
		   AND sub.id = member.submission_id
		   AND sub.judge_generation = member.generation
		 RETURNING sub.id, sub.problem_id, sub.user_id, sub.contest_id
`

type RestoreQueuedRejudgingSubmissionsRow struct {
	ID        string
	ProblemID string
	UserID    string
	ContestID *string
}

func (q *Queries) RestoreQueuedRejudgingSubmissions(ctx context.Context, rejudgingID string) ([]RestoreQueuedRejudgingSubmissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, restoreQueuedRejudgingSubmissions, rejudgingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RestoreQueuedRejudgingSubmissionsRow{}
	for rows.Next() {
		var i RestoreQueuedRejudgingSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.UserID,
			&i.ContestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveRejudgingSnapshot = `-- name: SaveRejudgingSnapshot :exec
INSERT INTO rejudging_submissions
			   (rejudging_id, submission_id, generation, prior_status, prior_score,
			    prior_total_time_ms, prior_peak_memory_kb, prior_compile_result,
			    prior_case_results, prior_judged_cases, prior_total_cases, prior_judged_at, domain_id,prior_problem_version)
			 VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,$14)
`

type SaveRejudgingSnapshotParams struct {
	RejudgingID         string
	SubmissionID        string
	Generation          int
	PriorStatus         string
	PriorScore          int
	PriorTotalTimeMs    int
	PriorPeakMemoryKb   int
	PriorCompileResult  string
	PriorCaseResults    json.RawMessage
	PriorJudgedCases    int
	PriorTotalCases     int
	PriorJudgedAt       *time.Time
	DomainID            string
	PriorProblemVersion int
}

func (q *Queries) SaveRejudgingSnapshot(ctx context.Context, arg SaveRejudgingSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, saveRejudgingSnapshot,
		arg.RejudgingID,
		arg.SubmissionID,
		arg.Generation,
		arg.PriorStatus,
		arg.PriorScore,
		arg.PriorTotalTimeMs,
		arg.PriorPeakMemoryKb,
		arg.PriorCompileResult,
		arg.PriorCaseResults,
		arg.PriorJudgedCases,
		arg.PriorTotalCases,
		arg.PriorJudgedAt,
		arg.DomainID,
		arg.PriorProblemVersion,
	)
	return err
}
