// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rejudging_read.sql

package dbgen

import (
	"context"
	"time"
)

const finishRejudging = `-- name: FinishRejudging :one
UPDATE rejudgings SET state = 'finished', finished_at = now()
		 WHERE id = $1 AND state = 'running' AND domain_id = $2
		 RETURNING state, finished_at
`

type FinishRejudgingParams struct {
	BatchID  string
	DomainID string
}

type FinishRejudgingRow struct {
	State      string
	FinishedAt *time.Time
}

func (q *Queries) FinishRejudging(ctx context.Context, arg FinishRejudgingParams) (FinishRejudgingRow, error) {
	row := q.db.QueryRowContext(ctx, finishRejudging, arg.BatchID, arg.DomainID)
	var i FinishRejudgingRow
	err := row.Scan(&i.State, &i.FinishedAt)
	return i, err
}

const getRejudgingProgress = `-- name: GetRejudgingProgress :one
SELECT r.id, r.contest_id, r.problem_id, r.reason, r.state, r.total_count,
	r.created_by, r.created_at, r.finished_at,
	(SELECT count(*) FROM rejudging_submissions AS member
	   JOIN submissions AS sub ON sub.id = member.submission_id
	   WHERE member.rejudging_id = r.id
	     AND (sub.judge_generation > member.generation
	          OR (sub.judge_generation = member.generation AND sub.judged_at IS NOT NULL)))::integer AS done_count,
	(SELECT count(*) FROM rejudging_submissions AS member
	   JOIN submissions AS sub ON sub.id = member.submission_id
	   WHERE member.rejudging_id = r.id
	     AND sub.judge_generation = member.generation AND sub.judged_at IS NOT NULL
	     AND (sub.status <> member.prior_status OR sub.score <> member.prior_score))::integer AS changed_count FROM rejudgings AS r WHERE r.id = $1 AND r.domain_id = $2
`

type GetRejudgingProgressParams struct {
	BatchID  string
	DomainID string
}

type GetRejudgingProgressRow struct {
	ID           string
	ContestID    *string
	ProblemID    *string
	Reason       string
	State        string
	TotalCount   int
	CreatedBy    *string
	CreatedAt    time.Time
	FinishedAt   *time.Time
	DoneCount    int
	ChangedCount int
}

func (q *Queries) GetRejudgingProgress(ctx context.Context, arg GetRejudgingProgressParams) (GetRejudgingProgressRow, error) {
	row := q.db.QueryRowContext(ctx, getRejudgingProgress, arg.BatchID, arg.DomainID)
	var i GetRejudgingProgressRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ProblemID,
		&i.Reason,
		&i.State,
		&i.TotalCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.DoneCount,
		&i.ChangedCount,
	)
	return i, err
}

const listRejudgingChanges = `-- name: ListRejudgingChanges :many
SELECT member.submission_id, u.username, p.title AS problem_title,
		        member.prior_status, member.prior_score,
		        sub.status, sub.score,
		        (sub.judge_generation = member.generation AND sub.judged_at IS NOT NULL)::boolean AS judged
		 FROM rejudging_submissions AS member
		 JOIN submissions AS sub ON sub.id = member.submission_id
		 JOIN users AS u ON u.id = sub.user_id
		 JOIN problems AS p ON p.id = sub.problem_id
		 WHERE member.rejudging_id = $1 AND member.domain_id = $2
		   AND (sub.status <> member.prior_status OR sub.score <> member.prior_score)
		 ORDER BY sub.submitted_at
		 LIMIT $3
`

type ListRejudgingChangesParams struct {
	BatchID   string
	DomainID  string
	PageLimit int32
}

type ListRejudgingChangesRow struct {
	SubmissionID string
	Username     string
	ProblemTitle string
	PriorStatus  string
	PriorScore   int
	Status       string
	Score        int
	Judged       bool
}

func (q *Queries) ListRejudgingChanges(ctx context.Context, arg ListRejudgingChangesParams) ([]ListRejudgingChangesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRejudgingChanges, arg.BatchID, arg.DomainID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRejudgingChangesRow{}
	for rows.Next() {
		var i ListRejudgingChangesRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.Username,
			&i.ProblemTitle,
			&i.PriorStatus,
			&i.PriorScore,
			&i.Status,
			&i.Score,
			&i.Judged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRejudgings = `-- name: ListRejudgings :many
SELECT r.id, r.contest_id, r.problem_id, r.reason, r.state, r.total_count,
	r.created_by, r.created_at, r.finished_at,
	(SELECT count(*) FROM rejudging_submissions AS member
	   JOIN submissions AS sub ON sub.id = member.submission_id
	   WHERE member.rejudging_id = r.id
	     AND (sub.judge_generation > member.generation
	          OR (sub.judge_generation = member.generation AND sub.judged_at IS NOT NULL)))::integer AS done_count,
	(SELECT count(*) FROM rejudging_submissions AS member
	   JOIN submissions AS sub ON sub.id = member.submission_id
	   WHERE member.rejudging_id = r.id
	     AND sub.judge_generation = member.generation AND sub.judged_at IS NOT NULL
	     AND (sub.status <> member.prior_status OR sub.score <> member.prior_score))::integer AS changed_count FROM rejudgings AS r
		 WHERE ($1::text = '' OR r.contest_id = NULLIF($1::text, '')::uuid) AND r.domain_id = $2
		 AND ($3::boolean OR ($4::boolean AND (
		   EXISTS(SELECT 1 FROM contests c WHERE c.id=r.contest_id AND (c.owner_id=$5 OR EXISTS(SELECT 1 FROM contest_staff s WHERE s.contest_id=c.id AND s.user_id=$5)))
		   OR (r.contest_id IS NULL AND EXISTS(SELECT 1 FROM problems p WHERE p.id=r.problem_id AND (p.owner_id=$5 OR EXISTS(
		     SELECT 1 FROM problem_access a WHERE a.problem_id=p.id AND (a.user_id=$5 OR a.group_id IN (SELECT group_id FROM domain_group_members WHERE domain_id=$2 AND user_id=$5))))))
		 ))) ORDER BY r.created_at DESC LIMIT $6
`

type ListRejudgingsParams struct {
	ContestFilter string
	DomainID      string
	CanManage     bool
	ActiveMember  bool
	ViewerID      string
	PageLimit     int32
}

type ListRejudgingsRow struct {
	ID           string
	ContestID    *string
	ProblemID    *string
	Reason       string
	State        string
	TotalCount   int
	CreatedBy    *string
	CreatedAt    time.Time
	FinishedAt   *time.Time
	DoneCount    int
	ChangedCount int
}

func (q *Queries) ListRejudgings(ctx context.Context, arg ListRejudgingsParams) ([]ListRejudgingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRejudgings,
		arg.ContestFilter,
		arg.DomainID,
		arg.CanManage,
		arg.ActiveMember,
		arg.ViewerID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRejudgingsRow{}
	for rows.Next() {
		var i ListRejudgingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.ProblemID,
			&i.Reason,
			&i.State,
			&i.TotalCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.DoneCount,
			&i.ChangedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
