// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requeue.sql

package dbgen

import (
	"context"
)

const cancelActiveJudgeJobs = `-- name: CancelActiveJudgeJobs :exec
UPDATE judge_jobs SET state = 'cancelled', finished_at = now()
		 WHERE submission_id = $1::uuid AND state IN ('queued', 'running')
		 AND EXISTS (SELECT 1 FROM submission_results WHERE submission_results.id = $1::uuid AND submission_results.domain_id = $2::uuid)
`

type CancelActiveJudgeJobsParams struct {
	SubmissionID string
	DomainID     string
}

func (q *Queries) CancelActiveJudgeJobs(ctx context.Context, arg CancelActiveJudgeJobsParams) error {
	_, err := q.db.ExecContext(ctx, cancelActiveJudgeJobs, arg.SubmissionID, arg.DomainID)
	return err
}

const enqueueJudgeGeneration = `-- name: EnqueueJudgeGeneration :exec
INSERT INTO judge_jobs (submission_id, generation) VALUES ($1::uuid, $2::integer)
`

type EnqueueJudgeGenerationParams struct {
	SubmissionID string
	Generation   int
}

func (q *Queries) EnqueueJudgeGeneration(ctx context.Context, arg EnqueueJudgeGenerationParams) error {
	_, err := q.db.ExecContext(ctx, enqueueJudgeGeneration, arg.SubmissionID, arg.Generation)
	return err
}

const getSubmissionRejudgeTarget = `-- name: GetSubmissionRejudgeTarget :one
SELECT contest_id,problem_id FROM submission_results WHERE submission_results.id =$1::uuid AND domain_id=$2::uuid
`

type GetSubmissionRejudgeTargetParams struct {
	SubmissionID string
	DomainID     string
}

type GetSubmissionRejudgeTargetRow struct {
	ContestID *string
	ProblemID string
}

func (q *Queries) GetSubmissionRejudgeTarget(ctx context.Context, arg GetSubmissionRejudgeTargetParams) (GetSubmissionRejudgeTargetRow, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionRejudgeTarget, arg.SubmissionID, arg.DomainID)
	var i GetSubmissionRejudgeTargetRow
	err := row.Scan(&i.ContestID, &i.ProblemID)
	return i, err
}

const lockRejudgeGeneration = `-- name: LockRejudgeGeneration :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text,0))
`

func (q *Queries) LockRejudgeGeneration(ctx context.Context, lockKey string) error {
	_, err := q.db.ExecContext(ctx, lockRejudgeGeneration, lockKey)
	return err
}

const recordRejudgeAudit = `-- name: RecordRejudgeAudit :exec
INSERT INTO domain_audit_events(domain_id,actor_id,action,target) VALUES($1::uuid,$2::uuid,$3::text,$4::text)
`

type RecordRejudgeAuditParams struct {
	DomainID string
	ActorID  string
	Action   string
	Target   string
}

func (q *Queries) RecordRejudgeAudit(ctx context.Context, arg RecordRejudgeAuditParams) error {
	_, err := q.db.ExecContext(ctx, recordRejudgeAudit,
		arg.DomainID,
		arg.ActorID,
		arg.Action,
		arg.Target,
	)
	return err
}

const resetSubmissionForRejudge = `-- name: ResetSubmissionForRejudge :one
WITH target AS (
 UPDATE submissions SET judge_generation=judge_generation+1,result_generation=judge_generation+1
 WHERE id=$1::uuid AND domain_id=$2::uuid
 RETURNING id, domain_id, public_id, user_id, problem_id, initial_problem_version, contest_id, language, source_code, submitted_at, judge_generation, result_generation
), evaluation AS (
 INSERT INTO judgements(submission_id,generation,problem_id,problem_version)
 SELECT t.id,t.judge_generation,t.problem_id,
        CASE WHEN t.contest_id IS NULL THEN p.published_version ELSE cp.problem_version END
 FROM target t JOIN problems p ON p.id=t.problem_id
 LEFT JOIN contest_problems cp ON cp.contest_id=t.contest_id AND cp.problem_id=t.problem_id
 RETURNING submission_id
)
SELECT t.judge_generation,t.problem_id,t.user_id,t.contest_id FROM target t JOIN evaluation j ON j.submission_id=t.id
`

type ResetSubmissionForRejudgeParams struct {
	SubmissionID string
	DomainID     string
}

type ResetSubmissionForRejudgeRow struct {
	JudgeGeneration int
	ProblemID       string
	UserID          string
	ContestID       *string
}

func (q *Queries) ResetSubmissionForRejudge(ctx context.Context, arg ResetSubmissionForRejudgeParams) (ResetSubmissionForRejudgeRow, error) {
	row := q.db.QueryRowContext(ctx, resetSubmissionForRejudge, arg.SubmissionID, arg.DomainID)
	var i ResetSubmissionForRejudgeRow
	err := row.Scan(
		&i.JudgeGeneration,
		&i.ProblemID,
		&i.UserID,
		&i.ContestID,
	)
	return i, err
}
