// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requeue.sql

package dbgen

import (
	"context"
)

const cancelActiveJudgeJobs = `-- name: CancelActiveJudgeJobs :exec
UPDATE judge_jobs SET state = 'cancelled', finished_at = now()
		 WHERE submission_id = $1::uuid AND state IN ('queued', 'running')
		 AND EXISTS (SELECT 1 FROM submissions WHERE submissions.id = $1::uuid AND submissions.domain_id = $2::uuid)
`

type CancelActiveJudgeJobsParams struct {
	SubmissionID string
	DomainID     string
}

func (q *Queries) CancelActiveJudgeJobs(ctx context.Context, arg CancelActiveJudgeJobsParams) error {
	_, err := q.db.ExecContext(ctx, cancelActiveJudgeJobs, arg.SubmissionID, arg.DomainID)
	return err
}

const deleteSubmissionCases = `-- name: DeleteSubmissionCases :exec
DELETE FROM submission_cases WHERE submission_id = $1::uuid
`

func (q *Queries) DeleteSubmissionCases(ctx context.Context, submissionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSubmissionCases, submissionID)
	return err
}

const enqueueJudgeGeneration = `-- name: EnqueueJudgeGeneration :exec
INSERT INTO judge_jobs (submission_id, generation) VALUES ($1::uuid, $2::integer)
`

type EnqueueJudgeGenerationParams struct {
	SubmissionID string
	Generation   int
}

func (q *Queries) EnqueueJudgeGeneration(ctx context.Context, arg EnqueueJudgeGenerationParams) error {
	_, err := q.db.ExecContext(ctx, enqueueJudgeGeneration, arg.SubmissionID, arg.Generation)
	return err
}

const getSubmissionRejudgeTarget = `-- name: GetSubmissionRejudgeTarget :one
SELECT contest_id,problem_id FROM submissions WHERE submissions.id =$1::uuid AND domain_id=$2::uuid
`

type GetSubmissionRejudgeTargetParams struct {
	SubmissionID string
	DomainID     string
}

type GetSubmissionRejudgeTargetRow struct {
	ContestID *string
	ProblemID string
}

func (q *Queries) GetSubmissionRejudgeTarget(ctx context.Context, arg GetSubmissionRejudgeTargetParams) (GetSubmissionRejudgeTargetRow, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionRejudgeTarget, arg.SubmissionID, arg.DomainID)
	var i GetSubmissionRejudgeTargetRow
	err := row.Scan(&i.ContestID, &i.ProblemID)
	return i, err
}

const lockRejudgeGeneration = `-- name: LockRejudgeGeneration :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text,0))
`

func (q *Queries) LockRejudgeGeneration(ctx context.Context, lockKey string) error {
	_, err := q.db.ExecContext(ctx, lockRejudgeGeneration, lockKey)
	return err
}

const recordRejudgeAudit = `-- name: RecordRejudgeAudit :exec
INSERT INTO domain_audit_events(domain_id,actor_id,action,target) VALUES($1::uuid,$2::uuid,$3::text,$4::text)
`

type RecordRejudgeAuditParams struct {
	DomainID string
	ActorID  string
	Action   string
	Target   string
}

func (q *Queries) RecordRejudgeAudit(ctx context.Context, arg RecordRejudgeAuditParams) error {
	_, err := q.db.ExecContext(ctx, recordRejudgeAudit,
		arg.DomainID,
		arg.ActorID,
		arg.Action,
		arg.Target,
	)
	return err
}

const resetSubmissionForRejudge = `-- name: ResetSubmissionForRejudge :one
UPDATE submissions SET status = 'Pending', judged_at = NULL, score = 0,
		                        problem_version=CASE WHEN contest_id IS NULL THEN (SELECT published_version FROM problems WHERE problems.id =submissions.problem_id)
		                          ELSE COALESCE((SELECT cp.problem_version FROM contest_problems cp WHERE cp.contest_id=submissions.contest_id AND cp.problem_id=submissions.problem_id),problem_version) END,
		                        total_time_ms = 0, peak_memory_kb = 0,
		                        compile_result = '', case_results = '[]'::jsonb,
		                        judged_cases = 0, total_cases = 0,
		                        judge_generation = judge_generation + 1
		 WHERE submissions.id = $1::uuid AND submissions.domain_id = $2::uuid
		 RETURNING judge_generation, problem_id, user_id, contest_id
`

type ResetSubmissionForRejudgeParams struct {
	SubmissionID string
	DomainID     string
}

type ResetSubmissionForRejudgeRow struct {
	JudgeGeneration int
	ProblemID       string
	UserID          string
	ContestID       *string
}

func (q *Queries) ResetSubmissionForRejudge(ctx context.Context, arg ResetSubmissionForRejudgeParams) (ResetSubmissionForRejudgeRow, error) {
	row := q.db.QueryRowContext(ctx, resetSubmissionForRejudge, arg.SubmissionID, arg.DomainID)
	var i ResetSubmissionForRejudgeRow
	err := row.Scan(
		&i.JudgeGeneration,
		&i.ProblemID,
		&i.UserID,
		&i.ContestID,
	)
	return i, err
}
