-- name: CountVisibleEditorials :one
SELECT count(*) FROM editorials e JOIN problems p ON p.id=e.problem_id LEFT JOIN users u ON u.id=e.author_id
WHERE e.domain_id=sqlc.arg(domain_id)::uuid AND (p.visibility='public' AND p.published_version IS NOT NULL OR sqlc.arg(is_manager)::boolean OR (sqlc.arg(active_member)::boolean AND (p.owner_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid OR EXISTS(SELECT 1 FROM problem_access a WHERE a.problem_id=p.id AND a.domain_id=p.domain_id AND (a.user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid OR a.group_id IN(SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid)))))) AND ((e.visibility='public' AND e.status='published') OR sqlc.arg(is_manager)::boolean OR (sqlc.arg(active_member)::boolean AND e.author_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid)) AND (sqlc.arg(problem_filter)::text='' OR e.problem_id=NULLIF(sqlc.arg(problem_filter)::text,'')::uuid) AND (sqlc.arg(author_filter)::text='' OR e.author_id=NULLIF(sqlc.arg(author_filter)::text,'')::uuid) AND (sqlc.arg(keyword)::text='' OR e.title ILIKE '%'||sqlc.arg(keyword)::text||'%' OR p.title ILIKE '%'||sqlc.arg(keyword)::text||'%');

-- name: ListVisibleEditorials :many
SELECT e.id,e.public_id,e.problem_id,p.public_id AS problem_public_id,p.title AS problem_title,e.author_id,COALESCE(u.username,'') AS author_name,e.title,e.visibility,e.status,e.solved_only,e.vote_count,EXISTS(SELECT 1 FROM editorial_votes votes WHERE votes.editorial_id=e.id AND votes.user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid) AS voted,e.created_at,e.updated_at,e.domain_id,p.owner_id AS problem_owner_id,EXISTS(SELECT 1 FROM submissions sub WHERE sub.domain_id=e.domain_id AND sub.problem_id=e.problem_id AND sub.user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid AND sub.contest_id IS NULL AND sub.status='Accepted') AS solved,''::text AS content_md FROM editorials e JOIN problems p ON p.id=e.problem_id LEFT JOIN users u ON u.id=e.author_id
WHERE e.domain_id=sqlc.arg(domain_id)::uuid AND (p.visibility='public' AND p.published_version IS NOT NULL OR sqlc.arg(is_manager)::boolean OR (sqlc.arg(active_member)::boolean AND (p.owner_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid OR EXISTS(SELECT 1 FROM problem_access a WHERE a.problem_id=p.id AND a.domain_id=p.domain_id AND (a.user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid OR a.group_id IN(SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid)))))) AND ((e.visibility='public' AND e.status='published') OR sqlc.arg(is_manager)::boolean OR (sqlc.arg(active_member)::boolean AND e.author_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid)) AND (sqlc.arg(problem_filter)::text='' OR e.problem_id=NULLIF(sqlc.arg(problem_filter)::text,'')::uuid) AND (sqlc.arg(author_filter)::text='' OR e.author_id=NULLIF(sqlc.arg(author_filter)::text,'')::uuid) AND (sqlc.arg(keyword)::text='' OR e.title ILIKE '%'||sqlc.arg(keyword)::text||'%' OR p.title ILIKE '%'||sqlc.arg(keyword)::text||'%')
ORDER BY CASE WHEN sqlc.arg(sort_votes)::boolean THEN e.vote_count ELSE 0 END DESC,e.created_at DESC,e.id DESC LIMIT sqlc.arg(page_limit)::integer OFFSET sqlc.arg(page_offset)::integer;

-- name: GetVisibleEditorial :one
SELECT e.id,e.public_id,e.problem_id,p.public_id AS problem_public_id,p.title AS problem_title,e.author_id,COALESCE(u.username,'') AS author_name,e.title,e.visibility,e.status,e.solved_only,e.vote_count,EXISTS(SELECT 1 FROM editorial_votes votes WHERE votes.editorial_id=e.id AND votes.user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid) AS voted,e.created_at,e.updated_at,e.domain_id,p.owner_id AS problem_owner_id,EXISTS(SELECT 1 FROM submissions sub WHERE sub.domain_id=e.domain_id AND sub.problem_id=e.problem_id AND sub.user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid AND sub.contest_id IS NULL AND sub.status='Accepted') AS solved,CASE WHEN (NOT e.solved_only OR (sqlc.arg(active_member)::boolean AND e.author_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid) OR (sqlc.arg(is_manager)::boolean OR (sqlc.arg(active_member)::boolean AND p.owner_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid)) OR EXISTS(SELECT 1 FROM submissions sub WHERE sub.domain_id=e.domain_id AND sub.problem_id=e.problem_id AND sub.user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid AND sub.contest_id IS NULL AND sub.status='Accepted')) THEN e.content_md ELSE '' END::text AS content_md FROM editorials e JOIN problems p ON p.id=e.problem_id LEFT JOIN users u ON u.id=e.author_id
WHERE e.domain_id=sqlc.arg(domain_id)::uuid AND (p.visibility='public' AND p.published_version IS NOT NULL OR sqlc.arg(is_manager)::boolean OR (sqlc.arg(active_member)::boolean AND (p.owner_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid OR EXISTS(SELECT 1 FROM problem_access a WHERE a.problem_id=p.id AND a.domain_id=p.domain_id AND (a.user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid OR a.group_id IN(SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid)))))) AND ((e.visibility='public' AND e.status='published') OR sqlc.arg(is_manager)::boolean OR (sqlc.arg(active_member)::boolean AND e.author_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid)) AND e.id=sqlc.arg(editorial_id)::uuid;

-- name: LockVisibleEditorial :one
SELECT e.id,e.public_id,e.problem_id,p.public_id AS problem_public_id,p.title AS problem_title,e.author_id,COALESCE(u.username,'') AS author_name,e.title,e.visibility,e.status,e.solved_only,e.vote_count,EXISTS(SELECT 1 FROM editorial_votes votes WHERE votes.editorial_id=e.id AND votes.user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid) AS voted,e.created_at,e.updated_at,e.domain_id,p.owner_id AS problem_owner_id,EXISTS(SELECT 1 FROM submissions sub WHERE sub.domain_id=e.domain_id AND sub.problem_id=e.problem_id AND sub.user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid AND sub.contest_id IS NULL AND sub.status='Accepted') AS solved,CASE WHEN (NOT e.solved_only OR (sqlc.arg(active_member)::boolean AND e.author_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid) OR (sqlc.arg(is_manager)::boolean OR (sqlc.arg(active_member)::boolean AND p.owner_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid)) OR EXISTS(SELECT 1 FROM submissions sub WHERE sub.domain_id=e.domain_id AND sub.problem_id=e.problem_id AND sub.user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid AND sub.contest_id IS NULL AND sub.status='Accepted')) THEN e.content_md ELSE '' END::text AS content_md FROM editorials e JOIN problems p ON p.id=e.problem_id LEFT JOIN users u ON u.id=e.author_id
WHERE e.domain_id=sqlc.arg(domain_id)::uuid AND (p.visibility='public' AND p.published_version IS NOT NULL OR sqlc.arg(is_manager)::boolean OR (sqlc.arg(active_member)::boolean AND (p.owner_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid OR EXISTS(SELECT 1 FROM problem_access a WHERE a.problem_id=p.id AND a.domain_id=p.domain_id AND (a.user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid OR a.group_id IN(SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid)))))) AND ((e.visibility='public' AND e.status='published') OR sqlc.arg(is_manager)::boolean OR (sqlc.arg(active_member)::boolean AND e.author_id=NULLIF(sqlc.arg(viewer_id)::text,'')::uuid)) AND e.id=sqlc.arg(editorial_id)::uuid FOR UPDATE OF e;

-- name: GetPost :one
SELECT d.id,d.problem_id,d.editorial_id,d.author_id,COALESCE(u.username,'') AS author_name,d.content_md,d.parent_id,d.created_at,d.updated_at,d.domain_id FROM discussion_posts d LEFT JOIN users u ON u.id=d.author_id WHERE d.domain_id=sqlc.arg(domain_id)::uuid AND d.id=sqlc.arg(post_id)::bigint;

-- name: LockPost :one
SELECT d.id,d.problem_id,d.editorial_id,d.author_id,COALESCE(u.username,'') AS author_name,d.content_md,d.parent_id,d.created_at,d.updated_at,d.domain_id FROM discussion_posts d LEFT JOIN users u ON u.id=d.author_id WHERE d.domain_id=sqlc.arg(domain_id)::uuid AND d.id=sqlc.arg(post_id)::bigint FOR UPDATE OF d;

-- name: ListProblemPosts :many
SELECT d.id,d.problem_id,d.editorial_id,d.author_id,COALESCE(u.username,'') AS author_name,d.content_md,d.parent_id,d.created_at,d.updated_at,d.domain_id FROM discussion_posts d LEFT JOIN users u ON u.id=d.author_id WHERE d.domain_id=sqlc.arg(domain_id)::uuid AND d.problem_id=sqlc.arg(target_id)::uuid ORDER BY d.created_at,d.id;

-- name: CheckProblemParent :one
SELECT 1 FROM discussion_posts WHERE id=sqlc.arg(parent_id)::bigint AND domain_id=sqlc.arg(domain_id)::uuid AND problem_id=sqlc.arg(target_id)::uuid FOR SHARE;

-- name: CreateProblemPost :one
INSERT INTO discussion_posts(domain_id,problem_id,author_id,content_md,parent_id) VALUES(sqlc.arg(domain_id)::uuid,sqlc.arg(target_id)::uuid,sqlc.arg(user_id)::uuid,sqlc.arg(body)::text,sqlc.narg(parent_id)::bigint) RETURNING id;

-- name: ListEditorialPosts :many
SELECT d.id,d.problem_id,d.editorial_id,d.author_id,COALESCE(u.username,'') AS author_name,d.content_md,d.parent_id,d.created_at,d.updated_at,d.domain_id FROM discussion_posts d LEFT JOIN users u ON u.id=d.author_id WHERE d.domain_id=sqlc.arg(domain_id)::uuid AND d.editorial_id=sqlc.arg(target_id)::uuid ORDER BY d.created_at,d.id;

-- name: CheckEditorialParent :one
SELECT 1 FROM discussion_posts WHERE id=sqlc.arg(parent_id)::bigint AND domain_id=sqlc.arg(domain_id)::uuid AND editorial_id=sqlc.arg(target_id)::uuid FOR SHARE;

-- name: CreateEditorialPost :one
INSERT INTO discussion_posts(domain_id,editorial_id,author_id,content_md,parent_id) VALUES(sqlc.arg(domain_id)::uuid,sqlc.arg(target_id)::uuid,sqlc.arg(user_id)::uuid,sqlc.arg(body)::text,sqlc.narg(parent_id)::bigint) RETURNING id;
