// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const claimJudgeJob = `-- name: ClaimJudgeJob :one
WITH candidate AS (
		   SELECT id FROM judge_jobs
		   WHERE (state = 'queued' AND available_at <= now())
		      OR (state = 'running' AND lease_expires_at < now() AND judge_jobs.attempt < $1::integer)
		   ORDER BY priority DESC, available_at, created_at
		   FOR UPDATE SKIP LOCKED
		   LIMIT 1
		 ), claimed AS (
		   UPDATE judge_jobs AS job
		   SET state = 'running', attempt = job.attempt + 1, worker_id = $2::text,
		       lease_token = gen_random_uuid(),
		       lease_expires_at = now() + ($3::bigint * interval '1 millisecond'),
		       started_at = COALESCE(job.started_at, now()), last_error = ''
		   FROM candidate
		   WHERE job.id = candidate.id
		   RETURNING job.id, job.submission_id, job.domain_id, job.problem_id, job.problem_version, job.generation, job.state, job.priority, job.attempt, job.available_at, job.worker_id, job.lease_token, job.lease_expires_at, job.last_error, job.created_at, job.started_at, job.finished_at
		 ), marked AS (
		   -- total_cases is known the moment the job is dispatched, so the UI can
		   -- render "0 / N" instead of an unbounded spinner.
		   UPDATE submissions AS sub
		   SET status = 'Judging', judged_cases = 0,
		       total_cases = (SELECT v.case_count FROM problem_versions v WHERE v.problem_id=claimed.problem_id AND v.version_no=claimed.problem_version)
		   FROM claimed
		   WHERE sub.id = claimed.submission_id
		     AND sub.judge_generation = claimed.generation
		 )
		 SELECT claimed.id, claimed.submission_id, claimed.generation, claimed.attempt,
		        claimed.worker_id, claimed.lease_token, claimed.lease_expires_at,
		        sub.user_id, sub.problem_id, sub.contest_id, sub.language, sub.source_code,
		        version.time_limit_ms, version.memory_limit_kb,
		        version.testdata_path,version.artifact_version,version.sha256,version.case_count,version.checker,
		        claimed.domain_id,claimed.problem_version
		 FROM claimed
		 JOIN submissions AS sub ON sub.id = claimed.submission_id
		 JOIN problem_versions version ON version.problem_id=claimed.problem_id AND version.version_no=claimed.problem_version
`

type ClaimJudgeJobParams struct {
	MaxAttempts int
	WorkerID    string
	LeaseMillis int64
}

type ClaimJudgeJobRow struct {
	ID              string
	SubmissionID    string
	Generation      int
	Attempt         int
	WorkerID        sql.NullString
	LeaseToken      *string
	LeaseExpiresAt  *time.Time
	UserID          string
	ProblemID       string
	ContestID       *string
	Language        string
	SourceCode      string
	TimeLimitMs     int
	MemoryLimitKb   int
	TestdataPath    string
	ArtifactVersion int
	Sha256          string
	CaseCount       int
	Checker         string
	DomainID        string
	ProblemVersion  int
}

func (q *Queries) ClaimJudgeJob(ctx context.Context, arg ClaimJudgeJobParams) (ClaimJudgeJobRow, error) {
	row := q.db.QueryRowContext(ctx, claimJudgeJob, arg.MaxAttempts, arg.WorkerID, arg.LeaseMillis)
	var i ClaimJudgeJobRow
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Generation,
		&i.Attempt,
		&i.WorkerID,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.UserID,
		&i.ProblemID,
		&i.ContestID,
		&i.Language,
		&i.SourceCode,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.TestdataPath,
		&i.ArtifactVersion,
		&i.Sha256,
		&i.CaseCount,
		&i.Checker,
		&i.DomainID,
		&i.ProblemVersion,
	)
	return i, err
}

const completeJudgeJob = `-- name: CompleteJudgeJob :execrows
UPDATE judge_jobs SET state = 'completed', finished_at = now(), lease_expires_at = NULL
		 WHERE judge_jobs.id = $1::uuid AND generation = $2::integer AND lease_token = $3::uuid
		   AND worker_id = $4::text AND state = 'running' AND lease_expires_at >= now()
`

type CompleteJudgeJobParams struct {
	JobID      string
	Generation int
	LeaseToken string
	WorkerID   string
}

func (q *Queries) CompleteJudgeJob(ctx context.Context, arg CompleteJudgeJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeJudgeJob,
		arg.JobID,
		arg.Generation,
		arg.LeaseToken,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSubmissionCases = `-- name: DeleteSubmissionCases :exec
DELETE FROM submission_cases WHERE submission_id = $1::uuid
`

func (q *Queries) DeleteSubmissionCases(ctx context.Context, submissionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSubmissionCases, submissionID)
	return err
}

const failExhaustedJudgeJobs = `-- name: FailExhaustedJudgeJobs :many
UPDATE judge_jobs SET state = 'dead', finished_at = now(), last_error = 'worker lease expired too many times'
		 WHERE state = 'running' AND lease_expires_at < now() AND attempt >= $1::integer
		 RETURNING submission_id, generation
`

type FailExhaustedJudgeJobsRow struct {
	SubmissionID string
	Generation   int
}

func (q *Queries) FailExhaustedJudgeJobs(ctx context.Context, maxAttempts int) ([]FailExhaustedJudgeJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, failExhaustedJudgeJobs, maxAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailExhaustedJudgeJobsRow{}
	for rows.Next() {
		var i FailExhaustedJudgeJobsRow
		if err := rows.Scan(&i.SubmissionID, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failSubmissionForExpiredLease = `-- name: FailSubmissionForExpiredLease :one
UPDATE submissions SET status = 'System Error', score = 0,
			        total_time_ms = 0, peak_memory_kb = 0, case_results = '[]'::jsonb,
			        compile_result = $1::text, judged_at = now()
			 WHERE id = $2::uuid AND judge_generation = $3::integer
			 RETURNING problem_id, user_id, contest_id
`

type FailSubmissionForExpiredLeaseParams struct {
	CompileResult string
	SubmissionID  string
	Generation    int
}

type FailSubmissionForExpiredLeaseRow struct {
	ProblemID string
	UserID    string
	ContestID *string
}

func (q *Queries) FailSubmissionForExpiredLease(ctx context.Context, arg FailSubmissionForExpiredLeaseParams) (FailSubmissionForExpiredLeaseRow, error) {
	row := q.db.QueryRowContext(ctx, failSubmissionForExpiredLease, arg.CompileResult, arg.SubmissionID, arg.Generation)
	var i FailSubmissionForExpiredLeaseRow
	err := row.Scan(&i.ProblemID, &i.UserID, &i.ContestID)
	return i, err
}

const insertSubmissionCase = `-- name: InsertSubmissionCase :exec
INSERT INTO submission_cases
			 (submission_id, case_index, verdict, time_ms, memory_kb, exit_status, checker_output)
			 VALUES ($1::uuid, $2::integer, $3::text, $4::integer, $5::integer, $6::text, $7::text)
`

type InsertSubmissionCaseParams struct {
	SubmissionID  string
	CaseIndex     int
	Verdict       string
	TimeMs        int
	MemoryKb      int
	ExitStatus    string
	CheckerOutput string
}

func (q *Queries) InsertSubmissionCase(ctx context.Context, arg InsertSubmissionCaseParams) error {
	_, err := q.db.ExecContext(ctx, insertSubmissionCase,
		arg.SubmissionID,
		arg.CaseIndex,
		arg.Verdict,
		arg.TimeMs,
		arg.MemoryKb,
		arg.ExitStatus,
		arg.CheckerOutput,
	)
	return err
}

const listenJudgeJobs = `-- name: ListenJudgeJobs :exec
LISTEN vertex_judge_jobs
`

func (q *Queries) ListenJudgeJobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, listenJudgeJobs)
	return err
}

const lockJudgeResultTarget = `-- name: LockJudgeResultTarget :one
SELECT job.state, job.submission_id, sub.problem_id, sub.user_id, sub.contest_id,
		        COALESCE(job.worker_id, '') AS worker_id, COALESCE(job.lease_token::text, '')::text AS lease_token
		 FROM judge_jobs AS job
		 JOIN submissions AS sub ON sub.id = job.submission_id
		 WHERE job.id = $1::uuid AND job.generation = $2::integer
		 FOR UPDATE OF job, sub
`

type LockJudgeResultTargetParams struct {
	JobID      string
	Generation int
}

type LockJudgeResultTargetRow struct {
	State        string
	SubmissionID string
	ProblemID    string
	UserID       string
	ContestID    *string
	WorkerID     string
	LeaseToken   string
}

func (q *Queries) LockJudgeResultTarget(ctx context.Context, arg LockJudgeResultTargetParams) (LockJudgeResultTargetRow, error) {
	row := q.db.QueryRowContext(ctx, lockJudgeResultTarget, arg.JobID, arg.Generation)
	var i LockJudgeResultTargetRow
	err := row.Scan(
		&i.State,
		&i.SubmissionID,
		&i.ProblemID,
		&i.UserID,
		&i.ContestID,
		&i.WorkerID,
		&i.LeaseToken,
	)
	return i, err
}

const renewJudgeLease = `-- name: RenewJudgeLease :one
WITH renewed AS (
		   UPDATE judge_jobs
		   SET lease_expires_at = now() + ($1::bigint * interval '1 millisecond')
		   WHERE judge_jobs.id = $2::uuid AND generation = $3::integer AND lease_token = $4::uuid
		     AND worker_id = $5::text AND state = 'running' AND lease_expires_at >= now()
		   RETURNING submission_id, generation
		 ), progress AS (
		   UPDATE submissions AS sub
		   SET judged_cases = GREATEST(sub.judged_cases, $6::integer)
		   FROM renewed
		   WHERE sub.id = renewed.submission_id AND sub.judge_generation = renewed.generation
		 )
		 SELECT count(*)::int FROM renewed
`

type RenewJudgeLeaseParams struct {
	LeaseMillis int64
	JobID       string
	Generation  int
	LeaseToken  string
	WorkerID    string
	JudgedCases int
}

func (q *Queries) RenewJudgeLease(ctx context.Context, arg RenewJudgeLeaseParams) (int, error) {
	row := q.db.QueryRowContext(ctx, renewJudgeLease,
		arg.LeaseMillis,
		arg.JobID,
		arg.Generation,
		arg.LeaseToken,
		arg.WorkerID,
		arg.JudgedCases,
	)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const saveSubmissionResult = `-- name: SaveSubmissionResult :execrows
UPDATE submissions SET status = $1::text, score = $2::integer, total_time_ms = $3::bigint,
		        peak_memory_kb = $4::integer, compile_result = $5::text, case_results = $6::jsonb,
		        judged_cases = $7::integer, total_cases = GREATEST(total_cases, $7::integer),
		        judged_at = now()
		 WHERE id = $8::uuid AND judge_generation = $9::integer
`

type SaveSubmissionResultParams struct {
	Status        string
	Score         int
	TotalTimeMs   int64
	PeakMemoryKb  int
	CompileResult string
	CaseResults   json.RawMessage
	JudgedCases   int
	SubmissionID  string
	Generation    int
}

func (q *Queries) SaveSubmissionResult(ctx context.Context, arg SaveSubmissionResultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveSubmissionResult,
		arg.Status,
		arg.Score,
		arg.TotalTimeMs,
		arg.PeakMemoryKb,
		arg.CompileResult,
		arg.CaseResults,
		arg.JudgedCases,
		arg.SubmissionID,
		arg.Generation,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
