// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: numbers.sql

package dbgen

import (
	"context"
)

const resolveAnnouncementNumber = `-- name: ResolveAnnouncementNumber :one
SELECT id FROM announcements WHERE domain_id=$1::uuid AND public_id=$2::bigint
`

type ResolveAnnouncementNumberParams struct {
	DomainID string
	PublicID int64
}

func (q *Queries) ResolveAnnouncementNumber(ctx context.Context, arg ResolveAnnouncementNumberParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveAnnouncementNumber, arg.DomainID, arg.PublicID)
	var id string
	err := row.Scan(&id)
	return id, err
}
