// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lists.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const countPublicProblems = `-- name: CountPublicProblems :one
SELECT count(*)
FROM problems p JOIN problem_workspaces w ON w.problem_id=p.id
LEFT JOIN LATERAL (SELECT COALESCE(max(CASE WHEN a.role='editor' THEN 2 ELSE 1 END),0)::integer AS grant_rank
 FROM problem_access a WHERE a.problem_id=p.id AND a.domain_id=p.domain_id
 AND (a.user_id=NULLIF($1::text,'')::uuid OR a.group_id IN (
 SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($1::text,'')::uuid))) grants ON true
WHERE p.domain_id=$2::uuid AND p.published_version IS NOT NULL AND (p.visibility='public' OR ($3::boolean OR ($4::boolean AND (p.owner_id=NULLIF($1::text,'')::uuid OR grants.grant_rank>0))))
AND ($5::text='' OR p.visibility=$5::text)
AND ($6::integer<=0 OR p.difficulty=$6::integer)
AND ($7::text='' OR p.title ILIKE '%'||$7::text||'%' OR p.source ILIKE '%'||$7::text||'%')
AND ($8::text='' OR EXISTS(SELECT 1 FROM problem_tags pt JOIN tags t ON t.id=pt.tag_id WHERE pt.problem_id=p.id AND t.name=$8::text))
AND ($1::text='' OR $9::text='' OR
 ($9::text='solved' AND EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL AND sub.status='Accepted')) OR
 ($9::text='attempted' AND EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL) AND NOT EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL AND sub.status='Accepted')) OR
 ($9::text='none' AND NOT EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL)))
`

type CountPublicProblemsParams struct {
	ViewerID     string
	DomainID     string
	IsManager    bool
	ActiveMember bool
	Visibility   string
	Difficulty   int
	Keyword      string
	Tag          string
	Status       string
}

func (q *Queries) CountPublicProblems(ctx context.Context, arg CountPublicProblemsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublicProblems,
		arg.ViewerID,
		arg.DomainID,
		arg.IsManager,
		arg.ActiveMember,
		arg.Visibility,
		arg.Difficulty,
		arg.Keyword,
		arg.Tag,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaceProblems = `-- name: CountWorkspaceProblems :one
SELECT count(*)
FROM problems p JOIN problem_workspaces w ON w.problem_id=p.id
LEFT JOIN LATERAL (SELECT COALESCE(max(CASE WHEN a.role='editor' THEN 2 ELSE 1 END),0)::integer AS grant_rank
 FROM problem_access a WHERE a.problem_id=p.id AND a.domain_id=p.domain_id
 AND (a.user_id=NULLIF($1::text,'')::uuid OR a.group_id IN (
 SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($1::text,'')::uuid))) grants ON true
WHERE p.domain_id=$2::uuid AND ($3::boolean OR ($4::boolean AND (p.owner_id=NULLIF($1::text,'')::uuid OR grants.grant_rank>0)))
AND ($5::text='' OR p.visibility=$5::text)
AND ($6::integer<=0 OR w.difficulty=$6::integer)
AND ($7::text='' OR w.title ILIKE '%'||$7::text||'%' OR w.source ILIKE '%'||$7::text||'%')
AND ($8::text='' OR w.tags_json @> jsonb_build_array($8::text))
AND ($1::text='' OR $9::text='' OR
 ($9::text='solved' AND EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL AND sub.status='Accepted')) OR
 ($9::text='attempted' AND EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL) AND NOT EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL AND sub.status='Accepted')) OR
 ($9::text='none' AND NOT EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL)))
`

type CountWorkspaceProblemsParams struct {
	ViewerID     string
	DomainID     string
	IsManager    bool
	ActiveMember bool
	Visibility   string
	Difficulty   int
	Keyword      string
	Tag          string
	Status       string
}

func (q *Queries) CountWorkspaceProblems(ctx context.Context, arg CountWorkspaceProblemsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspaceProblems,
		arg.ViewerID,
		arg.DomainID,
		arg.IsManager,
		arg.ActiveMember,
		arg.Visibility,
		arg.Difficulty,
		arg.Keyword,
		arg.Tag,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listPublicProblems = `-- name: ListPublicProblems :many
SELECT p.id,p.public_id,p.title,''::text AS statement_md,p.difficulty,p.source,
 p.time_limit_ms,p.memory_limit_kb,p.visibility,p.author_id,p.submission_count,p.accepted_count,p.solved_user_count,
 p.judge_type,p.created_at,p.updated_at,p.owner_id,p.domain_id,COALESCE(p.published_version,0)::integer AS published_version,
 COALESCE((SELECT jsonb_agg(t.name ORDER BY t.name) FROM problem_tags pt JOIN tags t ON t.id=pt.tag_id WHERE pt.problem_id=p.id),'[]'::jsonb)::jsonb AS tags,COALESCE((SELECT u.username FROM users u WHERE u.id=p.owner_id),'')::text AS owner_name,grants.grant_rank AS grant_rank
FROM problems p JOIN problem_workspaces w ON w.problem_id=p.id
LEFT JOIN LATERAL (SELECT COALESCE(max(CASE WHEN a.role='editor' THEN 2 ELSE 1 END),0)::integer AS grant_rank
 FROM problem_access a WHERE a.problem_id=p.id AND a.domain_id=p.domain_id
 AND (a.user_id=NULLIF($1::text,'')::uuid OR a.group_id IN (
 SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($1::text,'')::uuid))) grants ON true
WHERE p.domain_id=$2::uuid AND p.published_version IS NOT NULL AND (p.visibility='public' OR ($3::boolean OR ($4::boolean AND (p.owner_id=NULLIF($1::text,'')::uuid OR grants.grant_rank>0))))
AND ($5::text='' OR p.visibility=$5::text)
AND ($6::integer<=0 OR p.difficulty=$6::integer)
AND ($7::text='' OR p.title ILIKE '%'||$7::text||'%' OR p.source ILIKE '%'||$7::text||'%')
AND ($8::text='' OR EXISTS(SELECT 1 FROM problem_tags pt JOIN tags t ON t.id=pt.tag_id WHERE pt.problem_id=p.id AND t.name=$8::text))
AND ($1::text='' OR $9::text='' OR
 ($9::text='solved' AND EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL AND sub.status='Accepted')) OR
 ($9::text='attempted' AND EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL) AND NOT EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL AND sub.status='Accepted')) OR
 ($9::text='none' AND NOT EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL)))
ORDER BY p.created_at DESC,p.id DESC LIMIT $11::integer OFFSET $10::integer
`

type ListPublicProblemsParams struct {
	ViewerID     string
	DomainID     string
	IsManager    bool
	ActiveMember bool
	Visibility   string
	Difficulty   int
	Keyword      string
	Tag          string
	Status       string
	PageOffset   int
	PageLimit    int
}

type ListPublicProblemsRow struct {
	ID               string
	PublicID         string
	Title            string
	StatementMd      string
	Difficulty       int
	Source           string
	TimeLimitMs      int
	MemoryLimitKb    int
	Visibility       string
	AuthorID         *string
	SubmissionCount  int
	AcceptedCount    int
	SolvedUserCount  int
	JudgeType        string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	OwnerID          string
	DomainID         string
	PublishedVersion int
	Tags             json.RawMessage
	OwnerName        string
	GrantRank        int
}

func (q *Queries) ListPublicProblems(ctx context.Context, arg ListPublicProblemsParams) ([]ListPublicProblemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicProblems,
		arg.ViewerID,
		arg.DomainID,
		arg.IsManager,
		arg.ActiveMember,
		arg.Visibility,
		arg.Difficulty,
		arg.Keyword,
		arg.Tag,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicProblemsRow{}
	for rows.Next() {
		var i ListPublicProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.StatementMd,
			&i.Difficulty,
			&i.Source,
			&i.TimeLimitMs,
			&i.MemoryLimitKb,
			&i.Visibility,
			&i.AuthorID,
			&i.SubmissionCount,
			&i.AcceptedCount,
			&i.SolvedUserCount,
			&i.JudgeType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.DomainID,
			&i.PublishedVersion,
			&i.Tags,
			&i.OwnerName,
			&i.GrantRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceProblems = `-- name: ListWorkspaceProblems :many
SELECT p.id,p.public_id,w.title,''::text AS statement_md,w.difficulty,w.source,
 w.time_limit_ms,w.memory_limit_kb,p.visibility,p.author_id,p.submission_count,p.accepted_count,p.solved_user_count,
 w.judge_type,p.created_at,w.updated_at,p.owner_id,p.domain_id,COALESCE(p.published_version,0)::integer AS published_version,
 w.tags_json AS tags,COALESCE((SELECT u.username FROM users u WHERE u.id=p.owner_id),'')::text AS owner_name,grants.grant_rank AS grant_rank
FROM problems p JOIN problem_workspaces w ON w.problem_id=p.id
LEFT JOIN LATERAL (SELECT COALESCE(max(CASE WHEN a.role='editor' THEN 2 ELSE 1 END),0)::integer AS grant_rank
 FROM problem_access a WHERE a.problem_id=p.id AND a.domain_id=p.domain_id
 AND (a.user_id=NULLIF($1::text,'')::uuid OR a.group_id IN (
 SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($1::text,'')::uuid))) grants ON true
WHERE p.domain_id=$2::uuid AND ($3::boolean OR ($4::boolean AND (p.owner_id=NULLIF($1::text,'')::uuid OR grants.grant_rank>0)))
AND ($5::text='' OR p.visibility=$5::text)
AND ($6::integer<=0 OR w.difficulty=$6::integer)
AND ($7::text='' OR w.title ILIKE '%'||$7::text||'%' OR w.source ILIKE '%'||$7::text||'%')
AND ($8::text='' OR w.tags_json @> jsonb_build_array($8::text))
AND ($1::text='' OR $9::text='' OR
 ($9::text='solved' AND EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL AND sub.status='Accepted')) OR
 ($9::text='attempted' AND EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL) AND NOT EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL AND sub.status='Accepted')) OR
 ($9::text='none' AND NOT EXISTS(SELECT 1 FROM submissions sub WHERE sub.user_id=NULLIF($1::text,'')::uuid AND sub.problem_id=p.id AND sub.contest_id IS NULL)))
ORDER BY p.created_at DESC,p.id DESC LIMIT $11::integer OFFSET $10::integer
`

type ListWorkspaceProblemsParams struct {
	ViewerID     string
	DomainID     string
	IsManager    bool
	ActiveMember bool
	Visibility   string
	Difficulty   int
	Keyword      string
	Tag          string
	Status       string
	PageOffset   int
	PageLimit    int
}

type ListWorkspaceProblemsRow struct {
	ID               string
	PublicID         string
	Title            string
	StatementMd      string
	Difficulty       int
	Source           string
	TimeLimitMs      int
	MemoryLimitKb    int
	Visibility       string
	AuthorID         *string
	SubmissionCount  int
	AcceptedCount    int
	SolvedUserCount  int
	JudgeType        string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	OwnerID          string
	DomainID         string
	PublishedVersion int
	Tags             json.RawMessage
	OwnerName        string
	GrantRank        int
}

func (q *Queries) ListWorkspaceProblems(ctx context.Context, arg ListWorkspaceProblemsParams) ([]ListWorkspaceProblemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceProblems,
		arg.ViewerID,
		arg.DomainID,
		arg.IsManager,
		arg.ActiveMember,
		arg.Visibility,
		arg.Difficulty,
		arg.Keyword,
		arg.Tag,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceProblemsRow{}
	for rows.Next() {
		var i ListWorkspaceProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.StatementMd,
			&i.Difficulty,
			&i.Source,
			&i.TimeLimitMs,
			&i.MemoryLimitKb,
			&i.Visibility,
			&i.AuthorID,
			&i.SubmissionCount,
			&i.AcceptedCount,
			&i.SolvedUserCount,
			&i.JudgeType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.DomainID,
			&i.PublishedVersion,
			&i.Tags,
			&i.OwnerName,
			&i.GrantRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
