// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const countAccounts = `-- name: CountAccounts :one
SELECT count(*)::integer FROM users u WHERE ($1::text='' OR u.username ILIKE '%'||$1::text||'%' OR u.email ILIKE '%'||$1::text||'%') AND ($2::text='' OR u.role=$2::text) AND (NOT $3::boolean OR u.disabled_at IS NOT NULL)
`

type CountAccountsParams struct {
	Keyword      string
	Role         string
	OnlyDisabled bool
}

func (q *Queries) CountAccounts(ctx context.Context, arg CountAccountsParams) (int, error) {
	row := q.db.QueryRowContext(ctx, countAccounts, arg.Keyword, arg.Role, arg.OnlyDisabled)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const countAnnouncements = `-- name: CountAnnouncements :one
SELECT count(*) FROM announcements a WHERE a.domain_id=$1::uuid AND (NOT $2::boolean OR a.published) AND ($3::text='' OR strpos(lower(a.title),lower($3::text))>0 OR a.public_id::text=$3::text)
`

type CountAnnouncementsParams struct {
	DomainID      string
	PublishedOnly bool
	Keyword       string
}

func (q *Queries) CountAnnouncements(ctx context.Context, arg CountAnnouncementsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAnnouncements, arg.DomainID, arg.PublishedOnly, arg.Keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements(domain_id,created_by,title,content_md,pinned,published) VALUES($1::uuid,$2::uuid,$3::text,$4::text,$5::boolean,$6::boolean) RETURNING id
`

type CreateAnnouncementParams struct {
	DomainID  string
	UserID    string
	Title     string
	Body      string
	Pinned    bool
	Published bool
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createAnnouncement,
		arg.DomainID,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.Pinned,
		arg.Published,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :execrows
DELETE FROM announcements WHERE id=$1::uuid AND domain_id=$2::uuid
`

type DeleteAnnouncementParams struct {
	AnnouncementID string
	DomainID       string
}

func (q *Queries) DeleteAnnouncement(ctx context.Context, arg DeleteAnnouncementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAnnouncement, arg.AnnouncementID, arg.DomainID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id=$1::bigint AND domain_id=$2::uuid
`

type DeleteTagParams struct {
	TagID    int64
	DomainID string
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteTag, arg.TagID, arg.DomainID)
	return err
}

const findTagByName = `-- name: FindTagByName :one
SELECT id FROM tags WHERE domain_id=$1::uuid AND name=$2::text
`

type FindTagByNameParams struct {
	DomainID string
	Name     string
}

func (q *Queries) FindTagByName(ctx context.Context, arg FindTagByNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, findTagByName, arg.DomainID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAccountSummary = `-- name: GetAccountSummary :one
SELECT u.id, u.username, u.email, u.role, u.rating, u.created_at,
	u.disabled_at, u.disabled_reason,
	(SELECT count(*) FROM submissions AS s WHERE s.user_id = u.id)::int AS submission_count,
	(SELECT count(DISTINCT s.problem_id) FROM submissions AS s
	   WHERE s.user_id = u.id AND s.status = 'Accepted')::int AS solved_count FROM users AS u WHERE u.id = $1::uuid
`

type GetAccountSummaryRow struct {
	ID              string
	Username        string
	Email           string
	Role            string
	Rating          int
	CreatedAt       time.Time
	DisabledAt      *time.Time
	DisabledReason  string
	SubmissionCount int
	SolvedCount     int
}

func (q *Queries) GetAccountSummary(ctx context.Context, userID string) (GetAccountSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountSummary, userID)
	var i GetAccountSummaryRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Rating,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.SubmissionCount,
		&i.SolvedCount,
	)
	return i, err
}

const getAnnouncement = `-- name: GetAnnouncement :one
SELECT a.id,a.public_id::text AS public_id,a.title,a.content_md,a.pinned,a.published,COALESCE(u.username,'') AS author_name,a.created_at,a.updated_at FROM announcements a LEFT JOIN users u ON u.id=a.created_by WHERE a.id=$1::uuid AND a.domain_id=$2::uuid AND (NOT $3::boolean OR a.published)
`

type GetAnnouncementParams struct {
	AnnouncementID string
	DomainID       string
	PublishedOnly  bool
}

type GetAnnouncementRow struct {
	ID         string
	PublicID   string
	Title      string
	ContentMd  string
	Pinned     bool
	Published  bool
	AuthorName string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) GetAnnouncement(ctx context.Context, arg GetAnnouncementParams) (GetAnnouncementRow, error) {
	row := q.db.QueryRowContext(ctx, getAnnouncement, arg.AnnouncementID, arg.DomainID, arg.PublishedOnly)
	var i GetAnnouncementRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.ContentMd,
		&i.Pinned,
		&i.Published,
		&i.AuthorName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagCatalogEntry = `-- name: GetTagCatalogEntry :one
SELECT t.id,t.name,(SELECT count(*) FROM problem_tags pt WHERE pt.tag_id=t.id AND pt.domain_id=t.domain_id)::int AS problem_count FROM tags t WHERE t.id=$1::bigint AND t.domain_id=$2::uuid
`

type GetTagCatalogEntryParams struct {
	TagID    int64
	DomainID string
}

type GetTagCatalogEntryRow struct {
	ID           int64
	Name         string
	ProblemCount int
}

func (q *Queries) GetTagCatalogEntry(ctx context.Context, arg GetTagCatalogEntryParams) (GetTagCatalogEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getTagCatalogEntry, arg.TagID, arg.DomainID)
	var i GetTagCatalogEntryRow
	err := row.Scan(&i.ID, &i.Name, &i.ProblemCount)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT u.id, u.username, u.email, u.role, u.rating, u.created_at,
	u.disabled_at, u.disabled_reason,
	(SELECT count(*) FROM submissions AS s WHERE s.user_id = u.id)::int AS submission_count,
	(SELECT count(DISTINCT s.problem_id) FROM submissions AS s
	   WHERE s.user_id = u.id AND s.status = 'Accepted')::int AS solved_count FROM users u WHERE ($1::text='' OR u.username ILIKE '%'||$1::text||'%' OR u.email ILIKE '%'||$1::text||'%') AND ($2::text='' OR u.role=$2::text) AND (NOT $3::boolean OR u.disabled_at IS NOT NULL) ORDER BY u.created_at DESC LIMIT $5::integer OFFSET $4::integer
`

type ListAccountsParams struct {
	Keyword      string
	Role         string
	OnlyDisabled bool
	PageOffset   int
	PageLimit    int
}

type ListAccountsRow struct {
	ID              string
	Username        string
	Email           string
	Role            string
	Rating          int
	CreatedAt       time.Time
	DisabledAt      *time.Time
	DisabledReason  string
	SubmissionCount int
	SolvedCount     int
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts,
		arg.Keyword,
		arg.Role,
		arg.OnlyDisabled,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.Rating,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.DisabledReason,
			&i.SubmissionCount,
			&i.SolvedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT a.id,a.public_id::text AS public_id,a.title,a.content_md,a.pinned,a.published,COALESCE(u.username,'') AS author_name,a.created_at,a.updated_at FROM announcements a LEFT JOIN users u ON u.id=a.created_by WHERE a.domain_id=$1::uuid AND (NOT $2::boolean OR a.published) AND ($3::text='' OR strpos(lower(a.title),lower($3::text))>0 OR a.public_id::text=$3::text) ORDER BY a.pinned DESC,a.created_at DESC,a.id DESC LIMIT $5::integer OFFSET $4::integer
`

type ListAnnouncementsParams struct {
	DomainID      string
	PublishedOnly bool
	Keyword       string
	PageOffset    int
	PageLimit     int
}

type ListAnnouncementsRow struct {
	ID         string
	PublicID   string
	Title      string
	ContentMd  string
	Pinned     bool
	Published  bool
	AuthorName string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) ListAnnouncements(ctx context.Context, arg ListAnnouncementsParams) ([]ListAnnouncementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAnnouncements,
		arg.DomainID,
		arg.PublishedOnly,
		arg.Keyword,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnouncementsRow{}
	for rows.Next() {
		var i ListAnnouncementsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.ContentMd,
			&i.Pinned,
			&i.Published,
			&i.AuthorName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagCatalog = `-- name: ListTagCatalog :many
SELECT t.id,t.name,(SELECT count(*) FROM problem_tags pt WHERE pt.tag_id=t.id AND pt.domain_id=t.domain_id)::int AS problem_count FROM tags t WHERE t.domain_id=$1::uuid ORDER BY t.name
`

type ListTagCatalogRow struct {
	ID           int64
	Name         string
	ProblemCount int
}

func (q *Queries) ListTagCatalog(ctx context.Context, domainID string) ([]ListTagCatalogRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagCatalog, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagCatalogRow{}
	for rows.Next() {
		var i ListTagCatalogRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ProblemCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTaggedWorkspaces = `-- name: LockTaggedWorkspaces :many
SELECT w.problem_id,w.tags_json FROM problem_workspaces w JOIN problems p ON p.id=w.problem_id
WHERE p.domain_id=$1::uuid AND w.tags_json ? $2::text ORDER BY w.problem_id FOR UPDATE OF w
`

type LockTaggedWorkspacesParams struct {
	DomainID string
	OldName  string
}

type LockTaggedWorkspacesRow struct {
	ProblemID string
	TagsJson  json.RawMessage
}

func (q *Queries) LockTaggedWorkspaces(ctx context.Context, arg LockTaggedWorkspacesParams) ([]LockTaggedWorkspacesRow, error) {
	rows, err := q.db.QueryContext(ctx, lockTaggedWorkspaces, arg.DomainID, arg.OldName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockTaggedWorkspacesRow{}
	for rows.Next() {
		var i LockTaggedWorkspacesRow
		if err := rows.Scan(&i.ProblemID, &i.TagsJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeProblemTags = `-- name: MergeProblemTags :exec
INSERT INTO problem_tags(domain_id,problem_id,tag_id) SELECT domain_id,problem_id,$1::bigint FROM problem_tags WHERE problem_tags.tag_id=$2::bigint AND problem_tags.domain_id=$3::uuid ON CONFLICT(problem_id,tag_id) DO NOTHING
`

type MergeProblemTagsParams struct {
	TargetID int64
	SourceID int64
	DomainID string
}

func (q *Queries) MergeProblemTags(ctx context.Context, arg MergeProblemTagsParams) error {
	_, err := q.db.ExecContext(ctx, mergeProblemTags, arg.TargetID, arg.SourceID, arg.DomainID)
	return err
}

const recordResourceAudit = `-- name: RecordResourceAudit :exec
INSERT INTO domain_audit_events(domain_id,actor_id,action,target) VALUES($1::uuid,$2::uuid,$3::text,$4::text)
`

type RecordResourceAuditParams struct {
	DomainID string
	UserID   string
	Action   string
	Target   string
}

func (q *Queries) RecordResourceAudit(ctx context.Context, arg RecordResourceAuditParams) error {
	_, err := q.db.ExecContext(ctx, recordResourceAudit,
		arg.DomainID,
		arg.UserID,
		arg.Action,
		arg.Target,
	)
	return err
}

const renameTag = `-- name: RenameTag :exec
UPDATE tags SET name=$1::text WHERE id=$2::bigint AND domain_id=$3::uuid
`

type RenameTagParams struct {
	Name     string
	TagID    int64
	DomainID string
}

func (q *Queries) RenameTag(ctx context.Context, arg RenameTagParams) error {
	_, err := q.db.ExecContext(ctx, renameTag, arg.Name, arg.TagID, arg.DomainID)
	return err
}

const revokeAccountSessions = `-- name: RevokeAccountSessions :exec
UPDATE auth_sessions SET revoked_at = now()
			 WHERE user_id = $1::uuid AND revoked_at IS NULL
`

func (q *Queries) RevokeAccountSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, revokeAccountSessions, userID)
	return err
}

const updateAccount = `-- name: UpdateAccount :execrows
UPDATE users SET role=CASE WHEN $1::boolean THEN $2::text ELSE role END,
 rating=CASE WHEN $3::boolean THEN $4::integer ELSE rating END,
 disabled_at=CASE WHEN NOT $5::boolean THEN disabled_at WHEN $6::boolean THEN now() ELSE NULL END,
 disabled_reason=CASE WHEN NOT $5::boolean THEN disabled_reason WHEN $6::boolean THEN $7::text ELSE '' END
WHERE id=$8::uuid
`

type UpdateAccountParams struct {
	SetRole     bool
	Role        string
	SetRating   bool
	Rating      int
	SetDisabled bool
	Disabled    bool
	Reason      string
	UserID      string
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAccount,
		arg.SetRole,
		arg.Role,
		arg.SetRating,
		arg.Rating,
		arg.SetDisabled,
		arg.Disabled,
		arg.Reason,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAnnouncement = `-- name: UpdateAnnouncement :execrows
UPDATE announcements SET title=$1::text,content_md=$2::text,pinned=$3::boolean,published=$4::boolean,updated_at=now() WHERE id=$5::uuid AND domain_id=$6::uuid
`

type UpdateAnnouncementParams struct {
	Title          string
	Body           string
	Pinned         bool
	Published      bool
	AnnouncementID string
	DomainID       string
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAnnouncement,
		arg.Title,
		arg.Body,
		arg.Pinned,
		arg.Published,
		arg.AnnouncementID,
		arg.DomainID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkspaceTags = `-- name: UpdateWorkspaceTags :exec
WITH changed AS (UPDATE problem_workspaces SET tags_json=$1::jsonb,updated_at=now()
 WHERE problem_id=$2::uuid RETURNING problem_id)
UPDATE problems SET package_revision=package_revision+1,updated_at=now() WHERE id IN(SELECT problem_id FROM changed)
`

type UpdateWorkspaceTagsParams struct {
	Tags      json.RawMessage
	ProblemID string
}

func (q *Queries) UpdateWorkspaceTags(ctx context.Context, arg UpdateWorkspaceTagsParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceTags, arg.Tags, arg.ProblemID)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags(domain_id,name) VALUES($1::uuid,$2::text) ON CONFLICT(domain_id,name) DO UPDATE SET name=excluded.name RETURNING id
`

type UpsertTagParams struct {
	DomainID string
	Name     string
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertTag, arg.DomainID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
