// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package dbgen

import (
	"context"
	"time"
)

const getJudgeQueueStats = `-- name: GetJudgeQueueStats :one
SELECT count(*) FILTER(WHERE state='queued')::integer AS queued_jobs,
 count(*) FILTER(WHERE state='running')::integer AS running_jobs,
 count(*) FILTER(WHERE state='dead')::integer AS dead_jobs,
 COALESCE(min(created_at) FILTER(WHERE state='queued'),TIMESTAMPTZ 'epoch')::timestamptz AS oldest_queued,
 count(DISTINCT worker_id) FILTER(WHERE state='running' AND lease_expires_at>=now())::integer AS active_workers
FROM judge_jobs
`

type GetJudgeQueueStatsRow struct {
	QueuedJobs    int
	RunningJobs   int
	DeadJobs      int
	OldestQueued  time.Time
	ActiveWorkers int
}

func (q *Queries) GetJudgeQueueStats(ctx context.Context) (GetJudgeQueueStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getJudgeQueueStats)
	var i GetJudgeQueueStatsRow
	err := row.Scan(
		&i.QueuedJobs,
		&i.RunningJobs,
		&i.DeadJobs,
		&i.OldestQueued,
		&i.ActiveWorkers,
	)
	return i, err
}

const getSiteStats = `-- name: GetSiteStats :one
SELECT (SELECT count(*) FROM users)::integer AS users,
 (SELECT count(*) FROM users WHERE created_at>=now()-interval '1 day')::integer AS users_today,
 (SELECT count(*) FROM problems)::integer AS problems,
 (SELECT count(*) FROM problems WHERE visibility='public' AND published_version IS NOT NULL)::integer AS public_problems,
 (SELECT count(*) FROM submissions)::integer AS submissions,
 (SELECT count(*) FROM submissions WHERE submitted_at>=now()-interval '1 day')::integer AS submissions_today,
 (SELECT count(*) FROM contests)::integer AS contests,
 (SELECT count(*) FROM contests WHERE now() BETWEEN begin_at AND end_at)::integer AS running_contests,
 (SELECT count(*) FROM editorials WHERE status='published')::integer AS editorials,
 (SELECT count(*) FROM problem_sets)::integer AS problem_sets
`

type GetSiteStatsRow struct {
	Users            int
	UsersToday       int
	Problems         int
	PublicProblems   int
	Submissions      int
	SubmissionsToday int
	Contests         int
	RunningContests  int
	Editorials       int
	ProblemSets      int
}

func (q *Queries) GetSiteStats(ctx context.Context) (GetSiteStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getSiteStats)
	var i GetSiteStatsRow
	err := row.Scan(
		&i.Users,
		&i.UsersToday,
		&i.Problems,
		&i.PublicProblems,
		&i.Submissions,
		&i.SubmissionsToday,
		&i.Contests,
		&i.RunningContests,
		&i.Editorials,
		&i.ProblemSets,
	)
	return i, err
}

const listRecentVerdictCounts = `-- name: ListRecentVerdictCounts :many
SELECT status,count(*)::integer AS count FROM submissions WHERE submitted_at>=now()-interval '1 day' GROUP BY status ORDER BY count(*) DESC
`

type ListRecentVerdictCountsRow struct {
	Status string
	Count  int
}

func (q *Queries) ListRecentVerdictCounts(ctx context.Context) ([]ListRecentVerdictCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentVerdictCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentVerdictCountsRow{}
	for rows.Next() {
		var i ListRecentVerdictCountsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
