// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"
)

type User struct {
	ID             string
	Username       string
	Email          string
	PasswordHash   string
	Role           string
	Rating         int
	DisabledAt     *time.Time
	DisabledReason string
	CreatedAt      time.Time
}
