// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"
	"time"
)

const activeSessionUser = `-- name: ActiveSessionUser :one
SELECT usr.id, usr.username, usr.email, usr.password_hash, usr.role, usr.rating, usr.disabled_at, usr.disabled_reason, usr.created_at
FROM auth_sessions AS session JOIN users AS usr ON usr.id = session.user_id
WHERE session.id = $1 AND session.user_id = $2
  AND session.revoked_at IS NULL AND session.expires_at > now()
`

type ActiveSessionUserParams struct {
	ID     string
	UserID string
}

func (q *Queries) ActiveSessionUser(ctx context.Context, arg ActiveSessionUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, activeSessionUser, arg.ID, arg.UserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Rating,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO auth_sessions(user_id, refresh_token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, expires_at
`

type CreateSessionParams struct {
	UserID           string
	RefreshTokenHash []byte
	ExpiresAt        time.Time
}

type CreateSessionRow struct {
	ID        string
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserID, arg.RefreshTokenHash, arg.ExpiresAt)
	var i CreateSessionRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE auth_sessions SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1 AND user_id = $2
`

type RevokeSessionParams struct {
	ID     string
	UserID string
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE auth_sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, revokeUserSessions, userID)
	return err
}

const rotateSession = `-- name: RotateSession :one
UPDATE auth_sessions AS session
SET refresh_token_hash = $1, expires_at = $2, last_used_at = now()
FROM users AS usr
WHERE session.refresh_token_hash = $3
  AND session.user_id = usr.id
  AND session.revoked_at IS NULL
  AND session.expires_at > now()
RETURNING session.id AS session_id, session.user_id, session.expires_at,
          usr.id, usr.username, usr.email, usr.password_hash, usr.role, usr.rating,
          usr.created_at, usr.disabled_at, usr.disabled_reason
`

type RotateSessionParams struct {
	NewHash   []byte
	ExpiresAt time.Time
	OldHash   []byte
}

type RotateSessionRow struct {
	SessionID      string
	UserID         string
	ExpiresAt      time.Time
	ID             string
	Username       string
	Email          string
	PasswordHash   string
	Role           string
	Rating         int
	CreatedAt      time.Time
	DisabledAt     *time.Time
	DisabledReason string
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (RotateSessionRow, error) {
	row := q.db.QueryRowContext(ctx, rotateSession, arg.NewHash, arg.ExpiresAt, arg.OldHash)
	var i RotateSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Rating,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.DisabledReason,
	)
	return i, err
}
