// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
)

const bootstrapAdmin = `-- name: BootstrapAdmin :exec
INSERT INTO users(username, email, password_hash, role)
VALUES ($1, $2, $3, 'admin')
ON CONFLICT(username) DO NOTHING
`

type BootstrapAdminParams struct {
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) BootstrapAdmin(ctx context.Context, arg BootstrapAdminParams) error {
	_, err := q.db.ExecContext(ctx, bootstrapAdmin, arg.Username, arg.Email, arg.PasswordHash)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, role)
VALUES ($1, $2, $3, 'user')
RETURNING id, username, email, password_hash, role, rating, disabled_at, disabled_reason, created_at
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Rating,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.CreatedAt,
	)
	return i, err
}

const joinOfficialDomain = `-- name: JoinOfficialDomain :execrows
INSERT INTO domain_members(domain_id, user_id, role_key, status)
SELECT id, $1, 'member', 'active' FROM domains WHERE is_official
`

func (q *Queries) JoinOfficialDomain(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, joinOfficialDomain, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const userByID = `-- name: UserByID :one
SELECT id, username, email, password_hash, role, rating, disabled_at, disabled_reason, created_at FROM users WHERE id = $1
`

func (q *Queries) UserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Rating,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.CreatedAt,
	)
	return i, err
}

const userByUsername = `-- name: UserByUsername :one
SELECT id, username, email, password_hash, role, rating, disabled_at, disabled_reason, created_at FROM users WHERE username = $1
`

func (q *Queries) UserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Rating,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.CreatedAt,
	)
	return i, err
}
