// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create.sql

package dbgen

import (
	"context"
	"time"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (user_id, problem_id, language, source_code, status, contest_id, domain_id)
		 VALUES ($1::uuid, $2::uuid, $3::text, $4::text, 'Pending', $5::uuid, $6::uuid)
		 RETURNING id, public_id, user_id, problem_id, language, source_code, status, score,
		           total_time_ms, peak_memory_kb, compile_result, contest_id, submitted_at, judged_at,problem_version
`

type CreateSubmissionParams struct {
	UserID     string
	ProblemID  string
	Language   string
	SourceCode string
	ContestID  *string
	DomainID   string
}

type CreateSubmissionRow struct {
	ID             string
	PublicID       string
	UserID         string
	ProblemID      string
	Language       string
	SourceCode     string
	Status         string
	Score          int
	TotalTimeMs    int
	PeakMemoryKb   int
	CompileResult  string
	ContestID      *string
	SubmittedAt    time.Time
	JudgedAt       *time.Time
	ProblemVersion int
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (CreateSubmissionRow, error) {
	row := q.db.QueryRowContext(ctx, createSubmission,
		arg.UserID,
		arg.ProblemID,
		arg.Language,
		arg.SourceCode,
		arg.ContestID,
		arg.DomainID,
	)
	var i CreateSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ProblemID,
		&i.Language,
		&i.SourceCode,
		&i.Status,
		&i.Score,
		&i.TotalTimeMs,
		&i.PeakMemoryKb,
		&i.CompileResult,
		&i.ContestID,
		&i.SubmittedAt,
		&i.JudgedAt,
		&i.ProblemVersion,
	)
	return i, err
}

const enqueueInitialJudgeJob = `-- name: EnqueueInitialJudgeJob :exec
INSERT INTO judge_jobs (submission_id, generation) VALUES ($1::uuid, 1)
`

func (q *Queries) EnqueueInitialJudgeJob(ctx context.Context, submissionID string) error {
	_, err := q.db.ExecContext(ctx, enqueueInitialJudgeJob, submissionID)
	return err
}

const lockSubmissionContestProblem = `-- name: LockSubmissionContestProblem :one
SELECT 1 FROM contest_problems
		 WHERE contest_id = $1::uuid AND problem_id = $2::uuid
		 FOR SHARE
`

type LockSubmissionContestProblemParams struct {
	ContestID string
	ProblemID string
}

func (q *Queries) LockSubmissionContestProblem(ctx context.Context, arg LockSubmissionContestProblemParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, lockSubmissionContestProblem, arg.ContestID, arg.ProblemID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const lockSubmissionProblem = `-- name: LockSubmissionProblem :one
SELECT 1 FROM problems WHERE id = $1::uuid AND domain_id = $2::uuid FOR SHARE
`

type LockSubmissionProblemParams struct {
	ProblemID string
	DomainID  string
}

func (q *Queries) LockSubmissionProblem(ctx context.Context, arg LockSubmissionProblemParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, lockSubmissionProblem, arg.ProblemID, arg.DomainID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const notifyJudgeJob = `-- name: NotifyJudgeJob :exec
SELECT pg_notify('vertex_judge_jobs', $1::text)
`

func (q *Queries) NotifyJudgeJob(ctx context.Context, submissionID string) error {
	_, err := q.db.ExecContext(ctx, notifyJudgeJob, submissionID)
	return err
}
