// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: governance.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const addDomainOwner = `-- name: AddDomainOwner :exec
INSERT INTO domain_members(domain_id,user_id,role_key,status) VALUES($1::uuid,$2::uuid,'admin','active')
`

type AddDomainOwnerParams struct {
	DomainID string
	UserID   string
}

func (q *Queries) AddDomainOwner(ctx context.Context, arg AddDomainOwnerParams) error {
	_, err := q.db.ExecContext(ctx, addDomainOwner, arg.DomainID, arg.UserID)
	return err
}

const archiveDomain = `-- name: ArchiveDomain :exec
UPDATE domains SET archived=$1::boolean,updated_at=now() WHERE id=$2::uuid
`

type ArchiveDomainParams struct {
	Archived bool
	DomainID string
}

func (q *Queries) ArchiveDomain(ctx context.Context, arg ArchiveDomainParams) error {
	_, err := q.db.ExecContext(ctx, archiveDomain, arg.Archived, arg.DomainID)
	return err
}

const countAccessibleDomains = `-- name: CountAccessibleDomains :one
SELECT count(*) FROM domains d LEFT JOIN users owner ON owner.id=d.owner_id
    LEFT JOIN domain_members m ON m.domain_id=d.id AND m.user_id=NULLIF($1::text,'')::uuid
    LEFT JOIN domain_roles r ON r.domain_id=m.domain_id AND r.key=m.role_key WHERE ($2::boolean OR d.visibility='public' OR m.status IN ('active','invited','pending'))
        AND (NOT d.archived OR $2::boolean OR m.status='active') AND (d.name ILIKE $3::text OR d.slug ILIKE $3::text)
`

type CountAccessibleDomainsParams struct {
	ViewerID string
	IsAdmin  bool
	Keyword  string
}

func (q *Queries) CountAccessibleDomains(ctx context.Context, arg CountAccessibleDomainsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccessibleDomains, arg.ViewerID, arg.IsAdmin, arg.Keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDomainGroups = `-- name: CountDomainGroups :one
SELECT count(*) FROM domain_groups WHERE domain_id=$1::uuid AND name ILIKE $2::text
`

type CountDomainGroupsParams struct {
	DomainID string
	Keyword  string
}

func (q *Queries) CountDomainGroups(ctx context.Context, arg CountDomainGroupsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDomainGroups, arg.DomainID, arg.Keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDomainMembers = `-- name: CountDomainMembers :one
SELECT count(*) FROM domain_members m JOIN users u ON u.id=m.user_id WHERE m.domain_id=$1::uuid AND u.username ILIKE $2::text
`

type CountDomainMembersParams struct {
	DomainID string
	Keyword  string
}

func (q *Queries) CountDomainMembers(ctx context.Context, arg CountDomainMembersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDomainMembers, arg.DomainID, arg.Keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT count(*) FROM domain_group_members gm JOIN domain_members dm ON dm.domain_id=gm.domain_id AND dm.user_id=gm.user_id
        JOIN users u ON u.id=gm.user_id WHERE gm.domain_id=$1::uuid AND gm.group_id=$2::uuid AND dm.status='active' AND u.username ILIKE $3::text
`

type CountGroupMembersParams struct {
	DomainID string
	GroupID  string
	Keyword  string
}

func (q *Queries) CountGroupMembers(ctx context.Context, arg CountGroupMembersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroupMembers, arg.DomainID, arg.GroupID, arg.Keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains(slug,name,description,owner_id,visibility,join_policy)
        VALUES($1::text,$2::text,$3::text,$4::uuid,$5::text,$6::text) RETURNING id
`

type CreateDomainParams struct {
	Slug        string
	Name        string
	Description string
	OwnerID     string
	Visibility  string
	JoinPolicy  string
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createDomain,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.Visibility,
		arg.JoinPolicy,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createDomainGroup = `-- name: CreateDomainGroup :one
INSERT INTO domain_groups(domain_id,name,description,owner_id) VALUES($1::uuid,$2::text,$3::text,$4::uuid) RETURNING id
`

type CreateDomainGroupParams struct {
	DomainID    string
	Name        string
	Description string
	OwnerID     string
}

func (q *Queries) CreateDomainGroup(ctx context.Context, arg CreateDomainGroupParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createDomainGroup,
		arg.DomainID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteDomainGroup = `-- name: DeleteDomainGroup :exec
DELETE FROM domain_groups WHERE domain_id=$1::uuid AND id=$2::uuid
`

type DeleteDomainGroupParams struct {
	DomainID string
	GroupID  string
}

func (q *Queries) DeleteDomainGroup(ctx context.Context, arg DeleteDomainGroupParams) error {
	_, err := q.db.ExecContext(ctx, deleteDomainGroup, arg.DomainID, arg.GroupID)
	return err
}

const deleteDomainRole = `-- name: DeleteDomainRole :exec
DELETE FROM domain_roles WHERE domain_id=$1::uuid AND key=$2::text AND NOT builtin
`

type DeleteDomainRoleParams struct {
	DomainID string
	Key      string
}

func (q *Queries) DeleteDomainRole(ctx context.Context, arg DeleteDomainRoleParams) error {
	_, err := q.db.ExecContext(ctx, deleteDomainRole, arg.DomainID, arg.Key)
	return err
}

const deleteGroupMember = `-- name: DeleteGroupMember :exec
DELETE FROM domain_group_members WHERE domain_id=$1::uuid AND group_id=$2::uuid AND user_id=$3::uuid
`

type DeleteGroupMemberParams struct {
	DomainID string
	GroupID  string
	UserID   string
}

func (q *Queries) DeleteGroupMember(ctx context.Context, arg DeleteGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteGroupMember, arg.DomainID, arg.GroupID, arg.UserID)
	return err
}

const ensureOfficialDomain = `-- name: EnsureOfficialDomain :exec
INSERT INTO domains(id,slug,name,is_official,visibility,join_policy) VALUES($1::uuid,'official','官方',TRUE,'public','open') ON CONFLICT(id) DO NOTHING
`

func (q *Queries) EnsureOfficialDomain(ctx context.Context, domainID string) error {
	_, err := q.db.ExecContext(ctx, ensureOfficialDomain, domainID)
	return err
}

const getDomainGroupByID = `-- name: GetDomainGroupByID :one
SELECT g.id,g.public_id,g.domain_id,g.name,g.description,g.owner_id,u.username AS owner_name,g.created_at,
    (SELECT count(*) FROM domain_group_members allgm JOIN domain_members dm ON dm.domain_id=allgm.domain_id AND dm.user_id=allgm.user_id WHERE allgm.group_id=g.id AND dm.status='active')::integer AS member_count,COALESCE(gm.role,'') AS viewer_role FROM domain_groups g JOIN users u ON u.id=g.owner_id
    LEFT JOIN domain_group_members gm ON gm.group_id=g.id AND gm.user_id=NULLIF($1::text,'')::uuid WHERE g.domain_id=$2::uuid AND g.id=$3::uuid
`

type GetDomainGroupByIDParams struct {
	ViewerID string
	DomainID string
	GroupID  string
}

type GetDomainGroupByIDRow struct {
	ID          string
	PublicID    string
	DomainID    string
	Name        string
	Description string
	OwnerID     string
	OwnerName   string
	CreatedAt   time.Time
	MemberCount int
	ViewerRole  string
}

func (q *Queries) GetDomainGroupByID(ctx context.Context, arg GetDomainGroupByIDParams) (GetDomainGroupByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainGroupByID, arg.ViewerID, arg.DomainID, arg.GroupID)
	var i GetDomainGroupByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.DomainID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerName,
		&i.CreatedAt,
		&i.MemberCount,
		&i.ViewerRole,
	)
	return i, err
}

const getDomainGroupByNumber = `-- name: GetDomainGroupByNumber :one
SELECT g.id,g.public_id,g.domain_id,g.name,g.description,g.owner_id,u.username AS owner_name,g.created_at,
    (SELECT count(*) FROM domain_group_members allgm JOIN domain_members dm ON dm.domain_id=allgm.domain_id AND dm.user_id=allgm.user_id WHERE allgm.group_id=g.id AND dm.status='active')::integer AS member_count,COALESCE(gm.role,'') AS viewer_role FROM domain_groups g JOIN users u ON u.id=g.owner_id
    LEFT JOIN domain_group_members gm ON gm.group_id=g.id AND gm.user_id=NULLIF($1::text,'')::uuid WHERE g.domain_id=$2::uuid AND g.public_id=$3::bigint
`

type GetDomainGroupByNumberParams struct {
	ViewerID string
	DomainID string
	PublicID int64
}

type GetDomainGroupByNumberRow struct {
	ID          string
	PublicID    string
	DomainID    string
	Name        string
	Description string
	OwnerID     string
	OwnerName   string
	CreatedAt   time.Time
	MemberCount int
	ViewerRole  string
}

func (q *Queries) GetDomainGroupByNumber(ctx context.Context, arg GetDomainGroupByNumberParams) (GetDomainGroupByNumberRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainGroupByNumber, arg.ViewerID, arg.DomainID, arg.PublicID)
	var i GetDomainGroupByNumberRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.DomainID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerName,
		&i.CreatedAt,
		&i.MemberCount,
		&i.ViewerRole,
	)
	return i, err
}

const getDomainRole = `-- name: GetDomainRole :one
SELECT key,name,permissions,builtin FROM domain_roles WHERE domain_id=$1::uuid AND key=$2::text
`

type GetDomainRoleParams struct {
	DomainID string
	Key      string
}

type GetDomainRoleRow struct {
	Key         string
	Name        string
	Permissions json.RawMessage
	Builtin     bool
}

func (q *Queries) GetDomainRole(ctx context.Context, arg GetDomainRoleParams) (GetDomainRoleRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainRole, arg.DomainID, arg.Key)
	var i GetDomainRoleRow
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Permissions,
		&i.Builtin,
	)
	return i, err
}

const getDomainScopeByID = `-- name: GetDomainScopeByID :one
SELECT d.id,d.slug,d.name,d.description,d.owner_id,COALESCE(owner.username,'') AS owner_name,
    d.is_official,d.visibility,d.join_policy,d.archived,d.created_at,d.updated_at,
    COALESCE(m.role_key,'') AS member_role,COALESCE(m.status,'') AS member_status,COALESCE(r.permissions,'[]'::jsonb) AS role_permissions FROM domains d LEFT JOIN users owner ON owner.id=d.owner_id
    LEFT JOIN domain_members m ON m.domain_id=d.id AND m.user_id=NULLIF($1::text,'')::uuid
    LEFT JOIN domain_roles r ON r.domain_id=m.domain_id AND r.key=m.role_key WHERE d.id=$2::uuid
`

type GetDomainScopeByIDParams struct {
	ViewerID string
	DomainID string
}

type GetDomainScopeByIDRow struct {
	ID              string
	Slug            string
	Name            string
	Description     string
	OwnerID         *string
	OwnerName       string
	IsOfficial      bool
	Visibility      string
	JoinPolicy      string
	Archived        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	MemberRole      string
	MemberStatus    string
	RolePermissions json.RawMessage
}

func (q *Queries) GetDomainScopeByID(ctx context.Context, arg GetDomainScopeByIDParams) (GetDomainScopeByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainScopeByID, arg.ViewerID, arg.DomainID)
	var i GetDomainScopeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerName,
		&i.IsOfficial,
		&i.Visibility,
		&i.JoinPolicy,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberRole,
		&i.MemberStatus,
		&i.RolePermissions,
	)
	return i, err
}

const getDomainScopeBySlug = `-- name: GetDomainScopeBySlug :one
SELECT d.id,d.slug,d.name,d.description,d.owner_id,COALESCE(owner.username,'') AS owner_name,
    d.is_official,d.visibility,d.join_policy,d.archived,d.created_at,d.updated_at,
    COALESCE(m.role_key,'') AS member_role,COALESCE(m.status,'') AS member_status,COALESCE(r.permissions,'[]'::jsonb) AS role_permissions FROM domains d LEFT JOIN users owner ON owner.id=d.owner_id
    LEFT JOIN domain_members m ON m.domain_id=d.id AND m.user_id=NULLIF($1::text,'')::uuid
    LEFT JOIN domain_roles r ON r.domain_id=m.domain_id AND r.key=m.role_key WHERE d.slug=$2::text
`

type GetDomainScopeBySlugParams struct {
	ViewerID string
	Slug     string
}

type GetDomainScopeBySlugRow struct {
	ID              string
	Slug            string
	Name            string
	Description     string
	OwnerID         *string
	OwnerName       string
	IsOfficial      bool
	Visibility      string
	JoinPolicy      string
	Archived        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	MemberRole      string
	MemberStatus    string
	RolePermissions json.RawMessage
}

func (q *Queries) GetDomainScopeBySlug(ctx context.Context, arg GetDomainScopeBySlugParams) (GetDomainScopeBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainScopeBySlug, arg.ViewerID, arg.Slug)
	var i GetDomainScopeBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerName,
		&i.IsOfficial,
		&i.Visibility,
		&i.JoinPolicy,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberRole,
		&i.MemberStatus,
		&i.RolePermissions,
	)
	return i, err
}

const getGovernanceActor = `-- name: GetGovernanceActor :one
SELECT id,username,role='admin' AS is_admin FROM users WHERE id=$1::uuid AND disabled_at IS NULL
`

type GetGovernanceActorRow struct {
	ID       string
	Username string
	IsAdmin  bool
}

func (q *Queries) GetGovernanceActor(ctx context.Context, userID string) (GetGovernanceActorRow, error) {
	row := q.db.QueryRowContext(ctx, getGovernanceActor, userID)
	var i GetGovernanceActorRow
	err := row.Scan(&i.ID, &i.Username, &i.IsAdmin)
	return i, err
}

const listAccessibleDomains = `-- name: ListAccessibleDomains :many
SELECT d.id,d.slug,d.name,d.description,d.owner_id,COALESCE(owner.username,'') AS owner_name,
    d.is_official,d.visibility,d.join_policy,d.archived,d.created_at,d.updated_at,
    COALESCE(m.role_key,'') AS member_role,COALESCE(m.status,'') AS member_status,COALESCE(r.permissions,'[]'::jsonb) AS role_permissions FROM domains d LEFT JOIN users owner ON owner.id=d.owner_id
    LEFT JOIN domain_members m ON m.domain_id=d.id AND m.user_id=NULLIF($1::text,'')::uuid
    LEFT JOIN domain_roles r ON r.domain_id=m.domain_id AND r.key=m.role_key WHERE ($2::boolean OR d.visibility='public' OR m.status IN ('active','invited','pending'))
        AND (NOT d.archived OR $2::boolean OR m.status='active') AND (d.name ILIKE $3::text OR d.slug ILIKE $3::text) ORDER BY d.is_official DESC,d.created_at,d.id LIMIT $5::integer OFFSET $4::integer
`

type ListAccessibleDomainsParams struct {
	ViewerID   string
	IsAdmin    bool
	Keyword    string
	PageOffset int
	PageLimit  int
}

type ListAccessibleDomainsRow struct {
	ID              string
	Slug            string
	Name            string
	Description     string
	OwnerID         *string
	OwnerName       string
	IsOfficial      bool
	Visibility      string
	JoinPolicy      string
	Archived        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	MemberRole      string
	MemberStatus    string
	RolePermissions json.RawMessage
}

func (q *Queries) ListAccessibleDomains(ctx context.Context, arg ListAccessibleDomainsParams) ([]ListAccessibleDomainsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccessibleDomains,
		arg.ViewerID,
		arg.IsAdmin,
		arg.Keyword,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessibleDomainsRow{}
	for rows.Next() {
		var i ListAccessibleDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.OwnerName,
			&i.IsOfficial,
			&i.Visibility,
			&i.JoinPolicy,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberRole,
			&i.MemberStatus,
			&i.RolePermissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainGroups = `-- name: ListDomainGroups :many
SELECT g.id,g.public_id,g.domain_id,g.name,g.description,g.owner_id,u.username AS owner_name,g.created_at,
    (SELECT count(*) FROM domain_group_members allgm JOIN domain_members dm ON dm.domain_id=allgm.domain_id AND dm.user_id=allgm.user_id WHERE allgm.group_id=g.id AND dm.status='active')::integer AS member_count,COALESCE(gm.role,'') AS viewer_role FROM domain_groups g JOIN users u ON u.id=g.owner_id
    LEFT JOIN domain_group_members gm ON gm.group_id=g.id AND gm.user_id=NULLIF($1::text,'')::uuid WHERE g.domain_id=$2::uuid AND g.name ILIKE $3::text ORDER BY g.name,g.id LIMIT $5::integer OFFSET $4::integer
`

type ListDomainGroupsParams struct {
	ViewerID   string
	DomainID   string
	Keyword    string
	PageOffset int
	PageLimit  int
}

type ListDomainGroupsRow struct {
	ID          string
	PublicID    string
	DomainID    string
	Name        string
	Description string
	OwnerID     string
	OwnerName   string
	CreatedAt   time.Time
	MemberCount int
	ViewerRole  string
}

func (q *Queries) ListDomainGroups(ctx context.Context, arg ListDomainGroupsParams) ([]ListDomainGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDomainGroups,
		arg.ViewerID,
		arg.DomainID,
		arg.Keyword,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDomainGroupsRow{}
	for rows.Next() {
		var i ListDomainGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.DomainID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.OwnerName,
			&i.CreatedAt,
			&i.MemberCount,
			&i.ViewerRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainMembers = `-- name: ListDomainMembers :many
SELECT m.user_id,u.username,m.role_key,m.status,m.joined_at FROM domain_members m JOIN users u ON u.id=m.user_id
        WHERE m.domain_id=$1::uuid AND u.username ILIKE $2::text ORDER BY m.joined_at,m.user_id LIMIT $4::integer OFFSET $3::integer
`

type ListDomainMembersParams struct {
	DomainID   string
	Keyword    string
	PageOffset int
	PageLimit  int
}

type ListDomainMembersRow struct {
	UserID   string
	Username string
	RoleKey  string
	Status   string
	JoinedAt time.Time
}

func (q *Queries) ListDomainMembers(ctx context.Context, arg ListDomainMembersParams) ([]ListDomainMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listDomainMembers,
		arg.DomainID,
		arg.Keyword,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDomainMembersRow{}
	for rows.Next() {
		var i ListDomainMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.RoleKey,
			&i.Status,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainRoles = `-- name: ListDomainRoles :many
SELECT key,name,permissions,builtin FROM domain_roles WHERE domain_id=$1::uuid ORDER BY builtin DESC,key
`

type ListDomainRolesRow struct {
	Key         string
	Name        string
	Permissions json.RawMessage
	Builtin     bool
}

func (q *Queries) ListDomainRoles(ctx context.Context, domainID string) ([]ListDomainRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDomainRoles, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDomainRolesRow{}
	for rows.Next() {
		var i ListDomainRolesRow
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Permissions,
			&i.Builtin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT gm.user_id,u.username,gm.role FROM domain_group_members gm
        JOIN domain_members dm ON dm.domain_id=gm.domain_id AND dm.user_id=gm.user_id
        JOIN users u ON u.id=gm.user_id WHERE gm.domain_id=$1::uuid AND gm.group_id=$2::uuid AND dm.status='active' AND u.username ILIKE $3::text ORDER BY u.username LIMIT $5::integer OFFSET $4::integer
`

type ListGroupMembersParams struct {
	DomainID   string
	GroupID    string
	Keyword    string
	PageOffset int
	PageLimit  int
}

type ListGroupMembersRow struct {
	UserID   string
	Username string
	Role     string
}

func (q *Queries) ListGroupMembers(ctx context.Context, arg ListGroupMembersParams) ([]ListGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers,
		arg.DomainID,
		arg.GroupID,
		arg.Keyword,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMembersRow{}
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(&i.UserID, &i.Username, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDomainForGovernance = `-- name: LockDomainForGovernance :one
SELECT id FROM domains WHERE slug=$1::text FOR UPDATE
`

func (q *Queries) LockDomainForGovernance(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRowContext(ctx, lockDomainForGovernance, slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockDomainForResourceWrite = `-- name: LockDomainForResourceWrite :one
SELECT 1 FROM domains WHERE id=$1::uuid FOR SHARE
`

func (q *Queries) LockDomainForResourceWrite(ctx context.Context, domainID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, lockDomainForResourceWrite, domainID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const lockGovernanceActor = `-- name: LockGovernanceActor :one
SELECT id,username,role='admin' AS is_admin FROM users WHERE id=$1::uuid AND disabled_at IS NULL FOR SHARE
`

type LockGovernanceActorRow struct {
	ID       string
	Username string
	IsAdmin  bool
}

func (q *Queries) LockGovernanceActor(ctx context.Context, userID string) (LockGovernanceActorRow, error) {
	row := q.db.QueryRowContext(ctx, lockGovernanceActor, userID)
	var i LockGovernanceActorRow
	err := row.Scan(&i.ID, &i.Username, &i.IsAdmin)
	return i, err
}

const lockResourceExclusive = `-- name: LockResourceExclusive :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text,0))
`

func (q *Queries) LockResourceExclusive(ctx context.Context, resourceKey string) error {
	_, err := q.db.ExecContext(ctx, lockResourceExclusive, resourceKey)
	return err
}

const lockResourceShared = `-- name: LockResourceShared :exec
SELECT pg_advisory_xact_lock_shared(hashtextextended($1::text,0))
`

func (q *Queries) LockResourceShared(ctx context.Context, resourceKey string) error {
	_, err := q.db.ExecContext(ctx, lockResourceShared, resourceKey)
	return err
}

const lookupDomainMember = `-- name: LookupDomainMember :one
SELECT u.id AS user_id,u.username,COALESCE(m.role_key,'') AS role_key,COALESCE(m.status,'') AS status,COALESCE(m.joined_at,u.created_at)::timestamptz AS joined_at
        FROM users u LEFT JOIN domain_members m ON m.user_id=u.id AND m.domain_id=$1::uuid
        WHERE u.username=$2::text AND (NOT $3::boolean OR u.disabled_at IS NULL) FOR SHARE OF u
`

type LookupDomainMemberParams struct {
	DomainID          string
	Username          string
	ActiveAccountOnly bool
}

type LookupDomainMemberRow struct {
	UserID   string
	Username string
	RoleKey  string
	Status   string
	JoinedAt time.Time
}

func (q *Queries) LookupDomainMember(ctx context.Context, arg LookupDomainMemberParams) (LookupDomainMemberRow, error) {
	row := q.db.QueryRowContext(ctx, lookupDomainMember, arg.DomainID, arg.Username, arg.ActiveAccountOnly)
	var i LookupDomainMemberRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.RoleKey,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const promoteNewDomainOwner = `-- name: PromoteNewDomainOwner :exec
UPDATE domain_members SET role_key='admin',updated_at=now() WHERE domain_id=$1::uuid AND user_id=$2::uuid
`

type PromoteNewDomainOwnerParams struct {
	DomainID string
	UserID   string
}

func (q *Queries) PromoteNewDomainOwner(ctx context.Context, arg PromoteNewDomainOwnerParams) error {
	_, err := q.db.ExecContext(ctx, promoteNewDomainOwner, arg.DomainID, arg.UserID)
	return err
}

const recordDomainAudit = `-- name: RecordDomainAudit :exec
INSERT INTO domain_audit_events(domain_id,actor_id,action,target) VALUES($1::uuid,$2::uuid,$3::text,$4::text)
`

type RecordDomainAuditParams struct {
	DomainID string
	ActorID  string
	Action   string
	Target   string
}

func (q *Queries) RecordDomainAudit(ctx context.Context, arg RecordDomainAuditParams) error {
	_, err := q.db.ExecContext(ctx, recordDomainAudit,
		arg.DomainID,
		arg.ActorID,
		arg.Action,
		arg.Target,
	)
	return err
}

const seedDomainRole = `-- name: SeedDomainRole :exec
INSERT INTO domain_roles(domain_id,key,name,permissions,builtin) VALUES($1::uuid,$2::text,$3::text,$4::jsonb,TRUE) ON CONFLICT(domain_id,key) DO NOTHING
`

type SeedDomainRoleParams struct {
	DomainID    string
	Key         string
	Name        string
	Permissions json.RawMessage
}

func (q *Queries) SeedDomainRole(ctx context.Context, arg SeedDomainRoleParams) error {
	_, err := q.db.ExecContext(ctx, seedDomainRole,
		arg.DomainID,
		arg.Key,
		arg.Name,
		arg.Permissions,
	)
	return err
}

const transferDomainOwner = `-- name: TransferDomainOwner :exec
UPDATE domains SET owner_id=$1::uuid,updated_at=now() WHERE id=$2::uuid
`

type TransferDomainOwnerParams struct {
	OwnerID  string
	DomainID string
}

func (q *Queries) TransferDomainOwner(ctx context.Context, arg TransferDomainOwnerParams) error {
	_, err := q.db.ExecContext(ctx, transferDomainOwner, arg.OwnerID, arg.DomainID)
	return err
}

const transferGroupOwner = `-- name: TransferGroupOwner :exec
UPDATE domain_groups SET owner_id=$1::uuid,updated_at=now() WHERE domain_id=$2::uuid AND id=$3::uuid
`

type TransferGroupOwnerParams struct {
	OwnerID  string
	DomainID string
	GroupID  string
}

func (q *Queries) TransferGroupOwner(ctx context.Context, arg TransferGroupOwnerParams) error {
	_, err := q.db.ExecContext(ctx, transferGroupOwner, arg.OwnerID, arg.DomainID, arg.GroupID)
	return err
}

const updateDomain = `-- name: UpdateDomain :exec
UPDATE domains SET name=$1::text,description=$2::text,visibility=$3::text,join_policy=$4::text,updated_at=now() WHERE id=$5::uuid
`

type UpdateDomainParams struct {
	Name        string
	Description string
	Visibility  string
	JoinPolicy  string
	DomainID    string
}

func (q *Queries) UpdateDomain(ctx context.Context, arg UpdateDomainParams) error {
	_, err := q.db.ExecContext(ctx, updateDomain,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.JoinPolicy,
		arg.DomainID,
	)
	return err
}

const updateDomainGroup = `-- name: UpdateDomainGroup :exec
UPDATE domain_groups SET name=$1::text,description=$2::text,updated_at=now() WHERE domain_id=$3::uuid AND id=$4::uuid
`

type UpdateDomainGroupParams struct {
	Name        string
	Description string
	DomainID    string
	GroupID     string
}

func (q *Queries) UpdateDomainGroup(ctx context.Context, arg UpdateDomainGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateDomainGroup,
		arg.Name,
		arg.Description,
		arg.DomainID,
		arg.GroupID,
	)
	return err
}

const upsertDomainMember = `-- name: UpsertDomainMember :exec
INSERT INTO domain_members(domain_id,user_id,role_key,status) VALUES($1::uuid,$2::uuid,$3::text,$4::text)
        ON CONFLICT(domain_id,user_id) DO UPDATE SET role_key=EXCLUDED.role_key,status=EXCLUDED.status,updated_at=now()
`

type UpsertDomainMemberParams struct {
	DomainID string
	UserID   string
	RoleKey  string
	Status   string
}

func (q *Queries) UpsertDomainMember(ctx context.Context, arg UpsertDomainMemberParams) error {
	_, err := q.db.ExecContext(ctx, upsertDomainMember,
		arg.DomainID,
		arg.UserID,
		arg.RoleKey,
		arg.Status,
	)
	return err
}

const upsertDomainRole = `-- name: UpsertDomainRole :exec
INSERT INTO domain_roles(domain_id,key,name,permissions) VALUES($1::uuid,$2::text,$3::text,$4::jsonb)
        ON CONFLICT(domain_id,key) DO UPDATE SET name=EXCLUDED.name,permissions=EXCLUDED.permissions WHERE NOT domain_roles.builtin
`

type UpsertDomainRoleParams struct {
	DomainID    string
	Key         string
	Name        string
	Permissions json.RawMessage
}

func (q *Queries) UpsertDomainRole(ctx context.Context, arg UpsertDomainRoleParams) error {
	_, err := q.db.ExecContext(ctx, upsertDomainRole,
		arg.DomainID,
		arg.Key,
		arg.Name,
		arg.Permissions,
	)
	return err
}

const upsertGroupMember = `-- name: UpsertGroupMember :exec
INSERT INTO domain_group_members(domain_id,group_id,user_id,role) VALUES($1::uuid,$2::uuid,$3::uuid,$4::text)
        ON CONFLICT(group_id,user_id) DO UPDATE SET role=EXCLUDED.role
`

type UpsertGroupMemberParams struct {
	DomainID string
	GroupID  string
	UserID   string
	Role     string
}

func (q *Queries) UpsertGroupMember(ctx context.Context, arg UpsertGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, upsertGroupMember,
		arg.DomainID,
		arg.GroupID,
		arg.UserID,
		arg.Role,
	)
	return err
}
