// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const checkEditorialParent = `-- name: CheckEditorialParent :one
SELECT 1 FROM discussion_posts WHERE id=$1::bigint AND domain_id=$2::uuid AND editorial_id=$3::uuid FOR SHARE
`

type CheckEditorialParentParams struct {
	ParentID int64
	DomainID string
	TargetID string
}

func (q *Queries) CheckEditorialParent(ctx context.Context, arg CheckEditorialParentParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, checkEditorialParent, arg.ParentID, arg.DomainID, arg.TargetID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const checkProblemParent = `-- name: CheckProblemParent :one
SELECT 1 FROM discussion_posts WHERE id=$1::bigint AND domain_id=$2::uuid AND problem_id=$3::uuid FOR SHARE
`

type CheckProblemParentParams struct {
	ParentID int64
	DomainID string
	TargetID string
}

func (q *Queries) CheckProblemParent(ctx context.Context, arg CheckProblemParentParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, checkProblemParent, arg.ParentID, arg.DomainID, arg.TargetID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countVisibleEditorials = `-- name: CountVisibleEditorials :one
SELECT count(*) FROM editorials e JOIN problems p ON p.id=e.problem_id LEFT JOIN users u ON u.id=e.author_id
WHERE e.domain_id=$1::uuid AND (p.visibility='public' AND p.published_version IS NOT NULL OR $2::boolean OR ($3::boolean AND (p.owner_id=NULLIF($4::text,'')::uuid OR EXISTS(SELECT 1 FROM problem_access a WHERE a.problem_id=p.id AND a.domain_id=p.domain_id AND (a.user_id=NULLIF($4::text,'')::uuid OR a.group_id IN(SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($4::text,'')::uuid)))))) AND ((e.visibility='public' AND e.status='published') OR $2::boolean OR ($3::boolean AND e.author_id=NULLIF($4::text,'')::uuid)) AND ($5::text='' OR e.problem_id=NULLIF($5::text,'')::uuid) AND ($6::text='' OR e.author_id=NULLIF($6::text,'')::uuid) AND ($7::text='' OR e.title ILIKE '%'||$7::text||'%' OR p.title ILIKE '%'||$7::text||'%')
`

type CountVisibleEditorialsParams struct {
	DomainID      string
	IsManager     bool
	ActiveMember  bool
	ViewerID      string
	ProblemFilter string
	AuthorFilter  string
	Keyword       string
}

func (q *Queries) CountVisibleEditorials(ctx context.Context, arg CountVisibleEditorialsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVisibleEditorials,
		arg.DomainID,
		arg.IsManager,
		arg.ActiveMember,
		arg.ViewerID,
		arg.ProblemFilter,
		arg.AuthorFilter,
		arg.Keyword,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEditorialPost = `-- name: CreateEditorialPost :one
INSERT INTO discussion_posts(domain_id,editorial_id,author_id,content_md,parent_id) VALUES($1::uuid,$2::uuid,$3::uuid,$4::text,$5::bigint) RETURNING id
`

type CreateEditorialPostParams struct {
	DomainID string
	TargetID string
	UserID   string
	Body     string
	ParentID sql.NullInt64
}

func (q *Queries) CreateEditorialPost(ctx context.Context, arg CreateEditorialPostParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createEditorialPost,
		arg.DomainID,
		arg.TargetID,
		arg.UserID,
		arg.Body,
		arg.ParentID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createProblemPost = `-- name: CreateProblemPost :one
INSERT INTO discussion_posts(domain_id,problem_id,author_id,content_md,parent_id) VALUES($1::uuid,$2::uuid,$3::uuid,$4::text,$5::bigint) RETURNING id
`

type CreateProblemPostParams struct {
	DomainID string
	TargetID string
	UserID   string
	Body     string
	ParentID sql.NullInt64
}

func (q *Queries) CreateProblemPost(ctx context.Context, arg CreateProblemPostParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createProblemPost,
		arg.DomainID,
		arg.TargetID,
		arg.UserID,
		arg.Body,
		arg.ParentID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPost = `-- name: GetPost :one
SELECT d.id,d.problem_id,d.editorial_id,d.author_id,COALESCE(u.username,'') AS author_name,d.content_md,d.parent_id,d.created_at,d.updated_at,d.domain_id FROM discussion_posts d LEFT JOIN users u ON u.id=d.author_id WHERE d.domain_id=$1::uuid AND d.id=$2::bigint
`

type GetPostParams struct {
	DomainID string
	PostID   int64
}

type GetPostRow struct {
	ID          int64
	ProblemID   *string
	EditorialID *string
	AuthorID    *string
	AuthorName  string
	ContentMd   string
	ParentID    sql.NullInt64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DomainID    string
}

func (q *Queries) GetPost(ctx context.Context, arg GetPostParams) (GetPostRow, error) {
	row := q.db.QueryRowContext(ctx, getPost, arg.DomainID, arg.PostID)
	var i GetPostRow
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.EditorialID,
		&i.AuthorID,
		&i.AuthorName,
		&i.ContentMd,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainID,
	)
	return i, err
}

const getVisibleEditorial = `-- name: GetVisibleEditorial :one
SELECT e.id,e.public_id,e.problem_id,p.public_id AS problem_public_id,p.title AS problem_title,e.author_id,COALESCE(u.username,'') AS author_name,e.title,e.visibility,e.status,e.solved_only,e.vote_count,EXISTS(SELECT 1 FROM editorial_votes votes WHERE votes.editorial_id=e.id AND votes.user_id=NULLIF($1::text,'')::uuid) AS voted,e.created_at,e.updated_at,e.domain_id,p.owner_id AS problem_owner_id,EXISTS(SELECT 1 FROM submissions sub WHERE sub.domain_id=e.domain_id AND sub.problem_id=e.problem_id AND sub.user_id=NULLIF($1::text,'')::uuid AND sub.contest_id IS NULL AND sub.status='Accepted') AS solved,CASE WHEN (NOT e.solved_only OR ($2::boolean AND e.author_id=NULLIF($1::text,'')::uuid) OR ($3::boolean OR ($2::boolean AND p.owner_id=NULLIF($1::text,'')::uuid)) OR EXISTS(SELECT 1 FROM submissions sub WHERE sub.domain_id=e.domain_id AND sub.problem_id=e.problem_id AND sub.user_id=NULLIF($1::text,'')::uuid AND sub.contest_id IS NULL AND sub.status='Accepted')) THEN e.content_md ELSE '' END::text AS content_md FROM editorials e JOIN problems p ON p.id=e.problem_id LEFT JOIN users u ON u.id=e.author_id
WHERE e.domain_id=$4::uuid AND (p.visibility='public' AND p.published_version IS NOT NULL OR $3::boolean OR ($2::boolean AND (p.owner_id=NULLIF($1::text,'')::uuid OR EXISTS(SELECT 1 FROM problem_access a WHERE a.problem_id=p.id AND a.domain_id=p.domain_id AND (a.user_id=NULLIF($1::text,'')::uuid OR a.group_id IN(SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($1::text,'')::uuid)))))) AND ((e.visibility='public' AND e.status='published') OR $3::boolean OR ($2::boolean AND e.author_id=NULLIF($1::text,'')::uuid)) AND e.id=$5::uuid
`

type GetVisibleEditorialParams struct {
	ViewerID     string
	ActiveMember bool
	IsManager    bool
	DomainID     string
	EditorialID  string
}

type GetVisibleEditorialRow struct {
	ID              string
	PublicID        string
	ProblemID       string
	ProblemPublicID string
	ProblemTitle    string
	AuthorID        *string
	AuthorName      string
	Title           string
	Visibility      string
	Status          string
	SolvedOnly      bool
	VoteCount       int
	Voted           bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DomainID        string
	ProblemOwnerID  string
	Solved          bool
	ContentMd       string
}

func (q *Queries) GetVisibleEditorial(ctx context.Context, arg GetVisibleEditorialParams) (GetVisibleEditorialRow, error) {
	row := q.db.QueryRowContext(ctx, getVisibleEditorial,
		arg.ViewerID,
		arg.ActiveMember,
		arg.IsManager,
		arg.DomainID,
		arg.EditorialID,
	)
	var i GetVisibleEditorialRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProblemID,
		&i.ProblemPublicID,
		&i.ProblemTitle,
		&i.AuthorID,
		&i.AuthorName,
		&i.Title,
		&i.Visibility,
		&i.Status,
		&i.SolvedOnly,
		&i.VoteCount,
		&i.Voted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainID,
		&i.ProblemOwnerID,
		&i.Solved,
		&i.ContentMd,
	)
	return i, err
}

const listEditorialPosts = `-- name: ListEditorialPosts :many
SELECT d.id,d.problem_id,d.editorial_id,d.author_id,COALESCE(u.username,'') AS author_name,d.content_md,d.parent_id,d.created_at,d.updated_at,d.domain_id FROM discussion_posts d LEFT JOIN users u ON u.id=d.author_id WHERE d.domain_id=$1::uuid AND d.editorial_id=$2::uuid ORDER BY d.created_at,d.id
`

type ListEditorialPostsParams struct {
	DomainID string
	TargetID string
}

type ListEditorialPostsRow struct {
	ID          int64
	ProblemID   *string
	EditorialID *string
	AuthorID    *string
	AuthorName  string
	ContentMd   string
	ParentID    sql.NullInt64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DomainID    string
}

func (q *Queries) ListEditorialPosts(ctx context.Context, arg ListEditorialPostsParams) ([]ListEditorialPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEditorialPosts, arg.DomainID, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEditorialPostsRow{}
	for rows.Next() {
		var i ListEditorialPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.EditorialID,
			&i.AuthorID,
			&i.AuthorName,
			&i.ContentMd,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DomainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemPosts = `-- name: ListProblemPosts :many
SELECT d.id,d.problem_id,d.editorial_id,d.author_id,COALESCE(u.username,'') AS author_name,d.content_md,d.parent_id,d.created_at,d.updated_at,d.domain_id FROM discussion_posts d LEFT JOIN users u ON u.id=d.author_id WHERE d.domain_id=$1::uuid AND d.problem_id=$2::uuid ORDER BY d.created_at,d.id
`

type ListProblemPostsParams struct {
	DomainID string
	TargetID string
}

type ListProblemPostsRow struct {
	ID          int64
	ProblemID   *string
	EditorialID *string
	AuthorID    *string
	AuthorName  string
	ContentMd   string
	ParentID    sql.NullInt64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DomainID    string
}

func (q *Queries) ListProblemPosts(ctx context.Context, arg ListProblemPostsParams) ([]ListProblemPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProblemPosts, arg.DomainID, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProblemPostsRow{}
	for rows.Next() {
		var i ListProblemPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.EditorialID,
			&i.AuthorID,
			&i.AuthorName,
			&i.ContentMd,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DomainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleEditorials = `-- name: ListVisibleEditorials :many
SELECT e.id,e.public_id,e.problem_id,p.public_id AS problem_public_id,p.title AS problem_title,e.author_id,COALESCE(u.username,'') AS author_name,e.title,e.visibility,e.status,e.solved_only,e.vote_count,EXISTS(SELECT 1 FROM editorial_votes votes WHERE votes.editorial_id=e.id AND votes.user_id=NULLIF($1::text,'')::uuid) AS voted,e.created_at,e.updated_at,e.domain_id,p.owner_id AS problem_owner_id,EXISTS(SELECT 1 FROM submissions sub WHERE sub.domain_id=e.domain_id AND sub.problem_id=e.problem_id AND sub.user_id=NULLIF($1::text,'')::uuid AND sub.contest_id IS NULL AND sub.status='Accepted') AS solved,''::text AS content_md FROM editorials e JOIN problems p ON p.id=e.problem_id LEFT JOIN users u ON u.id=e.author_id
WHERE e.domain_id=$2::uuid AND (p.visibility='public' AND p.published_version IS NOT NULL OR $3::boolean OR ($4::boolean AND (p.owner_id=NULLIF($1::text,'')::uuid OR EXISTS(SELECT 1 FROM problem_access a WHERE a.problem_id=p.id AND a.domain_id=p.domain_id AND (a.user_id=NULLIF($1::text,'')::uuid OR a.group_id IN(SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($1::text,'')::uuid)))))) AND ((e.visibility='public' AND e.status='published') OR $3::boolean OR ($4::boolean AND e.author_id=NULLIF($1::text,'')::uuid)) AND ($5::text='' OR e.problem_id=NULLIF($5::text,'')::uuid) AND ($6::text='' OR e.author_id=NULLIF($6::text,'')::uuid) AND ($7::text='' OR e.title ILIKE '%'||$7::text||'%' OR p.title ILIKE '%'||$7::text||'%')
ORDER BY CASE WHEN $8::boolean THEN e.vote_count ELSE 0 END DESC,e.created_at DESC,e.id DESC LIMIT $10::integer OFFSET $9::integer
`

type ListVisibleEditorialsParams struct {
	ViewerID      string
	DomainID      string
	IsManager     bool
	ActiveMember  bool
	ProblemFilter string
	AuthorFilter  string
	Keyword       string
	SortVotes     bool
	PageOffset    int
	PageLimit     int
}

type ListVisibleEditorialsRow struct {
	ID              string
	PublicID        string
	ProblemID       string
	ProblemPublicID string
	ProblemTitle    string
	AuthorID        *string
	AuthorName      string
	Title           string
	Visibility      string
	Status          string
	SolvedOnly      bool
	VoteCount       int
	Voted           bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DomainID        string
	ProblemOwnerID  string
	Solved          bool
	ContentMd       string
}

func (q *Queries) ListVisibleEditorials(ctx context.Context, arg ListVisibleEditorialsParams) ([]ListVisibleEditorialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleEditorials,
		arg.ViewerID,
		arg.DomainID,
		arg.IsManager,
		arg.ActiveMember,
		arg.ProblemFilter,
		arg.AuthorFilter,
		arg.Keyword,
		arg.SortVotes,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleEditorialsRow{}
	for rows.Next() {
		var i ListVisibleEditorialsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ProblemID,
			&i.ProblemPublicID,
			&i.ProblemTitle,
			&i.AuthorID,
			&i.AuthorName,
			&i.Title,
			&i.Visibility,
			&i.Status,
			&i.SolvedOnly,
			&i.VoteCount,
			&i.Voted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DomainID,
			&i.ProblemOwnerID,
			&i.Solved,
			&i.ContentMd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPost = `-- name: LockPost :one
SELECT d.id,d.problem_id,d.editorial_id,d.author_id,COALESCE(u.username,'') AS author_name,d.content_md,d.parent_id,d.created_at,d.updated_at,d.domain_id FROM discussion_posts d LEFT JOIN users u ON u.id=d.author_id WHERE d.domain_id=$1::uuid AND d.id=$2::bigint FOR UPDATE OF d
`

type LockPostParams struct {
	DomainID string
	PostID   int64
}

type LockPostRow struct {
	ID          int64
	ProblemID   *string
	EditorialID *string
	AuthorID    *string
	AuthorName  string
	ContentMd   string
	ParentID    sql.NullInt64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DomainID    string
}

func (q *Queries) LockPost(ctx context.Context, arg LockPostParams) (LockPostRow, error) {
	row := q.db.QueryRowContext(ctx, lockPost, arg.DomainID, arg.PostID)
	var i LockPostRow
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.EditorialID,
		&i.AuthorID,
		&i.AuthorName,
		&i.ContentMd,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainID,
	)
	return i, err
}

const lockVisibleEditorial = `-- name: LockVisibleEditorial :one
SELECT e.id,e.public_id,e.problem_id,p.public_id AS problem_public_id,p.title AS problem_title,e.author_id,COALESCE(u.username,'') AS author_name,e.title,e.visibility,e.status,e.solved_only,e.vote_count,EXISTS(SELECT 1 FROM editorial_votes votes WHERE votes.editorial_id=e.id AND votes.user_id=NULLIF($1::text,'')::uuid) AS voted,e.created_at,e.updated_at,e.domain_id,p.owner_id AS problem_owner_id,EXISTS(SELECT 1 FROM submissions sub WHERE sub.domain_id=e.domain_id AND sub.problem_id=e.problem_id AND sub.user_id=NULLIF($1::text,'')::uuid AND sub.contest_id IS NULL AND sub.status='Accepted') AS solved,CASE WHEN (NOT e.solved_only OR ($2::boolean AND e.author_id=NULLIF($1::text,'')::uuid) OR ($3::boolean OR ($2::boolean AND p.owner_id=NULLIF($1::text,'')::uuid)) OR EXISTS(SELECT 1 FROM submissions sub WHERE sub.domain_id=e.domain_id AND sub.problem_id=e.problem_id AND sub.user_id=NULLIF($1::text,'')::uuid AND sub.contest_id IS NULL AND sub.status='Accepted')) THEN e.content_md ELSE '' END::text AS content_md FROM editorials e JOIN problems p ON p.id=e.problem_id LEFT JOIN users u ON u.id=e.author_id
WHERE e.domain_id=$4::uuid AND (p.visibility='public' AND p.published_version IS NOT NULL OR $3::boolean OR ($2::boolean AND (p.owner_id=NULLIF($1::text,'')::uuid OR EXISTS(SELECT 1 FROM problem_access a WHERE a.problem_id=p.id AND a.domain_id=p.domain_id AND (a.user_id=NULLIF($1::text,'')::uuid OR a.group_id IN(SELECT group_id FROM domain_group_members WHERE domain_id=p.domain_id AND user_id=NULLIF($1::text,'')::uuid)))))) AND ((e.visibility='public' AND e.status='published') OR $3::boolean OR ($2::boolean AND e.author_id=NULLIF($1::text,'')::uuid)) AND e.id=$5::uuid FOR UPDATE OF e
`

type LockVisibleEditorialParams struct {
	ViewerID     string
	ActiveMember bool
	IsManager    bool
	DomainID     string
	EditorialID  string
}

type LockVisibleEditorialRow struct {
	ID              string
	PublicID        string
	ProblemID       string
	ProblemPublicID string
	ProblemTitle    string
	AuthorID        *string
	AuthorName      string
	Title           string
	Visibility      string
	Status          string
	SolvedOnly      bool
	VoteCount       int
	Voted           bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DomainID        string
	ProblemOwnerID  string
	Solved          bool
	ContentMd       string
}

func (q *Queries) LockVisibleEditorial(ctx context.Context, arg LockVisibleEditorialParams) (LockVisibleEditorialRow, error) {
	row := q.db.QueryRowContext(ctx, lockVisibleEditorial,
		arg.ViewerID,
		arg.ActiveMember,
		arg.IsManager,
		arg.DomainID,
		arg.EditorialID,
	)
	var i LockVisibleEditorialRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ProblemID,
		&i.ProblemPublicID,
		&i.ProblemTitle,
		&i.AuthorID,
		&i.AuthorName,
		&i.Title,
		&i.Visibility,
		&i.Status,
		&i.SolvedOnly,
		&i.VoteCount,
		&i.Voted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainID,
		&i.ProblemOwnerID,
		&i.Solved,
		&i.ContentMd,
	)
	return i, err
}
