// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package dbgen

import (
	"context"
	"time"
)

const getProfileAccount = `-- name: GetProfileAccount :one
SELECT id, username, role, rating, created_at
FROM users WHERE username = $1::text
`

type GetProfileAccountRow struct {
	ID        string
	Username  string
	Role      string
	Rating    int
	CreatedAt time.Time
}

func (q *Queries) GetProfileAccount(ctx context.Context, username string) (GetProfileAccountRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileAccount, username)
	var i GetProfileAccountRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const getProfileSubmissionStats = `-- name: GetProfileSubmissionStats :one
SELECT count(DISTINCT s.problem_id) FILTER (WHERE s.status = 'Accepted')::integer AS solved_count,
       count(DISTINCT s.problem_id)::integer AS attempted_count,
       count(*)::integer AS submission_count,
       count(*) FILTER (WHERE s.status = 'Accepted')::integer AS accepted_count
FROM submissions s
WHERE s.user_id = $1::uuid AND s.contest_id IS NULL
  AND s.domain_id = $2::uuid
  AND EXISTS (SELECT 1 FROM problems p WHERE p.id = s.problem_id
              AND p.visibility = 'public' AND p.published_version IS NOT NULL)
`

type GetProfileSubmissionStatsParams struct {
	UserID   string
	DomainID string
}

type GetProfileSubmissionStatsRow struct {
	SolvedCount     int
	AttemptedCount  int
	SubmissionCount int
	AcceptedCount   int
}

func (q *Queries) GetProfileSubmissionStats(ctx context.Context, arg GetProfileSubmissionStatsParams) (GetProfileSubmissionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileSubmissionStats, arg.UserID, arg.DomainID)
	var i GetProfileSubmissionStatsRow
	err := row.Scan(
		&i.SolvedCount,
		&i.AttemptedCount,
		&i.SubmissionCount,
		&i.AcceptedCount,
	)
	return i, err
}

const listProfileActivity = `-- name: ListProfileActivity :many
SELECT to_char(s.submitted_at AT TIME ZONE 'UTC', 'YYYY-MM-DD')::text AS date, count(*)::integer AS count
FROM submissions s
WHERE s.user_id = $1::uuid AND s.contest_id IS NULL
  AND s.domain_id = $2::uuid
  AND EXISTS (SELECT 1 FROM problems p WHERE p.id = s.problem_id
              AND p.visibility = 'public' AND p.published_version IS NOT NULL)
  AND s.submitted_at >= now() - $3::integer * interval '1 day'
GROUP BY date ORDER BY date
`

type ListProfileActivityParams struct {
	UserID     string
	DomainID   string
	WindowDays int
}

type ListProfileActivityRow struct {
	Date  string
	Count int
}

func (q *Queries) ListProfileActivity(ctx context.Context, arg ListProfileActivityParams) ([]ListProfileActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfileActivity, arg.UserID, arg.DomainID, arg.WindowDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfileActivityRow{}
	for rows.Next() {
		var i ListProfileActivityRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileDifficultyStats = `-- name: ListProfileDifficultyStats :many
SELECT p.difficulty,
       count(*) FILTER (WHERE solved.problem_id IS NOT NULL)::integer AS solved,
       count(*)::integer AS total
FROM problems p
LEFT JOIN (
    SELECT DISTINCT s.problem_id FROM submissions s
    WHERE s.user_id = $1::uuid AND s.contest_id IS NULL AND s.status = 'Accepted'
) solved ON solved.problem_id = p.id
WHERE p.visibility = 'public' AND p.published_version IS NOT NULL AND p.domain_id = $2::uuid
GROUP BY p.difficulty ORDER BY p.difficulty
`

type ListProfileDifficultyStatsParams struct {
	UserID   string
	DomainID string
}

type ListProfileDifficultyStatsRow struct {
	Difficulty int
	Solved     int
	Total      int
}

func (q *Queries) ListProfileDifficultyStats(ctx context.Context, arg ListProfileDifficultyStatsParams) ([]ListProfileDifficultyStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfileDifficultyStats, arg.UserID, arg.DomainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfileDifficultyStatsRow{}
	for rows.Next() {
		var i ListProfileDifficultyStatsRow
		if err := rows.Scan(&i.Difficulty, &i.Solved, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
